### ISSUE TITLE
try to use hook script to register export dofile

### ISSUE THREAD

**Issue by derammo** [HeliosVirtualCockpit/Helios#184]
* created by @derammo on 2020-02-02 14:52:22 +0000 UTC
* assignees: derammo

https://forums.eagle.ru/showthread.php?t=261861

### please make sure to close upstream issue when this item is closed

**Comment by derammo** [comment]
result1: yes we can call code in the export context from the hook callbacks, but we would need to install the Lua... hooks earlier than onSimulationStart (they don't get called) or restructure everything to do our work on onSimulationFrame() callback

**Comment by derammo** [comment]
example calling export script in the export context (but failing to register any Lua... callbacks)
[HeliosGameGUI.zip](https://github.com/HeliosVirtualCockpit/Helios/files/5058329/HeliosGameGUI.zip)

**Comment by BlueFinBima** [comment]
Agreed, not worth it.
