### ISSUE TITLE
Unlock all in Layers

### ISSUE THREAD

**Issue by derammo** [HeliosVirtualCockpit/Helios#221]
* created by @Todd1215 on 2020-04-17 15:48:29 +0000 UTC

This is a creature comfort request. When you have a zillion Layers and want to unlock them all it gets a little tedious at times to click on each one to unlock them all. It would be nice to have a separate way of selectively selecting layers or select all layers to lock or unlock them. Kind of like when you can ALT-A to select all of something or hold CTRL and selectively select something. Its windows intuitive so would seem natural to most users.

### please make sure to close upstream issue when this item is closed

**Comment by ertiyu** [comment]
This request has been resolved.
