### ISSUE TITLE
RWR FALCON BMS

### ISSUE THREAD

**Issue by derammo** [HeliosVirtualCockpit/Helios#223]
* created by @ertiyu on 2020-04-23 14:41:42 +0000 UTC

Looking at the gauges of the F16, I rematched that the RWR does not correctly display the position of the contacts, they are a circle more ready than on the F16.
In addition, functions are on the "Output" side when it should be on the "input" side.

RWR BMS
![RWR BMS](https://user-images.githubusercontent.com/52707215/80111506-40f00000-8580-11ea-8a7b-c22a877ce8ac.png)

RWR HELIOS
![RWR HELIOS](https://user-images.githubusercontent.com/52707215/80111516-42212d00-8580-11ea-99c5-fe34edce7cb1.PNG)

![RWR input output](https://user-images.githubusercontent.com/52707215/80112261-31bd8200-8581-11ea-873e-cd1d2ca81526.png)

### comment by @Todd1215 on 2020-04-23 15:58:30 +0000 UTC

The contacts in RWR are not in the correct threat circle. Confirmed that this is a valid issue. I also confirmed that this also occurs in Helios 1.3 so the problem goes all the way back to Gadroc's Helios. 

Regarding the input & output I'm not sure what the intention was here as this control is updated only from sharedmemory and there is already bindings for Threat Warning Prime buttons external to this RWR control. Possibly it is setup this way for one of the other versions of falcon.

### comment by @Todd1215 on 2020-04-24 14:32:33 +0000 UTC

I tested this fix and the contacts now map into the correct threat ring. The only issue I see is that they look slightly off in location compared to BMS RWR export. 

Old RWR scope contacts, left is the Helios RWR and the right is the RWREmulator 
![old_scope](https://user-images.githubusercontent.com/6605805/80223195-f325d700-8615-11ea-93d2-d7abd645acde.PNG)

Fixed RWR scope contacts, left is the Helios RWR and the right is the RWREmulator 
![new_scope](https://user-images.githubusercontent.com/6605805/80223248-09cc2e00-8616-11ea-853e-23dd431698ce.PNG)

The contacts from the Helios RWR look slightly off. This I believe is an illusion based on the fact that the two scopes are using slightly different bezels. The Helios RWR bezel uses the same one from the A-10 Gauges in Helios. From what I can tell is the F-16 in BMS the bezel middle portion is slightly larger than the Helios bezel. I don't think this is a huge issue because the scope is based on threat rings not distance and the contacts do migrate properly based on threat.

## migrated from https://github.com/BlueFinBima/Helios/issues/223

**Comment by Todd1215** [comment]
Just for the sake of documenting the issue with the RWR bindings being on the wrong side "output" instead of "input". The point of bindings being on the output side are so that a profile creator can use those to output to the TWPR indicators to turn them on,off, and flash some of them based upon the state of the contacts within scope.
