### ISSUE TITLE
HELIOS Tested .key

### ISSUE THREAD

**Issue by derammo** [HeliosVirtualCockpit/Helios#225]
* created by @ertiyu on 2020-04-28 12:08:40 +0000 UTC

Hello,
After having wanted to install a profile with a user, we realized that if an order key, for example (SimCBEOSB_2L) is not present in its Keyfile, Helios cannot perform the shortcut. Normal behavior since the program does not know the keyboard shortcut to perform.
The ideal would therefore be that Helios via a ".log" for example exports the name of the commands without keyboard shortcut, so that the player can add them to his Keyfile without having to look in the entire profile to see if there are any forget.

------------------------------------------------------------------------------------------------------------

Bonjour,
Apres avoir voulu installer un profil chez un utilisateur nous nous sommes rendu compte que si une clé de commande, par exemple (SimCBEOSB_2L) n'est pas présente dans son Keyfile, Helios ne peut pas effectuer le racourci. Comportement normal puisque le programme ne sait pas le raccourcie clavier à effectuer.
L’idéal serait donc que Helios via un ".log" par exemple exporte le nom des commandes sans raccourci clavier, afin que le joueur puisse les ajouter dans son Keyfile sans avoir à regarder dans tout le profil pour voir s'il y a des oublis.

### comment by @derammo on 2020-04-28 12:18:03 +0000 UTC

yes i want to do this 

also will show in UI when running in 1.6

Sent from my iPhone

> On Apr 28, 2020, at 08:08, ertiyu <notifications@github.com> wrote:
> 
> ﻿
> Hello,
> After having wanted to install a profile with a user, we realized that if an order key, for example (SimCBEOSB_2L) is not present in its Keyfile, Helios cannot perform the shortcut. Normal behavior since the program does not know the keyboard shortcut to perform.
> The ideal would therefore be that Helios via a ".log" for example exports the name of the commands without keyboard shortcut, so that the player can add them to his Keyfile without having to look in the entire profile to see if there are any forget.
> 
> Bonjour,
> Apres avoir voulu installer un profil chez un utilisateur nous nous sommes rendu compte que si une clé de commande, par exemple (SimCBEOSB_2L) n'est pas présente dans son Keyfile, Helios ne peut pas effectuer le racourci. Comportement normal puisque le programme ne sait pas le raccourcie clavier à effectuer.
> L’idéal serait donc que Helios via un ".log" par exemple exporte le nom des commandes sans raccourci clavier, afin que le joueur puisse les ajouter dans son Keyfile sans avoir à regarder dans tout le profil pour voir s'il y a des oublis.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

### comment by @ertiyu on 2020-04-28 13:18:16 +0000 UTC

Thank you @derammo !
No urgency, it was just to find out if it was possible.

### comment by @ertiyu on 2020-04-28 13:46:13 +0000 UTC

A test profile
[TEST_KEYFILES.zip](https://github.com/BlueFinBima/Helios/files/4546109/TEST_KEYFILES.zip)

### please make sure to close upstream issue when this item is closed

**Comment by derammo** [comment]
this should be a preflight check in the Falcon interface

**Comment by derammo** [comment]
I have already provided skeleton code indicating where it should go

**Comment by Todd1215** [comment]
Apparently I really missed the ball on this one. I just saw this issue now.

So the key file gets loaded once when the profile loads. So if you got a list or a failed pre-flight check in control center to log all the callbacks that are not mapped would that be to a seperate file of just dumped into the control center log file?
