### ISSUE TITLE
ADI cage Adjustment not working

### ISSUE THREAD

**Issue by derammo** [HeliosVirtualCockpit/Helios#23]
* created by @BlueFinBima on 2018-05-29 11:16:11 +0000 UTC
* assignees: BlueFinBima

(AV-8B) Need to add an axis for the ADI adjustment and then bind it correctly in the profile.

### comment by @BlueFinBima on 2018-05-29 15:14:21 +0000 UTC

elements["PTN_351"] =   default_button_lever(_("Backup ADI Cage/Pitch   Adjust Knob"),  devices.FLIGHTINSTRUMENTS,   inst_commands.ADI_Cage, inst_commands.Knob_ADI, 350, 351)

### please make sure to close upstream issue when this item is closed

**Comment by BlueFinBima** [comment]
Tested at 1.6.611 and DCS 2.9.8.1214, and the Harrier ADI syncs between DCS and Helios profile.
