### ISSUE TITLE
Font sizes not adjusted by reset monitors

### ISSUE THREAD

**Issue by derammo** [HeliosVirtualCockpit/Helios#230]
* created by @derammo on 2020-05-30 12:25:20 +0000 UTC
* assignees: derammo

After reset monitors, the sizes of pushbuttons with labels are adjusted, but the font size is not.  The sizes of TextDisplay controls are adjusted, but poorly (see new TextDisplay scaling mode in 1.6.) 

It would be much better to let the controls know explicitly that they are being resized by reset monitors instead of user interaction, so they can do the right thing.   Even things that don't normally auto-scale when adjusted by a human should probably scale when reset monitors is run.  Only the individual control would know what makes sense.  

We should have an optional interface for the "I need to know when the overall profile is resized" capability on controls.

### comment by @derammo on 2020-05-30 12:26:48 +0000 UTC

the impact of this problem is that buttons no longer display their labels at all as they become too large to be contained in the button

### please make sure to close upstream issue when this item is closed

**Comment by derammo** [comment]
There is the additional problem of composite controls not scaling their embedded text fields correctly.  Something is still very wrong with font sizing.  This will likely be fixed together, so here is an example test case:

- take F18 UFC
- shrink it down to a small size (25% or original or so) and observe font sizes

**Comment by derammo** [comment]
a clean slate would be to combine the following into a common class:

Indicator
PushButton
PushButtonIndicator
TextDecoration
TextDisplay (this is the only one that current auto-scales)

in order to support existing XML, we would write an XmlModel that reads all the different names and emits a standard set of values, meaning every profile would change on the first write after the code changes

the UI would be factored into a few functional groups to be shared across all these classes

**Comment by derammo** [comment]
this makes quarter screen demo mode not work

**Comment by linknetx** [comment]
So this is not entirely straightforward and probably on the back burner but what is the position on getting this resolved?

**Comment by derammo** [comment]
The only controls that don't already scale their text appear to be the PushButton and RotarySwitch.  These now do so by default (during Reset Monitors, not when you just stretch them by hand.)    Their original behavior can be restored by turning off "Scale All Text" in Tools | Options.

![image](https://user-images.githubusercontent.com/817160/126724074-008346c6-bece-499f-9897-9e48c518b223.png)

**Comment by derammo** [comment]
Note: PushButton is what Capt Zeen's profiles use for the green panel buttons that people kept losing during Reset Monitors.  This fixes that.
