### ISSUE TITLE
Some AV-8B switches etc have incorrect names

### ISSUE THREAD

**Issue by derammo** [HeliosVirtualCockpit/Helios#238]
* created by @BlueFinBima on 2020-07-04 11:39:33 +0000 UTC
* assignees: BlueFinBima

Spotted that an error was being displayed (an incorrect message in fact) for visual components containing colons and dash characters.  The error message for the field in Profile Editor relates to the name being blank.  There is policing of alphanumeric names, but maybe this is over zealous and can be relaxed somewhat.

### please make sure to close upstream issue when this item is closed

**Comment by BlueFinBima** [comment]
Fixed by 3db8ae593d88656ba0aff6ffe642c56947919bd8 in RC1630
