### ISSUE TITLE
Missing white-wheel-down image throws exception in the log

### ISSUE THREAD

**Issue by Todd1215** [HeliosVirtualCockpit/Helios#270]
Exception is throw in Control Center log

```2020-06-26 22:01:26.1620|ERROR|GadrocsWorkshop.Helios.ImageManager|Error loading image from pack reference to assembly pack://application:,,,/Helios;component/Images/wheel-white-down.png.|System.IO.IOException
Cannot locate resource 'images/wheel-white-down.png'.
   at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
   at System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)
   at System.Windows.Application.GetResourceStream(Uri uriResource)
   at GadrocsWorkshop.Helios.ImageManager.CanOpenPackUri(Uri uri)
```

I've checked that the image does exist in src code. So possibly its not getting added as a resource at compile time?

**Comment by derammo** [comment]
What is the impact?  Does this prevent use of a particular control or what is it?  If it breaks some control then I would say it is "blocking" and needs to go into the current release.

This is a good opportunity to practice the release process :).   Three choices:

1) attach this to the Release1630 milestone:

This means it invalidates the current release candidate.  We fix it in the rc1630 branch and merge to master when the release is done.   We spin a new release candidate build.

2) attach this to the Release1631 milestone:

This means we commit to fix it in the next release.

3) attach this to the ShortTerm or LongTerm milestone:

Doesn't make much sense for bugs, but basically means it is not committed and just a candidate for inclusion in some release later.

**Comment by Todd1215** [comment]
For this issue I don't see it as being a blocker of any sort. After further review the exception message is thrown but the control is not missing the image. So possibly there is some incorrect reference that has no bearing on the control itself. Since its not a show stopper but can lead others astray in troubleshooting it probably needs to get sorted out before release as the 1.4 code does not throw this exception.

**Comment by derammo** [comment]
agreed.   This seems like the significant changes I made to image loading are just broken in some way.  It likely would happen to other controls also.  Will fix.

**Comment by derammo** [comment]
the path is wrong, it should be {Helios}/Images/Rockers/wheel-white-down.png

that said, throwing and logging an exception in this case is still a bug.   It was supposed to just return false (the code expected to get a null from the call and not an exception.)  this will be corrected

**Comment by derammo** [comment]
more clarification: 1.4 did not log these types of exceptions I think.  The image loading code is quite different.  That's where I broke it.

**Comment by Todd1215** [comment]
Just tested again with latest draft build 1.6.3045.0001. The issue is no longer present.
