### ISSUE TITLE
Custom Gauge hit test is performed on rectangular bounding box of all drawn objects instead of control base rectangle

### ISSUE THREAD

**Issue by ertiyu** [HeliosVirtualCockpit/Helios#276]
A video rather than words  ;)

https://youtu.be/qHj-vXnlngo

[Bug gauge.zip](https://github.com/HeliosVirtualCockpit/Helios/files/4898455/Bug.gauge.zip)

**Comment by ertiyu** [comment]
To get around the problem, just place the gauge under the elements.

**Comment by BlueFinBima** [comment]
To paraphrase the video so to speak,  the "hit / no-hit" area is based on a rectangle parallel to the x-axis determined by the highest and lowest points of a component (and the left/right-most points) with the result that when a rectangular control is rotated, the hit / no-hit area grows and shrinks and will potentially occlude lower controls, causing them to appear not to function.
Circumvention is to place rotating complex shapes lower than controls they might mask with the growing and shrinking of the rectangle.
The current implementation of hit/no-hit is rudimentary.

Question:  Excluding the video, are there valid cases where a rotating element would not be approximately circular?

**Comment by ertiyu** [comment]
Yes l'ADI

**Comment by derammo** [comment]
I misinterpreted the issue at first.  The rotated needle doesn't define where the control is for hit testing.  So now it will just hit test against the background rectangle (the control's base extent).

**Comment by derammo** [comment]
verified by ertiyu
