### ISSUE TITLE
Helios prevents image files from being updated externally

### ISSUE THREAD

**Issue by Todd1215** [HeliosVirtualCockpit/Helios#277]
Both the Control Center and the Profile Editor lock image files when the Profile has been loaded. I see no reason why Helios should be doing this. If users use other programs to create images to load into a kneeboard or something before flight time have to wait to start the Helios Profile after the images have been created/updated. Fixing this would allow for some level of dynamic updates to image files from external programs.

**Comment by derammo** [comment]
@Todd1215 please test in master.  should be resolved

**Comment by Todd1215** [comment]
yeah that fixed it. Helios no longer locks files.

**Comment by Todd1215** [comment]
Fixed
