### ISSUE TITLE
IAS Gauge on KA50 incorrect values

### ISSUE THREAD

**Issue by CaptZeen** [HeliosVirtualCockpit/Helios#284]
Morning, i discover a bug in Helios/Gauges/KA-50/IAS/IAS.cs
in the line 34:
 _needleCalibration = new CalibrationPointCollectionDouble(20d, 5d, 35d, 345d);

this is incorrect need to be:
 _needleCalibration = new CalibrationPointCollectionDouble(20d, 5d, 350d, 345d);

Thats cause the IAS gauge of the ka50 work wrong between 20 and 50km/h

**Comment by derammo** [comment]
good fix.  tested.
