### ISSUE TITLE
Windows scaling tactile control issue

### ISSUE THREAD

**Issue by Todd1215** [HeliosVirtualCockpit/Helios#287]
Take a fresh profile such as CaptZeen's A-10C profile and upon resetting the monitors causes the text on the tactile control to disappear. This seems to occur when Windows scaling is in effect.

TEXT is displayed on refresh profile
![image1](https://user-images.githubusercontent.com/6605805/88693669-9121b580-d0cd-11ea-8167-a58f183eb93c.png)

Type of control being affected
![image2](https://user-images.githubusercontent.com/6605805/88693686-941ca600-d0cd-11ea-8f8f-c49b32c28a78.png)

Resetting of the monitors
![image3](https://user-images.githubusercontent.com/6605805/88693691-95e66980-d0cd-11ea-9cc8-a78e05a9c783.png)

Result of reset is TEXT on tactile controls are gone!
![image4](https://user-images.githubusercontent.com/6605805/88693699-97b02d00-d0cd-11ea-96c1-993cd5bd75b9.png)

I know we addressed this same issue with labels but I would say that possibly it affects more controls that can have text.

**Comment by derammo** [comment]
more info:  wheelchock has observed this resetting from 1920x1080 to 1920x1080 with 150% scaling

I do not see any problem with resetting to 2560x1440 at 100%

**Comment by derammo** [comment]
if it doesn't happen with 1920x1080 at 100%, then I would suggest we defer this bug and continue to ship

**Comment by derammo** [comment]
testing to be done with the 1.6 profile here, btw
https://mega.nz/file/U8cCjaRZ#6x4bIpva42tJz9eYFUHrzdAYP8YG8189UZd0_T3puAs

**Comment by Todd1215** [comment]
yup I was suppose to add my screen details, apologies. Main screen is 3840x2160 second screen is 1920x1080 both are scaled to 150% using Windows scaling. 

Additional testing for a work around using Compatibility DPI scaling was performed and failed miserably.

**Comment by derammo** [comment]
ertiyu sent me some videos of scaling and losing the text.  The common denominator appears to be scaling to smaller effective sizes it clobbers the text.   That makes sense to me that this would happen.  It isn't super urgent, because most people probably scale to larger displays not smaller ones?   Except for the DPI issues forcing us to set the same DPI on both displays... hmm.. I would say medium priority short term?

**Comment by derammo** [comment]
I believe that this is resolved by #230 

Can you please confirm if this is the same thing, i.e. fixed now in the master?

**Comment by Todd1215** [comment]
Tested and confirmed. This is fixed.
