### ISSUE TITLE
compatibility with AVG anti virus

### ISSUE THREAD

**Issue by derammo** [HeliosVirtualCockpit/Helios#292]
build 3051

![image](https://user-images.githubusercontent.com/817160/88874478-29fb2280-d1ed-11ea-810d-ff9a826d0eeb.png)

get AVG running in a VM or a test machine
try to duplicate and investigate
helpful user has already submitted this probable false positive to AVG folks but has no contract (free user)

**Comment by derammo** [comment]
my gut reaction is that being an unsigned app that contains code to elevate privileges (in Helios.dll, thus code is present but unused in Control Center process) might trigger some behavior scanner?

**Comment by BlueFinBima** [comment]
I seem to recall that we had some virus scan problems with earlier versions.  I would like to think that if the priv elevation was the trigger, that it would pick something more specific than "Identity Detection Protection" as the threat.  Could this be detection of your code to anonymize diagnostics?

**Comment by derammo** [comment]
I installed paid AVG on a VM and cannot get it to trigger at all.  Everything is fine, including the ransomware protection (it asked me to allow Control Center.exe and Profile Editor.exe to write the Documents folder one time and then it shut up.)

**Comment by derammo** [comment]
ugh... elevated executable gets stopped by AVG for a scan, at which point it times out poorly (Helios was not expecting it to take 15 seconds to start communicating).   This needs work

**Comment by derammo** [comment]
some terminology from their logs

7/31/2020 7:50:47 AM	Autosandbox candidate: C:\Program Files\Helios Virtual Cockpit\Helios\HeliosPatching.exe
	[Source: ]
	[Opened by: C:\Program Files\Helios Virtual Cockpit\Helios\HeliosPatching.exe]
	[Reason: 0x00020000]
	 --> Result: Sandboxing (no custody)
	 --> Instrumentation: Instrumentation inside sandbox requested

7/31/2020 7:51:49 AM	Autosandbox candidate: C:\Program Files\Helios Virtual Cockpit\Helios\HeliosPatching.exe
	[Source: ]
	[Opened by: C:\Program Files\Helios Virtual Cockpit\Helios\HeliosPatching.exe]
	[Reason: 0x00020000]
	 --> Result: Not sandboxing (because the file is in the exception list).

**Comment by derammo** [comment]
now the elevated writing fails on the VM even with AVG temporarily disabled.  it needs better reporting as to what happened

**Comment by derammo** [comment]
note:  the elevated process scanner stores one result per path with a thumbprint.   so changing HeliosPatching.exe always triggers one scan the next time it is run

**Comment by derammo** [comment]
tried AVG both free and paid and get no failures.

when Helios starts (each process) gets one of these on the first use:

![image](https://user-images.githubusercontent.com/817160/89112017-2ce35680-d42b-11ea-96cf-588c2df66125.png)

and then it scans and is happy

**Comment by derammo** [comment]
on uninstalling 3104 from an AVG paid VM, I was able to get this same positive

![image](https://user-images.githubusercontent.com/817160/89137312-bf582880-d505-11ea-8ce8-8a16971b35a5.png)

oddly I have done this test many times.  it may be intermittent

**Comment by derammo** [comment]
AVG says the quarantine is empty.  This is so broken.

**Comment by derammo** [comment]
also there is something very odd going on during uninstall while Helios is running.  on the AVG VM Control Center and Profile Editor do not exit when the installer tries to stop them to uninstall.  They are still running after all the files have been deleted already.  I don't think that is possible in normal windows?

**Comment by derammo** [comment]
since this never happened again, I assume they updated their signatures and will close this
