### ISSUE TITLE
DCS World Steam Edition requires a workaround for Helios 1.6

### ISSUE THREAD

**Issue by derammo** [HeliosVirtualCockpit/Helios#295]
user Maverick_1971 reports their Steam OpenBeta install doesn't have autoupdate.cfg so it cannot be selected

https://discordapp.com/channels/434241908492075010/738069402905214997/738399294092214384

I am currently installing Steam OpenBeta version to test this.   Also check with Jabbers code to see if there is a known alternate way to do this.

**Comment by derammo** [comment]
installed latest openbeta from steam.  no autoupdate.cfg, no bin\dcs_updater.exe

apparently this is slapped down by regular Steam delivery and update mechanisms.  The current build number appears NOWHERE in the entire directory tree according to vscode search

at this point it looks as if Steam users have to manually configure their DCS location information, which means we need a UI

**Comment by derammo** [comment]
Note: this problem can be worked around by just placing an autoupdate.cfg with matching information in the DCS World installation folder in Steam.

**Comment by mnp555** [comment]
Howto? It's possible to have an example of autoupdate.cfg or some futrher info?
I have 
DCS World Steam Edition 2.5.6 
A-10C
Cucasus
Persian Gulf
Nevada 
Tacview

Thankyou

**Comment by derammo** [comment]
@mnp555 if your Saved Games are "Saved Games\DCS" _not_ "Saved Games\DCS.openbeta" then you can just place this file in the SteamLibrary\steamapps\common\DCSWorld folder


[autoupdate.zip](https://github.com/HeliosVirtualCockpit/Helios/files/5013025/autoupdate.zip)

you have to unzip it, because GitHub does not allow a .cfg file

**Comment by derammo** [comment]
this will be removed from the 1631 release and rescheduled.  It will be a known issue for 1631

**Comment by derammo** [comment]
according to c0ff, the file version stamp on dcs.exe will always be accurate.  Respins with 5 part version numbers will not include any different content in normal cases.  This approach would only fail in case of a Lua packaging issue, where a respin would actually include different Lua, which isn't a significant risk.
