### ISSUE TITLE
disallow install "just for me"

### ISSUE THREAD

**Issue by derammo** [HeliosVirtualCockpit/Helios#296]
only allow install for all users / machine wide

we don't test at all what happens when you install the product "just for me"

@BlueFinBima what do you think? is that ok?

**Comment by derammo** [comment]
needs testing: install as non-administrative user.  should fail gracefully

**Comment by derammo** [comment]
I will test this once I have my various testing VMs in place

**Comment by BlueFinBima** [comment]
What is the rationale for removing this?  Is it causing a problem?  If there isn't an obvious problem, and it is just that we so not test, then we could leave it in until someone tells us that it does not work.

**Comment by derammo** [comment]
I want to not have to deal with some weird bug that happened in the field because someone installed it locally to their user account and we don't know that fact.   If we keep it in, then I'd have to test it and see what it does and report in the status info whether the product is installed local to the user or not.

I thought it would be easier to just require that people be admins of their computer and install it to the machine.   

So the rationale was "we probably don't need it and it might waste a bunch of my time in the future."

**Comment by derammo** [comment]
I should have said this first:   this is only a checkbox in the installer project and doesn't represent any significant effort to put it back the old way if it is a problem for anyone.  This isn't installer development.  So I will happily put it back if someone complains.   Until then, I would like to have the installer as simple as possible.

**Comment by derammo** [comment]
at least one user ran the product in the "just me" mode.   I will just wait and see if it becomes a problem.  I can't get rid of an entire installer step anyway.
