### ISSUE TITLE
Loading image into user image control sizes control to scaled image size, not pixel size

### ISSUE THREAD

**Issue by ertiyu** [HeliosVirtualCockpit/Helios#308]
Hello,
I have just noticed a strange behavior of the image control.
Whatever the format entered it always comes back to 66 * 66.
Here is a video showing the behavior.

https://youtu.be/aZyGZe-lUcI

**Comment by Todd1215** [comment]
So its re-sizing the image control based on the initial image size, but can be changed after the image is loaded.

**Comment by Todd1215** [comment]
Additional info from the OP

The problem is rather when you do copy / paste, it resizes the image if you change the image source

**Comment by ertiyu** [comment]
I just did a test again,
the defined value is not fixed, for example on a rectangle it is more 66 * 66 it is a ratio.
For 50 * 50 the ratio is 1.32, on the other hand for 110 * 60 it is 1.3273 and 1.334.
I made a video.
https://youtu.be/l5vnUcRlpSo

**Comment by derammo** [comment]
I don't see anything wrong here?   Will reach out on Discord

**Comment by derammo** [comment]
Helios is reading the DPI meta information from bitmaps it loads and scaling them to the screen DPI on load.  So the image will auto size to the scaled image size, not the pixel size.

We need to discuss what the impact would be of changing this behavior or supporting an option

**Comment by ertiyu** [comment]
is no longer relevant.
