### ISSUE TITLE
Add a share to Android app (bms) / webpage

### ISSUE THREAD

**Issue by GamerKing122** [HeliosVirtualCockpit/Helios#312]
Needs an ability to use your Android / ios device as a screen using mirror/chromecast

**Comment by derammo** [comment]
Thanks for your suggestion.  This is an extremely expensive feature we would love to do some day.

**Comment by BlueFinBima** [comment]
@GamerKing122 I've not tried this, nor do I have any connection with the app or the company who creates it, but a user reported that they successfully used Twomon (as described here https://www.youtube.com/watch?v=ggZT6-BHci8) with Helios.  I cannot vouch for this, but it is something you might like to investigate yourself.
