### ISSUE TITLE
Helios A10C v3 profile issue

### ISSUE THREAD

**Issue by DZ82** [HeliosVirtualCockpit/Helios#313]
When opening a10C v3 Helios profile, Unhandled error in patching message appears

![Picture2](https://user-images.githubusercontent.com/69603838/90063566-da871d00-dce9-11ea-97fd-cdbb92dcebec.png)

**Comment by derammo** [comment]
thank you.  That's gonna be a real bug.  Can you provide the ```autoupdate.cfg``` file found in your DCS installation folder, please?  Clearly I failed to parse the version number correctly.

**Comment by derammo** [comment]
also, is this a Steam install?

I show both OpenBeta and Release DCS are currently at 2.5.6.52437, which we definitely parse correctly.  So I would need to the see the file you have.

**Comment by DZ82** [comment]
Had to create one, as I use Steam version of DCS.

Possibly the issue?

[autoupdate.zip](https://github.com/HeliosVirtualCockpit/Helios/files/5065481/autoupdate.zip)

**Comment by derammo** [comment]
yes it does not have a version in it. 

Please use the one I attached to the defect here #295

https://github.com/HeliosVirtualCockpit/Helios/files/5013025/autoupdate.zip

**Comment by DZ82** [comment]
Solved, thank you
