### ISSUE TITLE
crashing 

### ISSUE THREAD

**Issue by cosmo238977** [HeliosVirtualCockpit/Helios#315]
[Helios has written the report to the file 'Helios_status_report_132420478467601675.txt'
[Helios_status_report_132420478467601675.txt](https://github.com/HeliosVirtualCockpit/Helios/files/5080517/Helios_status_report_132420478467601675.txt)
 and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

**Comment by derammo** [comment]
Duplicate #316 
apparently created by mistake (log has no problems in it)
