### ISSUE TITLE
FA18CInterface: AOA Flags changed to dimmable values

### ISSUE THREAD

**Issue by derammo** [HeliosVirtualCockpit/Helios#319]
```
            AddFunction(new FlagValue(this, "4", "Caution Indicators", "AOA_HIGH", ""));        // create_caution_lamp(4,CautionLights.CPT_LTS_AOA_HIGH)
            AddFunction(new FlagValue(this, "5", "Caution Indicators", "AOA_CENTER", ""));      // create_caution_lamp(5,CautionLights.CPT_LTS_AOA_CENTER)
            AddFunction(new FlagValue(this, "6", "Caution Indicators", "AOA_LOW", ""));         // create_caution_lamp(6,CautionLights.CPT_LTS_AOA_LOW)
```
according to this post https://forums.eagle.ru/showpost.php?p=4456100&postcount=37
these have now been changed internally to be dimmable lamps (float values)

to maintain maximum compatibility, we could threshold them to a flag on the export side and also send the lamp intensities as separate 2xxxx codes?

however, since 1.6 enforces the driver being up to date, we can just change the type of the export to a float and then create a function object that provides two registered values (the original flag under the original name and another intensity value)

**Comment by BlueFinBima** [comment]
Off remains 0d from what I can see.  Design will be to add to the FlagValue a brightness value which it can pass on to a suitably capable Indicator.

**Comment by BlueFinBima** [comment]
Commit 376af6e3 is a fix which should cope with dimming and toggling.  No control yet which can consume the brightness yet.

**Comment by derammo** [comment]
marked as fixed as having a control to display dimmed AOA is out of scope for this issue (the bug that we don't correctly support those args in DCS since DCS has changed)

**Comment by derammo** [comment]
sorry I had a misunderstanding.   We aren't exposed to this bug that was originally reported.  The Capt Zeen module had integer exports (%d) for flags, and therefore would stop working correctly with the flag values now being floats for these.   Our driver actually always sent flags as float so never failed to begin with.    So there is no bug here and it doesn't matter when we improve this.  Correct?

**Comment by BlueFinBima** [comment]
Correct
