### ISSUE TITLE
problem with missing images and profileinterface

### ISSUE THREAD

**Issue by scottgold1169** [HeliosVirtualCockpit/Helios#333]
i loaded new helios 1.6 and n{
  "Product": "Helios",
  "Version": "1.6.3214.0",
  "Items": [
    {
      "Name": "Profile Interface",
      "Report": [
        {
          "TimeStamp": "08/28/2020 10:59:29.227 AM",
          "Status": "Profile is '%USERPROFILE%\\Documents\\Helios\\Profiles\\A10C_v3.0b.hpf'",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:29.228 AM",
          "Status": "The monitor arrangement saved in this profile matches this computer",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:29.228 AM",
          "Status": "The profile declares a monitor of size 2560x1440 at (0, 0)",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:29.228 AM",
          "Status": "The profile declares a monitor of size 1920x1080 at (2560, 351)",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:29.228 AM",
          "Severity": 1,
          "Status": "An image used in this Profile's controls could not be loaded from 'Capt_Zeen\\A10C\\ADI_slep_BG.png'",
          "Flags": 3,
          "Recommendation": "Install missing images or correct image paths in controls, then reload profile."
        },
        {
          "TimeStamp": "08/28/2020 10:59:29.228 AM",
          "Severity": 1,
          "Status": "An image used in this Profile's controls could not be loaded from 'Capt_Zeen\\A10C\\white_ball.png'",
          "Flags": 3,
          "Recommendation": "Install missing images or correct image paths in controls, then reload profile."
        },
        {
          "TimeStamp": "08/28/2020 10:59:29.228 AM",
          "Severity": 1,
          "Status": "An image used in this Profile's controls could not be loaded from 'Capt_Zeen\\A10C\\needle_010.png'",
          "Flags": 3,
          "Recommendation": "Install missing images or correct image paths in controls, then reload profile."
        },
        {
          "TimeStamp": "08/28/2020 10:59:29.228 AM",
          "Severity": 1,
          "Status": "An image used in this Profile's controls could not be loaded from 'Capt_Zeen\\A10C\\sw_009_UP.png'",
          "Flags": 3,
          "Recommendation": "Install missing images or correct image paths in controls, then reload profile."
        },
        {
          "TimeStamp": "08/28/2020 10:59:29.228 AM",
          "Severity": 1,
          "Status": "An image used in this Profile's controls could not be loaded from 'Capt_Zeen\\A10C\\sw_009_MID.png'",
          "Flags": 3,
          "Recommendation": "Install missing images or correct image paths in controls, then reload profile."
        },
        {
          "TimeStamp": "08/28/2020 10:59:29.228 AM",
          "Severity": 1,
          "Status": "An image used in this Profile's controls could not be loaded from 'Capt_Zeen\\A10C\\sw_009_DOWN.png'",
          "Flags": 3,
          "Recommendation": "Install missing images or correct image paths in controls, then reload profile."
        }
      ]
    },
    {
      "Name": "Keyboard",
      "Report": []
    },
    {
      "Name": "DCS A10C",
      "Report": [
        {
          "TimeStamp": "08/28/2020 10:59:28.454 AM",
          "Status": "DCS version 2.5.6.54046 installed at 'C:\\Program Files\\Eagle Dynamics\\DCS World' with Saved Games at '%USERPROFILE%\\Saved Games\\DCS'",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.455 AM",
          "Status": "Export scripts location for DCS exists",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.463 AM",
          "Status": "Export.lua stub for DCS calls HeliosExport16.lua",
          "Flags": 2
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.464 AM",
          "Status": "The configured DCS export script at '%USERPROFILE%\\Saved Games\\DCS\\Scripts\\Helios\\HeliosExport16.lua' is up to date",
          "Flags": 2
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.469 AM",
          "Status": "The export module provided by Capt Zeen (Version 1) at '%USERPROFILE%\\Saved Games\\DCS\\Scripts\\Helios\\Mods\\Helios_A10C.lua' is up to date",
          "Flags": 2
        }
      ]
    },
    {
      "Name": "Throttle - HOTAS Warthog",
      "Report": []
    },
    {
      "Name": "DCS Monitor Setup",
      "Report": [
        {
          "TimeStamp": "08/28/2020 10:59:28.477 AM",
          "Status": "Windows reports a scaling value of 100% (96 dpi)",
          "Flags": 3,
          "Recommendation": "This version of Helios does not support using different display scaling (DPI) on different monitors.  Make sure you use the same scaling value for all displays."
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.478 AM",
          "Status": "viewport 'A_10C_LEFT_MFCD' is provided by 'DCS Additional Viewports'",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.478 AM",
          "Status": "viewport 'A_10C_RIGHT_MFCD' is provided by 'DCS Additional Viewports'",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.478 AM",
          "Status": "viewport 'A_10C_RWR_SCREEN' is provided by 'DCS Additional Viewports'",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.478 AM",
          "Status": "viewport 'A_10C_DIGIT_CLOCK' is provided by 'DCS Additional Viewports'",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.478 AM",
          "Status": "viewport 'A_10C_UHF_REPEATER' is provided by 'DCS Additional Viewports'",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.478 AM",
          "Status": "viewport 'A_10C_CMSC_SCREEN' is provided by 'DCS Additional Viewports'",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.478 AM",
          "Status": "viewport 'A_10C_CMSP_SCREEN' is provided by 'DCS Additional Viewports'",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.478 AM",
          "Status": "viewport 'A_10C_CDU_SCREEN' is provided by 'DCS Additional Viewports'",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.478 AM",
          "Status": "viewport 'A_10C_UHF_PRESET_CHANNEL' is provided by 'DCS Additional Viewports'",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.478 AM",
          "Status": "viewport 'A_10C_UHF_FREQUENCY_STATUS' is provided by 'DCS Additional Viewports'",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.520 AM",
          "Status": "Helios: A_10C_CDU_SCREEN = { x = 3785, y = 1002, width = 222, height = 163 }",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.521 AM",
          "Status": "Helios: A_10C_CMSC_SCREEN = { x = 3424, y = 476, width = 235, height = 45 }",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.521 AM",
          "Status": "Helios: A_10C_CMSP_SCREEN = { x = 3755, y = 367, width = 207, height = 55 }",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.521 AM",
          "Status": "Helios: A_10C_DIGIT_CLOCK = { x = 3038, y = 1177, width = 123, height = 123 }",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.521 AM",
          "Status": "Helios: A_10C_LEFT_MFCD = { x = 2619, y = 491, width = 435, height = 435 }",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.521 AM",
          "Status": "Helios: A_10C_RIGHT_MFCD = { x = 3983, y = 492, width = 435, height = 435 }",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.521 AM",
          "Status": "Helios: A_10C_RWR_SCREEN = { x = 3150, y = 512, width = 185, height = 185 }",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.521 AM",
          "Status": "Helios: A_10C_UHF_FREQUENCY_STATUS = { x = 3107, y = 789, width = 112, height = 28 }",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.521 AM",
          "Status": "Helios: A_10C_UHF_PRESET_CHANNEL = { x = 3197, y = 718, width = 34, height = 27 }",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.521 AM",
          "Status": "Helios: A_10C_UHF_REPEATER = { x = 3223, y = 1049, width = 95, height = 25 }",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.521 AM",
          "Status": "Helios: FA_18C_CENTER_MFCD = { x = 3337, y = 1047, width = 363, height = 344 }",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.521 AM",
          "Status": "Helios: FA_18C_IFEI = { x = 2713, y = 1104, width = 526, height = 205 }",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.521 AM",
          "Status": "Helios: FA_18C_LEFT_MFCD = { x = 2839, y = 551, width = 391, height = 369 }",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.521 AM",
          "Status": "Helios: FA_18C_RIGHT_MFCD = { x = 3818, y = 551, width = 389, height = 367 }",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.521 AM",
          "Status": "Helios: FA_18C_RWR = { x = 4052, y = 1071, width = 182, height = 182 }",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.521 AM",
          "Status": "Helios: FA_18C_UFC = { x = 3300, y = 382, width = 457, height = 259 }",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.521 AM",
          "Status": "Monitor at Windows coordinates (0,0) of size 2560x1440 is used for main view",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.521 AM",
          "Status": "Monitor at Windows coordinates (0,0) of size 2560x1440 is used to display the DCS user interface",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.521 AM",
          "Status": "Monitor at Windows coordinates (2560,351) of size 1920x1080 has 10 viewports from this profile",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.521 AM",
          "Status": "MAIN = { x = 0, y = 0, width = 2560, height = 1440 }",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.522 AM",
          "Status": "UI = MAIN",
          "Flags": 3
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.525 AM",
          "Status": "monitor setup file 'Helios.lua' in Saved Games\\DCS\\Config\\MonitorSetup is up to date",
          "Flags": 2
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.636 AM",
          "Status": "Saved Games\\DCS\\Config\\options.lua has 'Resolution' set to 4480x1440",
          "Flags": 2
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.637 AM",
          "Status": "Saved Games\\DCS\\Config\\options.lua has 'Monitors' set to 'helios'",
          "Flags": 2
        }
      ]
    },
    {
      "Name": "DCS Additional Viewports",
      "Report": [
        {
          "TimeStamp": "08/28/2020 10:59:28.952 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\AN_ALR69V\\indicator\\AN_ALR69V_init.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.956 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\CDU\\indicator\\CDU_init.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.959 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\CMSC\\indicator\\CMSC_init.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.962 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\CMSP\\indicator\\CMSP_init.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.963 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\DigitalClock\\Indicator\\DIGIT_CLK_init.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.964 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\MFCD\\indicator\\MFCD_left_init.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.966 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\MFCD\\indicator\\MFCD_right_init.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.967 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\UHF_Radio\\indicator\\freq_status_init.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.970 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\UHF_Radio\\indicator\\preset_channel_init.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.970 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\UHF_Radio\\indicator\\repeater_init.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.971 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\DED\\indicator\\DED_init.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.972 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\EHSI\\indicator\\EHSI_init.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.980 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\EHSI\\indicator\\LCD\\EHSI_LCD.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.984 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\MFD\\indicator\\MFD_left_init.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.987 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\MFD\\indicator\\MFD_right_init.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.988 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\MFD\\indicator\\LCD\\MFD_LCD.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.991 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\EWS\\RWR\\indicator\\RWR_ALR56_init.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.995 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\fonts.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:28.999 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\IFEI\\indicator\\IFEI_init.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:29.002 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\Multipurpose_Display_Group\\AMPCD\\indicator\\AMPCD_viewport_cfg.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:29.005 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\Multipurpose_Display_Group\\AMPCD\\indicator\\BAKE\\AMPCD_bake_init.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:29.005 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\Multipurpose_Display_Group\\Common\\indicator\\BAKE\\MPD_common_bake_init.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:29.005 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\Multipurpose_Display_Group\\MDI_IP1556A\\indicator\\MDI_left_viewport_cfg.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:29.006 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\Multipurpose_Display_Group\\MDI_IP1556A\\indicator\\MDI_right_viewport_cfg.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:29.010 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\TEWS\\indicator\\RWR_ALR67_init.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:29.012 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\UFC\\indicator\\UFC_init.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:29.015 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\Ka-50\\Cockpit\\Scripts\\ABRIS\\BAKE\\init.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:29.019 AM",
          "Status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' has already patched Mods\\aircraft\\Ka-50\\Cockpit\\Scripts\\SHKVAL\\BAKE\\init.lua",
          "Flags": 1
        },
        {
          "TimeStamp": "08/28/2020 10:59:29.019 AM",
          "Status": "Helios is managing DCS patches for viewports and drawing settings",
          "Flags": 3,
          "Recommendation": "Do not also install viewport mods manually or via a mod manager like OVGME"
        }
      ]
    },
    {
      "Name": "EOS Bus",
      "Report": []
    },
    {
      "Name": "Process Control",
      "Report": []
    }
  ]
}ow ii have all kinds of errors inprofile interface and some images are missing just a red box.

**Comment by derammo** [comment]
pilot error as discussed on Discord
