### ISSUE TITLE
Falcon BMS interface bug

### ISSUE THREAD

**Issue by ertiyu** [HeliosVirtualCockpit/Helios#345]
By installing Helios on a workstation that does not have Falcon BMS, it is impossible to change the path of the key file by clicking on the gray button with the 3 small dots, an exception is raised.
this is version 1.6.3302
I'll watch at home tonight if I have the same on my main post.
[Profile Editor Problems.log](https://github.com/HeliosVirtualCockpit/Helios/files/5207252/Profile.Editor.Problems.log)

**Comment by Todd1215** [comment]
I doubt the initial author thought that someone would try to use Helios and Falcon without Falcon being on the same PC. I think that was always a requirement. With that said I was able to duplicate the issue. What is your use case? Are you just trying to do profile development while away from your beloved Falcon PC?   😛 

With that said we still need to deal with the exception and the fact that Falcon may not be present sometimes.
