### ISSUE TITLE
dcs 

### ISSUE THREAD

**Issue by luca2285** [HeliosVirtualCockpit/Helios#353]
[Helios has written the report to the file 'Helios_status_report_132458687998434336.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

**Comment by BlueFinBima** [comment]
@luca2285 can you please please drag and drop file 'Helios_status_report_132458687998434336.txt' from Explorer to this issue and provide a description of the problem you are reporting.

**Comment by derammo** [comment]
invalid
