### ISSUE TITLE
M2000C_VTB viewport patch does not preserve RIGHT_MFCD generic viewport name

### ISSUE THREAD

**Issue by derammo** [HeliosVirtualCockpit/Helios#361]
diff --git a/Mods/aircraft/M-2000C/Cockpit/VTB/VTB_init.lua b/Mods/aircraft/M-2000C/Cockpit/VTB/VTB_init.lua
index 9fe5a9d..4405588 100644
--- a/Mods/aircraft/M-2000C/Cockpit/VTB/VTB_init.lua
+++ b/Mods/aircraft/M-2000C/Cockpit/VTB/VTB_init.lua
@@ -38,7 +38,7 @@ init_pageID                   = VTB_PAGE_0

 used_render_mask = "interleave2.bmp" --default mask for TV
 update_screenspace_diplacement(SelfWidth/SelfHeight,false)
-try_find_assigned_viewport("RIGHT_MFCD")
+try_find_assigned_viewport("M2000C_VTB", "M2000C_VTB")

**Comment by flyguychrisw** [comment]
allof this needs to be simplified for happier user this only ads to the frustration of new users to dcs

**Comment by BlueFinBima** [comment]
Viewport RIGHT_MFCD now retained in 1.6.5308.1 release 
`try_find_assigned_viewport("M2000C_VTB","RIGHT_MFCD")`
