### ISSUE TITLE
Adding a border to a rectangle fill corrupts the profile

### ISSUE THREAD

**Issue by Solomute** [HeliosVirtualCockpit/Helios#364]
Procedure to reproduce:

0) Don't do this on a profile you care about
1) Make a rectangle fill
2) Set its border thickness to anything other than "0"
3) Save the profile
4) Try to open it in Control Center
5) For added fun, try clicking save again in Profile Editor
6) For extra additional added fun, try opening the profile in Profile editor.
6a) (Optional) Press F to pay respects for the profile you were working on and didn't have a backup of :(

**Comment by derammo** [comment]
Could you attach the corrupted profile please?  It does not reproduce.   "Rectangle Fill" isn't a Helios control, so I assumed you meant the "Rectangle" panel decoration.  It worked fine for me.

**Comment by derammo** [comment]
also confirm the version of Helios you are running

**Comment by derammo** [comment]
ok yeah that's broken.  to work around, just open your HPF file in a text editor.  Find the section that I have shown in this screenshot. 

Delete the portion I marked in red.  Now you can load it again at least.

![image](https://user-images.githubusercontent.com/817160/95993425-19764380-0dfd-11eb-9e90-d752b0e9a058.png)

**Comment by Solomute** [comment]
Whoops, I was afraid there would be confusion between the Rectangle (which is fine) and the Rectangle Fill (which is not), I could have been more clear. Sounds like you figured it out though. Happy bug hunting!

**Comment by derammo** [comment]
just to be extra clear: the workaround I posted should restore access to your profile that you thought was destroyed
