### ISSUE TITLE
Network setup instructions can not be found

### ISSUE THREAD

**Issue by DH14300** [HeliosVirtualCockpit/Helios#366]
After scouring the web, I am unable to find directions for configuring Helios over a network. In order to preserve FPS, I would like to run Control Center on a remote PC (other than DCS).
Thank you.

**Comment by derammo** [comment]
correct, I don't think anyone has written those. Realistically, this item is just going to sit here unless someone volunteers.

**Comment by BlueFinBima** [comment]
Hi Dan,  have you reviewed https://www.youtube.com/watch?v=78to_NENQT8 ?

**Comment by BlueFinBima** [comment]
Not going to happen anytime soon, but happy to do it as I move over to 1.6.

**Comment by DH14300** [comment]
Hello,

I just reviewd the video you sent a link to which shows Helios Control Center can be run on a 2nd computer. The video does not, however, go into settings to get Helios to recieve data from the 1st computer. Is it automatic? Does the export.lua (or another file) on PC 1 need to be edited to send data to 2nd PC IP address? I will install Helios on the 2nd computer today with a known good profile (just gauges) and see what happens.

Thanks.

Dan

 
 

Sent: Saturday, October 24, 2020 at 5:45 AM

**Comment by DH14300** [comment]
OK! Thank you for the update.

Dan
 

Sent: Saturday, October 24, 2020 at 5:48 AM

**Comment by BlueFinBima** [comment]
https://github.com/HeliosVirtualCockpit/Helios/wiki/Running-Helios-Control-Center-Remotely

**Comment by BlueFinBima** [comment]
![image](https://user-images.githubusercontent.com/18526232/97086707-edd53380-161c-11eb-88d0-5fc0ef6d177a.png)

**Comment by BlueFinBima** [comment]
There is now a bit more information on the Wiki about network config https://github.com/HeliosVirtualCockpit/Helios/wiki/Running-Helios-Control-Center-Remotely

**Comment by DH14300** [comment]
This was successful thanks to your help:

1. Edit profile on PC1 'DCS Export Configuration' to reflect PC2 IP address.

2. In section below click 'Update DCS' (exports LUAs are updated) and save.

3. Copy profile to PC2.

4. Open Profile Editor on PC2 and open copied profile.

5. Reset Monitors (configure as desired) and save.

6. Run Control Center on PC2 with the profile and start DCS. This is working correctly. Gauges are working on PC2!

 

Dan

 
 

Sent: Saturday, October 24, 2020 at 10:18 AM

**Comment by BlueFinBima** [comment]
Wiki updated with additional information
