### ISSUE TITLE
Hornet UFC Doesn't display "ERROR"

### ISSUE THREAD

**Issue by BlueFinBima** [HeliosVirtualCockpit/Helios#369]
DCS uses the string "pww0w" to write an approximation of the word "ERROR" into the seven segment displays in the Hornet's UFC scratchpad area.  I suspect that this has been the case for a long time and nobody bothered to report it.  
This is how it should appear.
![Screen_201107_083707](https://user-images.githubusercontent.com/18526232/98436709-82d43400-20d5-11eb-9120-80699d4e4ac8.png)
Hopefully this can be fixed in the translation string without a need for the font to be changed.

**Comment by BlueFinBima** [comment]
New downward arrow in comm channel display is not implemented.  Double dot underscore is displayed in the UFC scratchpad area instead of a blank.
All these addressed by https://github.com/HeliosVirtualCockpit/Helios/commit/87b7c265c27a22a3254b2d04da9ef01c280c87b4

**Comment by derammo** [comment]
@BlueFinBima did you simply correct the font so that an ascii "E" is an "E" etc?   Just want to understand since I can't see TTF diffs

**Comment by BlueFinBima** [comment]
@derammo No, just accepted DCS's spelling
![image](https://user-images.githubusercontent.com/18526232/98444893-58ea3400-210c-11eb-9764-ef7fd0741e96.png)

**Comment by derammo** [comment]
why is this happening you think?

**Comment by BlueFinBima** [comment]
I believe that  it is intentional, but I can't see the logic.  I don't believe lower case "e" or "r" are being used for anything else which would seem to be more obvious candidates.  Maybe something to do with the way they mapped the font.  I've just had a look and although I don't remember seeing this font before it does not really reduce the mystery because the characters needed are not in the positions for "p" and "w".  Looks like I need to at least add an up triangle and logic would suggest that it should be "e" so maybe that pushed them in a particular direction.
![image](https://user-images.githubusercontent.com/18526232/98445502-f98e2300-210f-11eb-9172-4ad26a9505b7.png)

**Comment by derammo** [comment]
I see..  so the letters we get are raw what they use to index their "pseudo
font" on the DCS side?   From that perspective, I guess it makes sense what
we have now.  As long as nobody wants to actually do something with that
text.

I am mainly interested because I do read from the UFC in one of my play
projects, and the text shown in the Option Display units is actually
regular ascii characters.  Specifically, I read the string "POSN" from it
and it is exactly that.  Weird stuff.

**Comment by BlueFinBima** [comment]
Interesting stuff you play with :-)  The UFC is constructed from mostly 16 segment displays which can display reasonable characters so ASCII is fine for those even though they would struggle with lower case.  There are some special characters and numbers (eg >=10) which use these and have no good mapping to ASCII.   However there are seven 7 segment displays on the right of the scratchpad, and these can't really display ASCII reliably.  The "o" in "Error" is a zero which makes sense, and using lower case makes some sense if you're trying to keep everything in the same font (which DCS does not do) but how they came up with "p" & "w" is a mystery unless they are using the character codes as coordinates into a 2D font layout.
