### ISSUE TITLE
UDP Screen repeater would be a very nice to have.

### ISSUE THREAD

**Issue by derammo** [HeliosVirtualCockpit/Helios#37]
* created by @BlueFinBima on 2018-06-03 17:39:49 +0000 UTC
* assignees: damien022

The MFD's use a local screen mirroring, however it would probably be relatively easy to use the IRIS client code to have a networked version of these.

### comment by @BlueFinBima on 2018-09-26 21:18:30 +0000 UTC

Looks like there might be a coincidence with investigations relating to gstreamer. @damien022 looking into this for simpit, but it would be great if Helios could benefit as well.

### please make sure to close upstream issue when this item is closed

**Comment by BlueFinBima** [comment]
This item is stale and while it would be nice to have a multi-platform viewport client, there are options such as ffmpeg, and someone has created a python version to receive the Iris format data (see the Iris documentation).
