### ISSUE TITLE
F14 RIO Viewports on 3rd Screen

### ISSUE THREAD

**Issue by Wingnut11275** [HeliosVirtualCockpit/Helios#372]
Im currently running 5 screens and have a Pilot and RIO screen. However, there is no RIO Viewport, only a pilot.  Is there a way to have the all RIO viewport  setup for a 3rd Screen? 

Screen 1 is the Sim... Ok 
Screen 2 is the Pilot ... Ok  if I leave ECMD in the Pilot seat
Screen 3 is the TID OK, The ECMD  (No Viewport) and the DDD Viewport doesn't work

![image](https://user-images.githubusercontent.com/74383365/99159886-003c0d80-26af-11eb-91c8-ea1945da3db4.png)

![image](https://user-images.githubusercontent.com/74383365/99003402-06de4f80-250c-11eb-91a1-e34f3d51577c.png)

{
  "Product": "Helios",
  "Version": "1.6.3308.0",
  "Items": [
    {
      "Name": "Profile Interface",
      "Report": [
        {
          "TimeStamp": "11/12/2020 05:07:49.491 PM",
          "Status": "Profile is '%USERPROFILE%\\Documents\\Helios\\Profiles\\F-14_v2.0.hpf'",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:49.492 PM",
          "Status": "The monitor arrangement saved in this profile matches this computer",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:49.492 PM",
          "Status": "The profile declares a monitor of size 5760x1080 at (0, 0)",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:49.492 PM",
          "Status": "The profile declares a monitor of size 1680x1050 at (5760, 23)",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:49.492 PM",
          "Status": "The profile declares a monitor of size 1680x1050 at (7440, 26)",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:49.492 PM",
          "Status": "The profile declares a monitor of size 1680x1050 at (9120, 29)",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:49.492 PM",
          "Severity": 1,
          "Status": "Profile needs to be saved in order to be used by Helios Control Center",
          "Flags": 8,
          "Recommendation": "Save the profile before trying to use it in Helios Control Center"
        }
      ]
    },
    {
      "Name": "Keyboard",
      "Report": []
    },
    {
      "Name": "DCS Generic impersonating F-14B",
      "Report": [
        {
          "TimeStamp": "11/12/2020 05:07:17.763 PM",
          "Status": "DCS version 2.5.6.57264 installed at 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' with Saved Games at '%USERPROFILE%\\Saved Games\\DCS.openbeta'",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.765 PM",
          "Status": "Export scripts location for DCS.openbeta exists",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.771 PM",
          "Status": "Generated Export.lua stub is up to date for DCS.openbeta",
          "Flags": 2
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.779 PM",
          "Status": "The configured DCS export script at '%USERPROFILE%\\Saved Games\\DCS.openbeta\\Scripts\\Helios\\HeliosExport16.lua' is up to date",
          "Flags": 2
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.789 PM",
          "Status": "The export module provided by Capt Zeen (Version 1) at '%USERPROFILE%\\Saved Games\\DCS.openbeta\\Scripts\\Helios\\Mods\\Helios_F14.lua' is up to date",
          "Flags": 2
        }
      ]
    },
    {
      "Name": "DCS Monitor Setup",
      "Report": [
        {
          "TimeStamp": "11/12/2020 05:07:59.157 PM",
          "Status": "Windows reports a scaling value of 100% (96 dpi)",
          "Flags": 3,
          "Recommendation": "This version of Helios does not support using different display scaling (DPI) on different monitors.  Make sure you use the same scaling value for all displays."
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Status": "viewport 'F_14_RWR_PILOT' is provided by 'DCS Additional Viewports'",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Status": "viewport 'F_14_UHF_ARC159_M' is provided by 'DCS Additional Viewports'",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Status": "viewport 'F_14_UHF_ARC159_RP' is provided by 'DCS Additional Viewports'",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Status": "viewport 'F_14_VHF_ARC182_RP' is provided by 'DCS Additional Viewports'",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Status": "viewport 'F_14_RWR_RIO' is provided by 'DCS Additional Viewports'",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Status": "viewport 'F_14_UHF_ARC159_RR' is provided by 'DCS Additional Viewports'",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Severity": 1,
          "Status": "The viewport 'F14_ECMD' exists more than once in this profile.  Each viewport must have a unique name.",
          "Flags": 2,
          "Recommendation": "Rename one of the duplicated viewports with name 'F14_ECMD' in this profile"
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Severity": 2,
          "Status": "The viewport data for this profile is out of date",
          "Recommendation": "Configure DCS Monitor Setup"
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Status": "Helios: F_14_RWR_PILOT = { x = 7048, y = 410, width = 148, height = 148 }",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Status": "Helios: F_14_RWR_RIO = { x = 8660, y = 270, width = 142, height = 142 }",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Status": "Helios: F_14_UHF_ARC159_M = { x = 6153, y = 448, width = 119, height = 26 }",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Status": "Helios: F_14_UHF_ARC159_RP = { x = 7030, y = 259, width = 105, height = 26 }",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Status": "Helios: F_14_UHF_ARC159_RR = { x = 7888, y = 334, width = 108, height = 24 }",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Status": "Helios: F_14_VHF_ARC182_RP = { x = 7031, y = 331, width = 105, height = 26 }",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Status": "Helios: F14_DDD = { x = 8184, y = 108, width = 200, height = 200 }",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Status": "Helios: F14_ECMD = { x = 6449, y = 635, width = 316, height = 322 }",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Status": "Helios: F14_TID = { x = 8108, y = 427, width = 343, height = 330 }",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Status": "Helios: F14_VDI = { x = 6446, y = 259, width = 300, height = 300 }",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Status": "Monitor at Windows coordinates (0,0) of size 5760x1080 is used for main view",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Status": "Monitor at Windows coordinates (0,0) of size 5760x1080 is used to display the DCS user interface",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Status": "Monitor at Windows coordinates (5760,23) of size 1680x1050 has 6 viewports from this profile",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Status": "Monitor at Windows coordinates (7440,26) of size 1680x1050 has 5 viewports from this profile",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Status": "Monitor at Windows coordinates (9120,29) of size 1680x1050 is not included in monitor setup",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Status": "MAIN = { x = 0, y = 0, width = 5760, height = 1080 }",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.158 PM",
          "Status": "UI = MAIN",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.159 PM",
          "Severity": 1,
          "Status": "monitor setup file 'Helios.lua' in Saved Games\\DCS.openbeta\\Config\\MonitorSetup does not match configuration",
          "Recommendation": "Configure DCS Monitor Setup"
        },
        {
          "TimeStamp": "11/12/2020 05:07:59.160 PM",
          "Status": "Saved Games\\DCS.openbeta\\Config\\options.lua has 'Resolution' set to 10800x1080",
          "Flags": 2
        }
      ]
    },
    {
      "Name": "DCS Additional Viewports",
      "Report": [
        {
          "TimeStamp": "11/12/2020 05:07:17.827 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\AN_ALR69V\\indicator\\AN_ALR69V_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.827 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\CDU\\indicator\\CDU_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.828 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\CMSC\\indicator\\CMSC_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.828 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\CMSP\\indicator\\CMSP_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.828 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\DigitalClock\\Indicator\\DIGIT_CLK_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.828 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\MFCD\\indicator\\MFCD_left_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.828 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\MFCD\\indicator\\MFCD_right_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.828 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\UHF_Radio\\indicator\\freq_status_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.828 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\UHF_Radio\\indicator\\preset_channel_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.828 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\UHF_Radio\\indicator\\repeater_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.828 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\AV8BNA\\Cockpit\\MPCD\\indicator\\MPCD_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.828 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\DED\\indicator\\DED_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.828 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\EHSI\\indicator\\EHSI_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.829 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\EHSI\\indicator\\LCD\\EHSI_LCD.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.829 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\MFD\\indicator\\MFD_left_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.829 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\MFD\\indicator\\MFD_right_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.829 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\MFD\\indicator\\LCD\\MFD_LCD.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.829 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\EWS\\RWR\\indicator\\RWR_ALR56_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.829 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\F14\\Cockpit\\Scripts\\RWR\\Indicator\\Pilot\\init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.829 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\F14\\Cockpit\\Scripts\\RWR\\Indicator\\RIO\\init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.829 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\F14\\Cockpit\\Scripts\\UHF_Radio\\Indicator\\Main\\init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.829 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\F14\\Cockpit\\Scripts\\UHF_Radio\\Indicator\\RemotePilot\\init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.829 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\F14\\Cockpit\\Scripts\\UHF_Radio\\Indicator\\RemoteRIO\\init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.829 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\F14\\Cockpit\\Scripts\\VHF_Radio\\Indicator\\Main\\init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.830 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\F14\\Cockpit\\Scripts\\VHF_Radio\\Indicator\\RemotePilot\\init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.830 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\fonts.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.830 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\IFEI\\indicator\\IFEI_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.830 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\Multipurpose_Display_Group\\AMPCD\\indicator\\AMPCD_viewport_cfg.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.830 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\Multipurpose_Display_Group\\AMPCD\\indicator\\BAKE\\AMPCD_bake_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.830 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\Multipurpose_Display_Group\\Common\\indicator\\BAKE\\MPD_common_bake_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.830 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\Multipurpose_Display_Group\\MDI_IP1556A\\indicator\\MDI_left_viewport_cfg.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.830 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\Multipurpose_Display_Group\\MDI_IP1556A\\indicator\\MDI_right_viewport_cfg.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.830 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\TEWS\\indicator\\RWR_ALR67_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.831 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\UFC\\indicator\\UFC_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.831 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\Ka-50\\Cockpit\\Scripts\\ABRIS\\BAKE\\init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.831 PM",
          "Status": "DCS installation in 'I:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\Ka-50\\Cockpit\\Scripts\\SHKVAL\\BAKE\\init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "11/12/2020 05:07:17.831 PM",
          "Status": "Helios is managing DCS viewport patches",
          "Flags": 3,
          "Recommendation": "Do not also install viewport mods manually or via a mod manager like OVGME"
        }
      ]
    }
  ]
}

**Comment by Wingnut11275** [comment]
Can anyone Help me with this issue!

**Comment by derammo** [comment]
https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help#7-if-you-need-help-because-you-cant-figure-out-how-to-do-something-in-helios
