### ISSUE TITLE
How to / Can I send data to a Linux machine?

### ISSUE THREAD

**Issue by Fedaykin-Wolf** [HeliosVirtualCockpit/Helios#379]
totally new to Helios, just found it. I can't find  the info required by hours of searching.

So, I was wondering if I could send data (gauges, buttons, MFD's) to a separate Linux machine (preferably a Raspberry Pi)?

Where might I find instructions on how-to?

Thank you for your time

**Comment by derammo** [comment]
Here's a guide to how to get your questions answered:  
https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help

For example, this sort of question doesn't need an issue filed.  Just ask people on the Discord.

The answer to your question is:  No, there isn't any Linux support.  If you are building a cockpit and want to use embedded systems (mostly Arduino,) look at the DCS-BIOS project.

**Comment by Fedaykin-Wolf** [comment]
OK, Thank you. I was looking to output gauges and hopefully MFD's to another pc (as I'm out of video ports and pcie on my main PC)
