### ISSUE TITLE
Incorrect Glideslope and Localizer Bar Values

### ISSUE THREAD

**Issue by linknetx** [HeliosVirtualCockpit/Helios#380]
There are problems with the Falcon Interface ADI "ils vertical changed" and "ils horizontal changed" values.

**The First Problem:**

The values returned are as follows:

**For the Glideslope Bar:**

Specified Values: "ils vertical changed" Highest = -1 and Lowest = +1

Actual Values Returned: "ils vertical changed" Highest = -0.975 and Lowest = -1.025

Using a Lua Script correction code of -((TriggerValue + 1) x 40) gives the correct range (note the negation for this).

**For the Localizer Bar:**

Specified Values: "ils horizontal changed" Full Left = -1 and Full Right = +1

Actual Values Returned: "ils horizontal changed" Full Left = -1.025 and Full Right = -0.975

Using a Lua Script correction code of (TriggerValue + 1) x 40 gives the correct range (no negation in this case).

**The Second Problem:**

The values above even when corrected for scale are still referenced incorrectly to the aircraft centre line whereas they should be referenced to the flight path or flight path marker.

So the "ils vertical changed" should be corrected by adding a factor from the Angle of Attack AOA and the "ils horizontal changed" should be corrected by adding a factor from the sideslip (although I don't think that the sideslip value is available).

The main problem relates to the "ils vertical changed" values and according to my calculations the range of -1 to +1 represents an ILS cone with -5 degree to +5 degree limits giving a correction factor of 0.2 ( 2/10 ) to be added to the value for every 1 degree of AOA and obviously subtracted for negative values of AOA.

Stricly speaking this should be calculated using trigonometry but for small angles of AOA this isn't going to be significant.

**The Third Problem:**

This concerns the Falcon ADI in the Toolbox, this scales approximately correctly with an input range from -0.5 to +0.5 so this needs to be adjusted for a full scale range of -1 to +1.

Hopefully all of the above makes sense and is correct but it certainly need to be verified by someone else.

**Comment by ertiyu** [comment]
Can you provide a test model?
With ADI or you have the lua script.

**Comment by Todd1215** [comment]
BMS is exporting the ADI ILS bar values as the position of the bar in shared memory. Helios is taking those values and performing calculations on them. This has been this way since Helios was created. So changing those ADI ILS Vert / Horz values now would break lots of profiles.

Here is what Helios Falcon plugin is doing for ADI ILS calulations

ILS Horizontal  is determined by  (_lastFlightData.AdiIlsHorPos / 2.5f) - 1f)
ILS Vertical is determined by (_lastFlightData.AdiIlsVerPos * 2f) - 1f)

With that said we could create a "SharedMemory Values" section under the Falcon Interface that has a reference for all values coming out of BMS without being manipulated by Helios. This way it doesn't break existing profiles and the data is already in the HeliosFalcon plugin so there is no duplication of data. This will allow those that want to go the route of creating their own custom gauges the ability to do so with RAW data from BMS.

Thoughts??

**Comment by ertiyu** [comment]
this is an approach that is good for me.
So everyone can if they wish to do something else with the raw values of BMS.

**Comment by linknetx** [comment]
Changing the scaling of the values isn't really a problem, certainly if it would break other profiles. The main problem is that the glideslope values are referenced to the aircraft centre line and not the flight path. So having the raw data wouldn't help since there is no way in Helios profiles to adjust the ILS data with the AOA data. The only way would be to do this calculation in Helios and export an ILS glideslope deviation corrected for angle of attack.

**Comment by linknetx** [comment]
To give an example in an approach with say a 10 degree angle of attack and on the glideslope the ILS bar in the HUD is positioned correctly on the flight path marker. The ILS bar according to the Helios data is positioned on the aircraft centre line, 10 degrees above the flight path marker, showing that you should incorrectly fly up.

**Comment by linknetx** [comment]
Here are two ILS test profiles. Both with the scaling corrected but one not corrected for AOA and the other corrected for AOA using a horrendous kludge!!

https://www.mediafire.com/file/512zczitka8z3d7/ILS+Test.zip/file

**Comment by linknetx** [comment]
I suggest a new value for the glide slope corrected for angle of attack something like this:

```
FlightData.cs

// ADI values
public float AdiIlsHorPos; // Position of horizontal ILS bar
public float AdiIlsVerPos; // Position of vertical ILS bar
public float AdiIlsVerPosToFlightPath; // Position of vertical ILS bar to flight path

BMSFalconDataExporter.cs

SetValue("ADI", "ils vertical to flight path", new BindingValue((_lastFlightData.AdiIlsVerPos * 2f) - 1f) - (_lastFlightData.alpha * 0.0025f));
```
I've checked the value and it gives the correct position for the glide slope bar.

To be consistent this will give similar scaling to the original value:
ils vertical changed    Highest = -0.975 and Lowest = -1.025

**Comment by linknetx** [comment]
I would like to suggest a new value is established for the glide slope corrected for angle of attack something like this:

```
FlightData.cs

// ADI values
public float AdiIlsHorPos; // Position of horizontal ILS bar
public float AdiIlsVerPos; // Position of vertical ILS bar
public float AdiIlsVerPosToFlightPath; // Position of vertical ILS bar to flight path

BMSFalconDataExporter.cs

SetValue("ADI", "ils vertical to flight path", new BindingValue((_lastFlightData.AdiIlsVerPos * 2f) - 1f) - (_lastFlightData.alpha * 0.0025f));
```
I've checked the value and it gives the correct position for the glide slope bar.

To be consistent this will give similar scaling to the original value:
ils vertical changed  -   Highest = -0.975 and Lowest = -1.025

**Comment by Todd1215** [comment]
Where is this ( _lastFlightData.alpha ) coming from? It's not generated by BMS nor provided by Helios so it has to be calculated. I assume you meant to put that in the previous post @linknetx but it's missing.

**Comment by linknetx** [comment]
Apologies but it's a long time since I looked at any C# code.

What I was trying to find was the variable representing the angle of attack in degrees which at the moment I can't find.

**Comment by Todd1215** [comment]
disregard you are correct. BMS does provide AOA which is named alpha. Ok this is doable.

Header file entry
    float alpha;        // Ownship AOA (Degrees)

**Comment by Todd1215** [comment]
rethinking this one. If BMS is outputting ILS values that are what the ILS bar is suppose to be then why is Helios code transforming those numbers and why should we create another input value to work around a problem that possibly was created by the originator?

**Comment by linknetx** [comment]
That's a very good point, so what you are saying is BMS should fix it.

**Comment by linknetx** [comment]
That's a very good point, so what you are saying is BMS should fix it. But then again perhaps that is the value that BMS use internally and then they perform the correction for the angle of attack as required. So they may assume that providing both of the values is sufficient and then the user can perform the calculation. If this calculation could be done in a Helios profile then there wouldn't be a problem.

**Comment by Todd1215** [comment]
I suppose we could do a test and expose a non-modified version of ADIILSVert so we can see if those raw values will work without doing much else.

**Comment by linknetx** [comment]
I've done some more thinking and testing and I finally realise why BMS are perfectly correct in providing the glide slope referenced to the aircraft centre line and not referenced to the flight path or flight path marker.

It all relates to the scale used to display the glide slope deviation versus the scale of the pitch ladder on the screen. I used a scale of deviation to pitch ladder of 2 for it to look reasonable on the screen. On the HUD in BMS they are using a scale of deviation to pitch ladder of something like 0.5 or even less. In other words on the HUD the the deviation is very small in the centre of the HUD in relation to the pitch ladder.

Where is all of this leading to? Well the scale factor of 0.0025 I provided in this formula:

BindingValue((_lastFlightData.AdiIlsVerPos * 2f) - 1f) - (_lastFlightData.alpha * 0.0025f))

is only correct for a deviation scale to pitch ladder scale of 2. If you draw the deviation on the same scale as the pitch ladder then the scale factor in the formula needs to be 0.005 which is what I originally calculated and when I tested it found that I needed to halve it. This I now see was due to the deviation to pitch ladder scale of 2 that I am using.

So depending on which scale you draw the glide slope deviation in relation to the pitch ladder scale then you need a different scale factor in the above formula. So BMS are right in providing the uncorrected glide slope deviation together with the angle of attack fully expecting the user to carry out the calculation to correct for the scale used to draw the glide slope deviation.

The problem is that a Helios profile can't take two inputs and perform a calculation using both of them. That can only be done in the Helios software and output as a single Falcon Interface value.

So if you are going to provide this calculation then which scale factor to use? The scale factor of 0.0025 gives a better display of the deviation on the screen whereas a value of 0.005 whilst strictly correct gives a very small deviation on the screen. I would personally go for 0.0025 or maybe provide both and let the user choose a suitable correction.

I hope all of the above makes sense, it has taken me some time to fully understand what was going on.

**Comment by Todd1215** [comment]
We will leave the scaling factor at 0.0025 for now as it works with existing ADI gauge.

**Comment by Todd1215** [comment]
committed

**Comment by derammo** [comment]
assigned only for tracking purposes and credit, no action required
