### ISSUE TITLE
coocpit

### ISSUE THREAD

**Issue by luca2285** [HeliosVirtualCockpit/Helios#382]
[Helios has written the report to the file 'Helios_status_report_132530594079947297.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

[Helios_status_report_132530594079947297.txt](https://github.com/HeliosVirtualCockpit/Helios/files/5726601/Helios_status_report_132530594079947297.txt)

**Comment by derammo** [comment]
no description provided
