### ISSUE TITLE
help

### ISSUE THREAD

**Issue by luca2285** [HeliosVirtualCockpit/Helios#384]
{
  "Product": "Helios",
  "Version": "1.6.3308.0",
  "Items": [
    {
      "Report": [
        {
          "TimeStamp": "12/24/2020 02:44:18.548 PM",
          "Status": "Helios 1.6.3308.0000\nhttps://github.com/HeliosVirtualCockpit/Helios/"
        },
        {
          "TimeStamp": "12/24/2020 02:46:18.705 PM",
          "Status": "Loading Profile..."
        },
        {
          "TimeStamp": "12/24/2020 02:46:23.906 PM",
          "Severity": 2,
          "Status": "Cannot display this profile because it has an invalid monitor configuration.",
          "Recommendation": "Select reset monitors from the profile menu."
        },
        {
          "TimeStamp": "12/24/2020 02:47:11.135 PM",
          "Status": "Loading Profile..."
        },
        {
          "TimeStamp": "12/24/2020 02:47:11.472 PM",
          "Severity": 2,
          "Status": "The viewport data for this profile does not exist",
          "Recommendation": "Configure DCS Monitor Setup"
        },
        {
          "TimeStamp": "12/24/2020 02:47:11.501 PM",
          "Severity": 1,
          "Status": "Saved Games\\DCS\\Config\\MonitorSetup does not contain the monitor setup file 'Helios.lua'",
          "Recommendation": "Configure DCS Monitor Setup"
        },
        {
          "TimeStamp": "12/24/2020 02:47:11.503 PM",
          "Severity": 1,
          "Status": "Saved Games\\DCS\\Config\\MonitorSetup does not contain the monitor setup file 'Helios.lua'",
          "Recommendation": "Configure DCS Monitor Setup"
        },
        {
          "TimeStamp": "12/24/2020 02:47:12.951 PM",
          "Status": "Saved Games\\DCS\\Config\\options.lua has 'Resolution' set to 1800x1200",
          "Flags": 2,
          "Recommendation": "Using DCS, please make sure the 'Resolution' in the 'System' options is set to 1366x768"
        },
        {
          "TimeStamp": "12/24/2020 02:47:12.953 PM",
          "Status": "Saved Games\\DCS\\Config\\options.lua has 'Resolution' set to 1800x1200",
          "Flags": 2,
          "Recommendation": "Using DCS, please make sure the 'Resolution' in the 'System' options is set to 1366x768"
        },
        {
          "TimeStamp": "12/24/2020 02:47:12.974 PM",
          "Severity": 2,
          "Status": "Failed preflight check.",
          "Recommendation": "Please resolve problems or disable preflight check in preferences."
        }
      ],
      "Name": "Control Center Console"
    }
  ]
}

**Comment by derammo** [comment]
no description of any problem provided
