### ISSUE TITLE
FalconBMS - CalculateHSICourseDeviation

### ISSUE THREAD

**Issue by andreashohl82** [HeliosVirtualCockpit/Helios#385]
Version: 1.6.3309.0000
The calculated course deviation is not correct.
It should use the bearing to beacon and the desired course to calculate the course offset.
But instead it does something that does not work. i.e. if you set a course away from the beacon and have the beacon behind you the offset flips on the wrong side.

**Comment by Todd1215** [comment]
Issue #347 is where this code was introduced based on analysis work done by another user. If you suspect this to be incorrect then please provide more data.

**Comment by ertiyu** [comment]
Can you test with the latest version ?

https://github.com/HeliosVirtualCockpit/Helios/releases/tag/1.6.3424.0

**Comment by Todd1215** [comment]
Yes please test with 1.6.3424. I forgot that none of the changes you referenced are in 1.6.33xx they are in the latest version which was just released a few days ago

**Comment by andreashohl82** [comment]
I just did a test with 1.6.3424 and the HSI course deviation works fine. Thanks 👍
