### ISSUE TITLE
Half of  the Helios Control Center disappeared  since the updated to the latest version of Helios ( v.1.6.3425.0)

### ISSUE THREAD

**Issue by sunbiy-34gb** [HeliosVirtualCockpit/Helios#390]
![img_1](https://user-images.githubusercontent.com/74776121/103480468-f06fb880-4e17-11eb-864c-0ea5f988b2db.JPG)
Control disappeared as shown in the attached picture.
The same happens when I reinstall after delete it, or repair.

**Comment by derammo** [comment]
thank you for the good report.  This is bug #368 which I thought was fixed.  I guess it is not.

The workaround is to turn off "Start Minimized" preference in Control Center, either by text editing Documents\Helios\ControlCenterPreferences.xml or by simply deleting Documents\Helios\ControlCenterPreferences.xml to go back to default.

**Comment by sunbiy-34gb** [comment]
Thank you very much
I found the other half.... 
I love Helios
