### ISSUE TITLE
Helios Control Center background

### ISSUE THREAD

**Issue by ZwaardvisS806** [HeliosVirtualCockpit/Helios#392]
Since last update 1.6.3425.0000 I'm having a red background in control center.
Already did an uninstall and re-install but no change.

Any ideas?

Thanks
Sparks

![image](https://user-images.githubusercontent.com/22834155/104091850-6a70c900-5280-11eb-9802-f9ddd06a414f.png)

**Comment by nittch** [comment]
Same issue, each time I relaunch the control center, the red area becomes bigger and bigger...

![helios_bug_red](https://user-images.githubusercontent.com/13579757/104127481-9bc1c580-5362-11eb-8006-4679191b747c.png)

**Comment by derammo** [comment]
please try version 1.6.3308 

it would be helpful to know if it is really something changed in Helios or something changed in Windows (meaning it will happen with any version of Helios)

that would help a lot to figure this out and fix it

**Comment by nittch** [comment]
bug NOT REPRODUCED in 1.6.3308

in 1.6.3308 I've seen really really quickly flashing to red (like a few frames only), and then the windows has been resized to a working configuration
![helios_bug_working_1 6 3308](https://user-images.githubusercontent.com/13579757/104127772-45ee1d00-5364-11eb-828b-0e236aa719ec.png)

**Comment by derammo** [comment]
great thanks.   pretty sure I know what this is

**Comment by nittch** [comment]
Back to 1.6.3425 I don't reproduce anymore the issue, something is not understood from my side :)

Details about my setup: Windows 10 1904, lots of screen (six) really plug/unplug them very often.

**Comment by derammo** [comment]
I believe this is the same as #368 

original hadron code had some hard coded window size setting that I tried to replace with letting Windows size to content

obviously that isn’t working so I may have to put back the gross hard coded stuff and move on :)

**Comment by ZwaardvisS806** [comment]
Got the problem solved.

I have deleted the file: ControlCenterPreferences.xml from the documents/Helios folder.
Restarted the control center, changed the profile back into my own profile. Started the profile for test and closed it.
It has created new file ControlCenterPreferences.xml in my documents Helios folder.

If interested, I  can send both files to compare and see if it is kind of bug that can be solved.


Thanks
Sparks

**Comment by derammo** [comment]
yes please that’s a great idea

**Comment by derammo** [comment]
@ZwaardvisS806 yes please that’s a great idea

**Comment by ZwaardvisS806** [comment]
Hello,

 

Please find attached.

 

 

Thanks

Sparks

**Comment by ZwaardvisS806** [comment]
Files send by mail.

Regards
Sparks

**Comment by derammo** [comment]
@ZwaardvisS806 that didn't work... I don't think you can attach files by email unless they are the valid kind of file.  Put both the files in a zip and attach it here.  Zip is allowed by github

**Comment by ZwaardvisS806** [comment]
Retry.

**Comment by ZwaardvisS806** [comment]
@derammo 

[control center.zip](https://github.com/HeliosVirtualCockpit/Helios/files/5796458/control.center.zip)

**Comment by derammo** [comment]
@ZwaardvisS806 are you on discord?   could you message me there if you are?

**Comment by derammo** [comment]
using the enclosed preferences file, it reproduces and appears fixed in a build I will shortly publish (3426.4)

**Comment by derammo** [comment]
@ZwaardvisS806 please try https://github.com/HeliosVirtualCockpit/Helios/releases/tag/1.6.3426.4

**Comment by ZwaardvisS806** [comment]
@derammo i donnot have Discord and guess we are not in same TZ. I’m from The Netherlands. Like said above my problem is solved.  Not sure you still want me to install the beta release?

**Comment by derammo** [comment]
@ZwaardvisS806 I was hoping you could try the new build with your old saved ControlCenterPreferences.xml to confirm it is fixed.

**Comment by ertiyu** [comment]
Hello ammo
I just took the test.
With 1.6.3425 I have a red stripe.
![Sans titre1](https://user-images.githubusercontent.com/52707215/104312451-eb290280-54d6-11eb-969e-70b4c5095b11.png)

With 1.6.3426 more red stripe.
![Sans titre2](https://user-images.githubusercontent.com/52707215/104312437-e6644e80-54d6-11eb-9fe8-74f3a5a778bd.png)

Thanks for the job done!

**Comment by derammo** [comment]
world's best volunteer strikes again

**Comment by ZwaardvisS806** [comment]
@derammo Installed Beta 1.6.3426.0004 and tested with previous corrupted ControlCenterPrefeences.xml

All fine, problem solved.

Thanks for help.

**Comment by nittch** [comment]
Tested 1.6.3426.4 and it's working fine also
