### ISSUE TITLE
Left & Right MFD's blank - Warnings after cockpit loads

### ISSUE THREAD

**Issue by Slick8791** [HeliosVirtualCockpit/Helios#393]
Falcon BMS 4.35 Using BMS-Viper-435-V1.0 template
Warnings displayed after loading the cockpit in game.  Analog gauges work but both Left & Right MFD's are blank.

[Helios_status_report_132553778638741561.txt](https://github.com/HeliosVirtualCockpit/Helios/files/5826517/Helios_status_report_132553778638741561.txt)

**Comment by ertiyu** [comment]
Hello, for the errors in the text file, it will be necessary to see with linknet.
To display the MFDs, have you considered activating

set g_bExportRTTTextures 1 // This enables the shared texture memory area for HUD / MFDs / HMS / RWR / DED / PFL

**Comment by Slick8791** [comment]
Thanks ertiyu!  My apologies as I'm new to this process and GitHub in general.  Yes, the enabling of the "set" line command did allow the MFD's to display and are visible in the game.  However, none of the button around the MDF's seem to work/do anything.  I'm not sure if additional setup is needed elsewhere of if the template even allows that to work. 

I don't understand your reference to "linknet"...?

**Comment by ertiyu** [comment]
I was thinking about this profile, which is from linknet,
https://www.benchmarksims.org/forum/showthread.php?41095-Ice%E2%80%99s-Falcon-BMS-Profile-Updated-for-BMS-4-35

The errors that are in your text file, if I am not mistaken, are not Helios bugs.
It is the creator of the profile who has written a lua code which causes errors.

For your info Github is only there to report internal bugs to Helios.
You will have to ask the creator of your profile.

Imagine if all the people come here to report the mistakes of the profile creators, Ammo is going to go crazy.

I hope you don't take my explanation badly. 

There is no smiley, in GitHub it's a serious place ^^.

**Comment by ertiyu** [comment]
I forgot to mention your problem with the MFD button not responding. ;)
There can be two causes for its:

1. you have not loaded the .key file provided by the designer in BMS.
2. You loaded the file into BMS so it is most certainly the fact that your keyboard is not in qwerty.

**Comment by Slick8791** [comment]
Understood, and thanks for the help!  I'll dig a little deeper on the keyboard.
