### ISSUE TITLE
Helios bug profile

### ISSUE THREAD

**Issue by epalzeolithe** [HeliosVirtualCockpit/Helios#395]
[Helios has written the report to the file 'Helios_status_report_132559666404771898.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

**Comment by BlueFinBima** [comment]
@epalzeolithe  "Helios has written the report to the file 'Helios_status_report_132559666404771898.txt' and opened its containing folder in Explorer. **Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.**"
