### ISSUE TITLE
Mouse won’t move

### ISSUE THREAD

**Issue by maddog453** [HeliosVirtualCockpit/Helios#397]
I’m using Helios with Ices falcon profile. The screen with the cockpit shows up and the gauges reflect the sim values.

the problem is when I try to move the mouse to the new screen the mouse won’t go pst the right edge of monitor 1.

I have tried with a 2nd monitor hooked to the computer, a monitor connected by the network and with space desk.

I tried changing the values in falcon bms config for mouse exclusivity and the button 4 disconnect mouse. I even tried a program called mouseunsnag. Nothing works

everything works fine in dcs.

any help would be appreciated 

doug

**Comment by derammo** [comment]
this is BMS being weird about the mouse.   You don't need to file a bug for something like this,  see <https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help>.  That way, you don't notify all Helios developers :).... *ahem*

I recommend you ask on the BMS channel https://discord.gg/3QQDGczyfX unless wheelchock answers it for you here.
