### ISSUE TITLE
Falcon Interface Falcon registry path hardcoded to BMS 4.34

### ISSUE THREAD

**Issue by oakdesign** [HeliosVirtualCockpit/Helios#398]
Within the FalconInterface.cs the registry path for the 

```
case FalconTypes.BMS:
                            pathKey = Registry.LocalMachine.OpenSubKey(@"SOFTWARE\WOW6432Node\Benchmark Sims\Falcon BMS 4.34");
                            break;
```
is hardcoded to 4.34
With BMS 4.35 released in 12/2020 it should be considered to be able to select the version through a dropdown on the Falcon Interface settings. On my side currently not an issue as i have both 4.34 and 4.35 installed and the only culprit is that the keyfile selection opens in the 4.34 User/config folder. 
Haven't tested yet if i remove the regkey for 4.34 so as I would have only 4.35 installed.

Edit: Tested with 4.34 registry key removed. So keyfile path then defaults to "User\config" and the file Open dialog to Users\Documents.
Not really a big issue but might confuse unexperienced users. 
I'd suggest to read use 
`Registry.LocalMachine.OpenSubKey(@"SOFTWARE\WOW6432Node\Benchmark Sims").GetSubKeyNames();`
to read the installed versions of BMS to prepopulate the BMS Version selection dropdown.

If I find some time might submit a PR for that

**Comment by Todd1215** [comment]
I am aware of the issue and do plan on fixing this at some point.
