### ISSUE TITLE
Helios AJS-37 Bug

### ISSUE THREAD

**Issue by ManLo46** [HeliosVirtualCockpit/Helios#405]
[Helios has written the report to the file 'Helios_status_report_132583054620347733.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

{
  "Product": "Helios",
  "Version": "1.6.3426.4",
  "Items": [
    {
      "Report": [
        {
          "TimeStamp": "02/20/2021 04:38:05.883 PM",
          "Status": "Failed to install CaptZeen AJ37 beta 1.hpf.helios16"
        },
        {
          "TimeStamp": "02/20/2021 04:38:05.883 PM",
          "Status": "Attempt to install Helios Profile from '%USERPROFILE%\\Downloads\\CaptZeen AJ37 beta 1.hpf.helios16' failed"
        },
        {
          "TimeStamp": "02/20/2021 04:36:39.331 PM",
          "Severity": 2,
          "Status": "Unexpected error from attempt to install Helios Archive '%USERPROFILE%\\Downloads\\CaptZeen AJ37 beta 1.hpf.helios16'",
          "Recommendation": "Make sure the specified file is a valid archive.  If this error persists, report it to the developer of this Profile or file a bug against Helios.",
          "Code": [
            {
              "Text": "Newtonsoft.Json.JsonReaderException: Invalid property identifier character: ]. Path 'Choices[0].Options[1].Description', line 23, position 20.",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.JsonTextReader.ParseProperty()",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)",
              "LineEnding": 1
            },
            {
              "Text": "   at GadrocsWorkshop.Helios.ProfileEditor.ArchiveInstall.ArchiveInstall.LoadManifest(ZipArchiveEntry manifestEntry)",
              "LineEnding": 1
            },
            {
              "Text": "   at GadrocsWorkshop.Helios.ProfileEditor.ArchiveInstall.ArchiveInstall.Install(IInstallationCallbacks2 callbacks)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.JsonTextReader.ParseProperty()",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)",
              "LineEnding": 1
            },
            {
              "Text": "   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)",
              "LineEnding": 1
            },
            {
              "Text": "   at GadrocsWorkshop.Helios.ProfileEditor.ArchiveInstall.ArchiveInstall.LoadManifest(ZipArchiveEntry manifestEntry)",
              "LineEnding": 1
            },
            {
              "Text": "   at GadrocsWorkshop.Helios.ProfileEditor.ArchiveInstall.ArchiveInstall.Install(IInstallationCallbacks2 callbacks)",
              "LineEnding": 0
            }
          ]
        }
      ],
      "Name": "Configuration Results"
    }
  ]
}

**Comment by derammo** [comment]
is this reproducible?  if so, could you link to the profile we have to download to reproduce it, please?

**Comment by sobe1205** [comment]
I think you need to put helios16 in the second location.

**Comment by derammo** [comment]
user never responded
