### ISSUE TITLE
hellp

### ISSUE THREAD

**Issue by luca2285** [HeliosVirtualCockpit/Helios#407]
[Helios has written the report to the file 'Helios_status_report_132603330548169078.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

[Helios_status_report_132603330548169078.txt](https://github.com/HeliosVirtualCockpit/Helios/files/6145548/Helios_status_report_132603330548169078.txt)

**Comment by derammo** [comment]
https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help

https://www.youtube.com/playlist?list=PLCiL8SHubzhyPA38GyeyL2TCLlKjhtLz6
