### ISSUE TITLE
Adding interface location causing crash

### ISSUE THREAD

**Issue by LeIceHomme** [HeliosVirtualCockpit/Helios#409]
Trying to add an interface location in the profile editor but repeatedly crashing to desktop. Getting the error shown below. 

![Capture](https://user-images.githubusercontent.com/50210409/113481088-88b92000-948f-11eb-8274-3c6a4df7784d.PNG)

**Comment by BlueFinBima** [comment]
I presume that this is line 243 in InstallationLocations.cs, but I'm not sure why g would be an empty or single character string.

**Comment by derammo** [comment]
I didn't look at it yet, but you can easily get nonsense if the registry keys from DCS installation location have crap in them or something.  Since that is external data, I should have sanitized it but apparently did not.

**Comment by derammo** [comment]
fixed by just filtering any bad data instead of crashing
