### ISSUE TITLE
Error of install Fa18 V3.1

### ISSUE THREAD

**Issue by Mhax51** [HeliosVirtualCockpit/Helios#411]
J ai essayé d installer le profil F18 V3.1
[Helios_status_report_132629099228370580.txt](https://github.com/HeliosVirtualCockpit/Helios/files/6313856/Helios_status_report_132629099228370580.txt)

**Comment by derammo** [comment]
Please copy the .helios16 file to another location, like Desktop or a temporary directory, before you open it.  Helios appears to be having problems opening the file.

--------------------------


Veuillez copier le fichier .helios16 vers un autre dossier, "Desktop" ou un répertoire temporaire, avant de l'ouvrir. Helios semble rencontrer des problèmes pour ouvrir le fichier.

**Comment by derammo** [comment]
@ertiyu how is google translate doing?  does this parse? :)

**Comment by ertiyu** [comment]
Google a bien fait son travail ;)

**Comment by derammo** [comment]
user never responded
