### ISSUE TITLE
new viewport patches for AJS-37 in DCS 2.7

### ISSUE THREAD

**Issue by Denver29** [HeliosVirtualCockpit/Helios#412]
[Helios has written the report to the file 'Helios_status_report_132629838210651277.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

{
  "Product": "Helios",
  "Version": "1.6.3504.1",
  "Items": [
    {
      "Report": [
        {
          "TimeStamp": "04/15/2021 08:10:42.127 ",
          "Status": "Helios viewport patches installation would fail"
        },
        {
          "TimeStamp": "04/15/2021 08:10:42.127 ",
          "Status": "Some patches would fail to apply.  No patches have been applied."
        },
        {
          "TimeStamp": "04/15/2021 08:09:39.437 ",
          "Severity": 2,
          "Status": "DCS installation in 'G:\\DCS World OpenBeta' could not install patches.  You may have viewport mods installed that need to be removed or DCS may have changed too much during a recent update.",
          "Recommendation": "Please make sure you do not have viewport mods installed.  If your DCS installation is free from modifications and patches still fail, then install a newer Helios distribution or patches with support for this DCS version."
        },
        {
          "TimeStamp": "04/15/2021 08:09:39.437 ",
          "Severity": 2,
          "Status": "DCS installation in 'G:\\DCS World OpenBeta' failed to apply patch to Mods\\aircraft\\AJS37\\Cockpit\\scripts\\radar\\Indicator\\init.lua: CONTENT_NOT_FOUND\r\nThe patch could not locate the expected content section (searching near character 477):",
          "Recommendation": "Please make sure you do not have viewport mods installed.  If your DCS installation is free from modifications and patches still fail, then install a newer Helios distribution or patches with support for this DCS version.",
          "Code": [
            {
              "Text": "EST2",
              "LineEnding": 2
            },
            {
              "Text": "\t },",
              "LineEnding": 2
            },
            {
              "Text": "}",
              "LineEnding": 2
            },
            {
              "Text": "",
              "LineEnding": 2
            },
            {
              "Text": "\u0001\u0002\u0003\u0004",
              "LineEnding": 0
            }
          ]
        }
      ],
      "Name": "Configuration Results"
    }
  ]
}

**Comment by Todd1215** [comment]
I have Helios version 1.6.3504.1 and have run profiles against DC 2.7 without any issue. I did have to remove DCS patches and reapply them. Have you done that?

Also can you be a bit more specific as to what is the problem rather than just dumping a status report into a GitHub issue

**Comment by derammo** [comment]
@Todd1215 actually the status report is exactly what we need, so @Denver29 did it correctly.   I believe the patches for the AJS-37 just don't fit and maybe you don't have that aircraft installed.  Will verify.

**Comment by derammo** [comment]
@Denver29 it seems like we don't ship the AJS-37 patches with Helios?  Are these from Capt Zeen?  Can you link the profile archive that you installed please?

**Comment by derammo** [comment]
@Denver29 ok I confirmed these patches come from the Capt Zeen profile for AJS-37.  

Workaround:  please delete the folder "My Documents\Helios\Patches" to remove all profile-provided patches.  This means the viewports for the Viggen will stop working until Capt Zeen releases new patches for it.   At least the other profiles will work then, though.

**Comment by Denver29** [comment]
Hi
Sorry for unpersonnal and precise bug report. Not used to do this kind of report and as Helios automaticaly do it well it do it auto!!
Derammo your last message resolve all my problem si it definitely come fro capt Zenn AJS-37 profile

Thanks a lot

**Comment by BlueFinBima** [comment]
Seems this issue has concluded.

**Comment by BlueFinBima** [comment]
Patches delivered in 1.6.5400.2
