### ISSUE TITLE
Multimonitor setup conflict

### ISSUE THREAD

**Issue by Clyberic** [HeliosVirtualCockpit/Helios#416]
Hello Guys,
After the computer is rebooted my multi montor setup does not settle properly as expected when firing up DCS. The viewports are projected on the DCS main screen and everytime i need to setup DCS to update the Export Script to  support the profile in DCS. As a side effect i need to reinstall or update other apps like SRS as well...very annoying.
Also ,  the DCS Welcome screen  isnt neatly arranged in the middle of the mainscreen which isnt really important but it might help figure out what the problem is,
I have read some of the multi monitor issues but non of those solutions really worked for me like changing DPi  for all screens to 100% ,Changed some settings like scaling off via Graphicscards.

![Welcom1](https://user-images.githubusercontent.com/58867753/116979753-ac0d0000-acc5-11eb-9631-654ea2ccce21.jpg)
![profile int 2](https://user-images.githubusercontent.com/58867753/116978334-dd84cc00-acc3-11eb-88a7-fc389cef0da3.jpg)
![Welcom2](https://user-images.githubusercontent.com/58867753/116979937-ea0a2400-acc5-11eb-8991-23efaa1c9201.jpg)
![Inkedmultiphel_LI](https://user-images.githubusercontent.com/58867753/116980393-79173c00-acc6-11eb-85d9-08aaeec3e06d.jpg)
![export](https://user-images.githubusercontent.com/58867753/116980462-8c2a0c00-acc6-11eb-9171-28914d3787a6.jpg)
![screen](https://user-images.githubusercontent.com/58867753/116980493-96e4a100-acc6-11eb-925a-ae0a6f65ebf5.jpg)

[Export_luafile..txt](https://github.com/HeliosVirtualCockpit/Helios/files/6420007/Export_luafile.txt)
[Export.lua.backup.20210504.txt](https://github.com/HeliosVirtualCockpit/Helios/files/6420024/Export.lua.backup.20210504.txt)
[Helios.lua.txt](https://github.com/HeliosVirtualCockpit/Helios/files/6420044/Helios.lua.txt)
[options_lua.txt](https://github.com/HeliosVirtualCockpit/Helios/files/6420050/options_lua.txt)

Regards, B.H

**Comment by derammo** [comment]
There are a few separate things going on here.   

1) the Export.lua file:    This file has nothing to do with monitors or exported views.  It only calls scripts that "export" the gauge values, switches, etc. and handle any input coming back from external programs such as Helios or SRS.    The "always overwrite" mode for writing the Export.lua file is for people who have configured Helios to actually call the other modules (such as SRS.)   However, you have apparently edited this file yourself, so you need to use a different mode (which is the default mode):

![image](https://user-images.githubusercontent.com/817160/117005958-d656c180-acb5-11eb-94a5-a0842da37023.png)
    
2) After you fix that and realize that Export.lua does not affect monitors, we can figure out the multi monitor setup issue.   Please provide your interface status report <https://github.com/HeliosVirtualCockpit/Helios/wiki/Status-Report-Sharing>.  You can copy and paste it here or attach as a file.

**Comment by Clyberic** [comment]
Hello Derammo
Thx for your response,  I saw that but didnt know what it really does so i
havnt touched it. ... ill give it a shot and keep you posted.

thx.
B.H

Op di 4 mei 2021 14:54 schreef derammo ***@***.***>:

**Comment by Clyberic** [comment]
it was set already to " Always overwrite file ". 
![Uploading 16201508560317803513686329134700.jpg…]()

**Comment by Clyberic** [comment]
> 1. you have apparently edited this file yourself, so you need to use a different mode

iam confused... what file would i have edited ? If you mean the Export.lua file, i have not. I clicked on the box " setup dcs " but i havnt  manually messed with the export file in DCS.

I have changed the export output option to '' update if possible " but the problem still  excist

**Comment by derammo** [comment]
let's take one problem at a time:

1) the fact that you keep having to rewrite the Export.lua file:

With "update the file if possible" it should just find that its HeliosExport16 is already called and do nothing.  It will say so in the details section on the DCS Blackshark interface

If you still get "an updated DCS export..." message after that, then you have something else also changing the file and removing our changes, such as OVGME or some installer trying to manage the SRS entry?    If you didn't change the file yourself, how did it end up calling SRS?

2) monitors afterwards...

**Comment by Clyberic** [comment]
I have rebooted the computer and it seems that export file is fixed  and stable even SrS  works. At first i tought the screen behavior and SrS issues were related but it was the export file.

**Comment by derammo** [comment]
Like I said, these are separate issues.   Now let's look at your monitors problems.   Please share the report I asked for above

**Comment by Clyberic** [comment]
[int_stat_rep.txt](https://github.com/HeliosVirtualCockpit/Helios/files/6423688/int_stat_rep.txt)

**Comment by derammo** [comment]
excellent, thank you.   This all looks correct.   It is configured to do the following, please tell me which ones do not happen:

1) the DCS UI starts up on the main monitor, which is 5760x1080.   The menus should be covering the entire monitor.

2) the viewports are on the second monitor, just to the right of the main monitor

3) before Helios is started, nothing in rendered on the other two monitors (no DCS, no viewports)

4) Helios draws controls over the viewports on the second monitor and on the other two monitors

**Comment by derammo** [comment]
is the red arrow in your screen shot above still on the main screen, i.e. the DCS view doesn't cover the entire screen?

**Comment by derammo** [comment]
also:   did you mistakenly set DCS to run in fullscreen?  it looks like it is squishing all the content (the main view and one monitor's worth of viewports) into the main display, which I guess is what you are reporting?

**Comment by derammo** [comment]
reopen:  hit wrong button, sorry :)

**Comment by Clyberic** [comment]
> excellent, thank you. This all looks correct. It is configured to do the following, please tell me which ones do not happen:
> 
> 1. the DCS UI starts up on the main monitor, which is 5760x1080.   The menus should be covering the entire monitor.
> 2. the viewports are on the second monitor, just to the right of the main monitor
> 3. before Helios is started, nothing in rendered on the other two monitors (no DCS, no viewports)
> 4. Helios draws controls over the viewports on the second monitor and on the other two monitors

All of these four mentioned above are  as how it works here

**Comment by Clyberic** [comment]
> also: did you mistakenly set DCS to run in fullscreen? it looks like it is squishing all the content (the main view and one monitor's worth of viewports) into the main display, which I guess is what you are reporting?

-Its not set  to Fullscreen.
- Thats exactly what happens  it all got squeezed on the main window
![settings](https://user-images.githubusercontent.com/58867753/117069433-c0381800-ad2c-11eb-91cd-50331285dcfb.jpg)

**Comment by Clyberic** [comment]
> is the red arrow in your screen shot above still on the main screen, i.e. the DCS view doesn't cover the entire screen?

Yes... thats it... There is either a black window when Helios is not fired up or when it is on,  the skval and abris appear in that main window

**Comment by derammo** [comment]
Which monitor is selected as the "Make this my main display" display in the Windows "Rearrange multiple monitors" ?

![image](https://user-images.githubusercontent.com/817160/117070123-58b5a480-acfb-11eb-9107-735472ca31f4.png)

**Comment by Clyberic** [comment]
> Which monitor is selected as the "Make this my main display" display in the Windows "Rearrange multiple monitors" ?
> 
> ![image](https://user-images.githubusercontent.com/817160/117070123-58b5a480-acfb-11eb-9107-735472ca31f4.png)

The Main ( DCS ) window  is selected as primary window.

**Comment by derammo** [comment]
ugh... you can't use surround
 
it makes multiple monitors into one monitor, which is exactly what you are seeing

**Comment by Clyberic** [comment]
> ugh... you can't use surround
> 
> it makes multiple monitors into one monitor, which is exactly what you are seeing

How do you mean "cant" ? thats how i have done it always.
the 3 monitors are hooked together on a separate card while the other 3 are at another G.card

**Comment by derammo** [comment]
oh I see.... the "main" 5760 is actually a triple via surround, but the 4th one is separate

understood, that should be ok except DCS is getting it wrong.   So please try this for me:

set your monitors up like this in windows:

top row:  main triple plus the one screen that gets viewports to its right
second row: the other two screens that only get controls, but no view ports

now select "row" mode in DCS Monitor Setup interface:
![image](https://user-images.githubusercontent.com/817160/117073661-3a9e7300-ad00-11eb-8388-7cbc78ecabb1.png)

now your DCS resolution should be the same as before, except that the "extra" screens are separately below.   This might help DCS correctly match your resolution to where it needs to go.   DCS basically doesn't have a configuration for "put the main window at THIS position" so we have to tickle it into doing the right thing by matching the resolution to something that includes the main view and that it can figure out

as always, make sure 100% scaling is set on all the displays that DCS sees (the main one and the first Helios one with the viewports)

**Comment by Clyberic** [comment]
okey but what about that empty space under the second viewport monitor ? Will that also be rendered and isnt it useless load on the G.card which could result in less FPS ?
And i must adjust the option file graphic settings to 7689x1080
![monsup](https://user-images.githubusercontent.com/58867753/117076354-8cfa8680-ad36-11eb-8ec4-ca9b83dc23d2.jpg)

**Comment by derammo** [comment]
it should be the same resolution.  you must have nudged the screen by 9 pixels in the windows control panel.   it should still be 7680 if you stick it on the right exactly

the dead space isn't even part of the DCS window, and does not get rendered.   in fact, when we get this working we should move the viewports monitor to the first graphics card so that DCS doesn't use the extra graphics card at all (only Helios)

that's the optimal config for what you have there hard ware wise

**Comment by Clyberic** [comment]
it seems to work

**Comment by derammo** [comment]
7680x1080?   seems like DCS' window placement algorithm freaked out with all those monitors before.  weird.

if you have a fourth output on the first graphics card, try running the viewports monitor on there and compare FPS.  spanning the DCS window (for viewports) across graphics cards destroys graphics performance in my experience

closing this as a DCS problem

**Comment by Clyberic** [comment]
Thank you very much for the support

**Comment by Clyberic** [comment]
Hello DERAMMO,
Did you know that the discord Helios channel in Hotas is removed ?
Anyway... the screen issue is not fixed and did not fit properly today again.

Also after i had reposisioned the windows the viewports were  messed up. when i run the profile the viewports are black as if there is a background behind . In the editor it was normally pink but now the dashbord cutouts are blue. Clicking them makes it pink again but not in the monitorsetup setction of the editor 

![Uploading 20210505_125700.jpg…]()

**Comment by derammo** [comment]
I still see the Helios channel in HOTAS.  

I don't think I can spend any more time on this DCS issue that seems to be affecting only you.  I assume there is something weird with how you combine the monitors or something like that is confusing DCS.  But it really doesn't have anything to do with the Helios code.    Maybe ask on the DCS discord.

**Comment by Clyberic** [comment]
No problem...thx anyway,  at least i some ideas to work with. I have rearranged the monitors once again and it seems to work.
