### ISSUE TITLE
Steam autoupdate.cfg error

### ISSUE THREAD

**Issue by drdotpepper** [HeliosVirtualCockpit/Helios#418]
Attaching control center and profile editor logs - had a crash due to autoupdate.cfg in my steam folder

[Control Center Problems.log](https://github.com/HeliosVirtualCockpit/Helios/files/6459767/Control.Center.Problems.log)
[Profile Editor Problems.log](https://github.com/HeliosVirtualCockpit/Helios/files/6459768/Profile.Editor.Problems.log)

**Comment by derammo** [comment]
file was corrupted, addressed by #428
