### ISSUE TITLE
autoupdate.cfg

### ISSUE THREAD

**Issue by drdotpepper** [HeliosVirtualCockpit/Helios#419]
[Helios has written the report to the file 'Helios_status_report_132652157649775940.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

**Comment by drdotpepper** [comment]
[Helios_status_report_132652157649775940.txt](https://github.com/HeliosVirtualCockpit/Helios/files/6459782/Helios_status_report_132652157649775940.txt)

**Comment by derammo** [comment]
duplicates #418 
adds additional log file
