### ISSUE TITLE
Helios should handle failure to parse autoupdate.cfg 

### ISSUE THREAD

**Issue by Foxbat107** [HeliosVirtualCockpit/Helios#428]
![dcs autoudateerror](https://user-images.githubusercontent.com/13083987/124367303-9fe8e480-dc1b-11eb-88e6-161ae8ccc7e0.jpg)
this error come up when open profile   pleease help  email me at *[email removed]* please[Helios has written the report to the file 'Helios_status_report_132698210544465937.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

**Comment by derammo** [comment]
@Foxbat107 it is saying it can't read the status file of your DCS installation location.  Run DCS repair, that should fix the file.
There is no email support, so I will just remove your address from your report so you don't get spammed by any bots that read this.

----- 

dev notes: This is at least the second time this has happened to a user.   We should gracefully handle failure to parse autoupdate.cfg, make a copy of the file contents into the log for debugging, and tell the user to repair DCS.
