### ISSUE TITLE
Show multiple MFDs on a 10 "screen?

### ISSUE THREAD

**Issue by ManuelPeiro** [HeliosVirtualCockpit/Helios#433]
Hi,

First of all, congratulate the developers for this great software.

I really don't know if it's an issue or if I don't know how Helios works well.

I have made this query in the DCS forum and in a YouTube channel, but I have not had clarification.
I'm using Helios for DCS the F18 module (at the moment) and I'm using it on a 10 "touch screen connected by HDMI and USB.

At first I made a simple profile, on the screen the right MFD was shown and it was Clickable (Touch) ... but soon I liked it and wanted more, so I thought about showing other parts of the cabin, the project idea consists with 4 views (right MFD, left MFD, central MFD and UFC), in addition to this 4 buttons, the mission of these buttons is to show 1 of the views and hide the rest.

Well, when I made the panel in HELIOS PROFILE EDITOR, everything worked as expected, each of the 4 buttons shows an instrument and hides the rest ... but the problem comes when I try it with DCS, the panels DOES that they are shown properly ... but the dynamic area of ​​the panel is NOT hidden, it is always visible ...

Any idea why this could be?

[Screen capture](https://www.dropbox.com/s/xo6fyrndl1k2ylh/Helios%20Issues.png?dl=0)

**Comment by Todd1215** [comment]
What is happening here is that you put all the viewports into the same location, but what you really did was tell DCS to render all the viewports into the same location. Helios only creates the viewport config that DCS reads. So it has no control over layering of the viewports (which isn't available in DCS) which is what you are trying to do.
