### ISSUE TITLE
exceptions in Add Interface dialog should be presented to user

### ISSUE THREAD

**Issue by rudek1980** [HeliosVirtualCockpit/Helios#456]
hellow
my joystick devices not on add interface list?

**Comment by rudek1980** [comment]
hi im trying to edit f-16 profile  i'm open (profile\add interface )
and im see just  3 option: eos\control router\falcon
(no trustmaster/or winwing.....)no joystics
how to add them pls?

**Comment by rudek1980** [comment]
![helios](https://user-images.githubusercontent.com/90444733/132860793-683c22d2-cced-4890-8f91-7b0d37ffe2e4.jpg)

**Comment by derammo** [comment]
try removing any joystick interfaces present in the profile (warthog etc).   Use Interface Status or Profile Explorer views to find them and remove them

**Comment by derammo** [comment]
also attach your interface report to any questions or issues please: https://github.com/HeliosVirtualCockpit/Helios/wiki/Status-Report-Sharing

**Comment by rudek1980** [comment]
thx
{
  "Product": "Helios",
  "Version": "1.6.3605.0",
  "Items": [
    {
      "Name": "Profile Interface",
      "Report": [
        {
          "TimeStamp": "09/10/2021 05:07:50.490 PM",
          "Status": "Profile is '%USERPROFILE%\\Documents\\Helios\\Profiles\\f-16bl60 3mon.hpf'",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:07:50.490 PM",
          "Status": "The monitor arrangement saved in this profile matches this computer",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:07:50.490 PM",
          "Status": "The profile declares a monitor of size 2560x1440 at (0, 0)",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:07:50.490 PM",
          "Status": "The profile declares a monitor of size 768x1024 at (0, 1440)",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:07:50.490 PM",
          "Status": "The profile declares a monitor of size 1680x1050 at (871, 1440)",
          "Flags": 3
        }
      ]
    },
    {
      "Name": "Keyboard",
      "Report": []
    },
    {
      "Name": "DCS Generic impersonating F-16C_50",
      "Report": [
        {
          "TimeStamp": "09/10/2021 05:06:16.370 PM",
          "Status": "Not writing to DCS version 2.5.6.55960 installed at 'F:\\DCS World' with Saved Games at '%USERPROFILE%\\Saved Games\\DCS'",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.370 PM",
          "Status": "DCS version 2.7.5.10869 installed at 'F:\\DCS World OpenBeta' with Saved Games at '%USERPROFILE%\\Saved Games\\DCS.openbeta'",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.370 PM",
          "Status": "Export scripts location for DCS.openbeta exists",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.370 PM",
          "Status": "Export.lua stub for DCS.openbeta calls HeliosExport16.lua",
          "Flags": 2
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.371 PM",
          "Status": "The configured DCS export script at '%USERPROFILE%\\Saved Games\\DCS.openbeta\\Scripts\\Helios\\HeliosExport16.lua' is up to date",
          "Flags": 2
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.371 PM",
          "Status": "The export module provided by Capt Zeen (Version 1) at '%USERPROFILE%\\Saved Games\\DCS.openbeta\\Scripts\\Helios\\Mods\\Helios_F16C.lua' is up to date",
          "Flags": 2
        }
      ]
    },
    {
      "Name": "DCS Monitor Setup",
      "Report": [
        {
          "TimeStamp": "09/10/2021 05:06:16.371 PM",
          "Status": "Windows reports a scaling value of 100% (96 dpi)",
          "Flags": 3,
          "Recommendation": "This version of Helios does not support using different display scaling (DPI) on different monitors.  Make sure you use the same scaling value for all displays."
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.372 PM",
          "Status": "viewport 'F_16C_RIGHT_MFCD' is provided by 'DCS Additional Viewports'",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.372 PM",
          "Status": "viewport 'F_16C_LEFT_MFCD' is provided by 'DCS Additional Viewports'",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.372 PM",
          "Status": "viewport 'F_16C_DED' is provided by 'DCS Additional Viewports'",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.372 PM",
          "Status": "Helios: A_10C_2_CDU_SCREEN = { x = 1630, y = 857, width = 296, height = 217 }",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.372 PM",
          "Status": "Helios: A_10C_2_LEFT_MFCD = { x = 82, y = 192, width = 573, height = 573 }",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.372 PM",
          "Status": "Helios: A_10C_2_RIGHT_MFCD = { x = 1900, y = 192, width = 573, height = 573 }",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.372 PM",
          "Status": "Helios: A_10C_2_RWR_SCREEN = { x = 788, y = 216, width = 246, height = 246 }",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.372 PM",
          "Status": "Helios: FA_18C_CENTER_MFCD = { x = 907, y = 928, width = 481, height = 456 }",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.372 PM",
          "Status": "Helios: FA_18C_IFEI = { x = 79, y = 1005, width = 698, height = 270 }",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.372 PM",
          "Status": "Helios: FA_18C_LEFT_MFCD = { x = 244, y = 267, width = 519, height = 489 }",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.372 PM",
          "Status": "Helios: FA_18C_RIGHT_MFCD = { x = 1549, y = 267, width = 517, height = 487 }",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.372 PM",
          "Status": "Helios: FA_18C_RWR = { x = 1862, y = 960, width = 240, height = 240 }",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.372 PM",
          "Status": "Helios: FA_18C_UFC = { x = 860, y = 43, width = 606, height = 343 }",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.372 PM",
          "Status": "Monitor at Windows coordinates (0,0) of size 2560x1440 is used for main view",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.372 PM",
          "Status": "Monitor at Windows coordinates (0,0) of size 2560x1440 is used to display the DCS user interface",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.372 PM",
          "Status": "Monitor at Windows coordinates (871,1440) of size 1680x1050 has 3 viewports from this profile",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.372 PM",
          "Status": "MAIN = { x = 0, y = 0, width = 2560, height = 1440 }",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.372 PM",
          "Status": "UI = MAIN",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.372 PM",
          "Status": "monitor setup file 'Helios.lua' in Saved Games\\DCS.openbeta\\Config\\MonitorSetup is up to date",
          "Flags": 2
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.373 PM",
          "Status": "H_f-16bl603mon: F_16C_DED = { x = 1486, y = 1559, width = 153, height = 83 }",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.373 PM",
          "Status": "H_f-16bl603mon: F_16C_LEFT_MFCD = { x = 870, y = 1854, width = 239, height = 252 }",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.373 PM",
          "Status": "H_f-16bl603mon: F_16C_RIGHT_MFCD = { x = 1738, y = 2026, width = 138, height = 83 }",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.373 PM",
          "Status": "monitor setup file 'H_f-16bl603mon.lua' in Saved Games\\DCS.openbeta\\Config\\MonitorSetup is up to date",
          "Flags": 2
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.373 PM",
          "Status": "Saved Games\\DCS.openbeta\\Config\\options.lua has 'Resolution' set to 2560x2520",
          "Flags": 2
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.373 PM",
          "Status": "Saved Games\\DCS.openbeta\\Config\\options.lua has 'Monitors' set to '2_monitors-f16c'",
          "Flags": 2,
          "Recommendation": "Using DCS, please make sure 'Monitors' in the 'System' options is set to 'H_f-16bl603mon'"
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.373 PM",
          "Status": "Saved Games\\DCS.openbeta\\Config\\options.lua has 'Fullscreen' set to False",
          "Flags": 2
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.373 PM",
          "Status": "This profile requires a specific monitor setup file",
          "Flags": 2,
          "Recommendation": "You will need to switch 'Monitors' in DCS when you switch Helios Profile"
        }
      ]
    },
    {
      "Name": "DCS Additional Viewports",
      "Report": [
        {
          "TimeStamp": "09/10/2021 05:06:16.395 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\AN_ALR69V\\indicator\\AN_ALR69V_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.395 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\CDU\\indicator\\CDU_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.395 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\CMSC\\indicator\\CMSC_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.395 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\CMSP\\indicator\\CMSP_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.395 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\DigitalClock\\Indicator\\DIGIT_CLK_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.395 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\MFCD\\indicator\\MFCD_left_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.395 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\MFCD\\indicator\\MFCD_right_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.395 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\UHF_Radio\\indicator\\freq_status_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.395 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\UHF_Radio\\indicator\\preset_channel_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.395 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\UHF_Radio\\indicator\\repeater_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.395 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\AN_ALR69V\\indicator\\AN_ALR69V_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.395 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\CDU\\indicator\\CDU_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.395 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\CMSC\\indicator\\CMSC_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.395 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\CMSP\\indicator\\CMSP_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.395 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\DigitalClock\\Indicator\\DIGIT_CLK_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.396 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\MFCD\\indicator\\MFCD_left_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.396 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\MFCD\\indicator\\MFCD_right_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.396 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\UHF_Radio\\indicator\\freq_status_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.396 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\UHF_Radio\\indicator\\preset_channel_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.396 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\UHF_Radio\\indicator\\repeater_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.396 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\DED\\indicator\\DED_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.396 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\EHSI\\indicator\\EHSI_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.396 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\EHSI\\indicator\\LCD\\EHSI_LCD.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.396 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\MFD\\indicator\\MFD_left_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.396 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\MFD\\indicator\\MFD_right_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.396 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\MFD\\indicator\\LCD\\MFD_LCD.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.396 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\EWS\\RWR\\indicator\\RWR_ALR56_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.396 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\fonts.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.396 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\IFEI\\indicator\\IFEI_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.396 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\Multipurpose_Display_Group\\AMPCD\\indicator\\AMPCD_viewport_cfg.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.396 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\Multipurpose_Display_Group\\AMPCD\\indicator\\BAKE\\AMPCD_bake_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.397 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\Multipurpose_Display_Group\\Common\\indicator\\BAKE\\MPD_common_bake_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.397 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\Multipurpose_Display_Group\\MDI_IP1556A\\indicator\\MDI_left_viewport_cfg.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.397 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\Multipurpose_Display_Group\\MDI_IP1556A\\indicator\\MDI_right_viewport_cfg.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.397 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\TEWS\\indicator\\RWR_ALR67_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.397 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\UFC\\indicator\\UFC_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.397 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\Ka-50\\Cockpit\\Scripts\\ABRIS\\ABRIS_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.397 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\Ka-50\\Cockpit\\Scripts\\ABRIS\\BAKE\\init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.397 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\Ka-50\\Cockpit\\Scripts\\SHKVAL\\SHKVAL_init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.397 PM",
          "Status": "DCS installation in 'F:\\DCS World OpenBeta' has already patched Mods\\aircraft\\Ka-50\\Cockpit\\Scripts\\SHKVAL\\BAKE\\init.lua",
          "Flags": 3
        },
        {
          "TimeStamp": "09/10/2021 05:06:16.397 PM",
          "Status": "Helios is managing DCS viewport patches",
          "Flags": 3,
          "Recommendation": "Do not also install viewport mods manually or via a mod manager like OVGME"
        }
      ]
    }
  ]
}

**Comment by derammo** [comment]
please send any files like these that you have (drag and drop the entire files here)

![image](https://user-images.githubusercontent.com/817160/132890425-f24800a7-6301-4583-88a3-cad37c160508.png)

**Comment by derammo** [comment]
developers:  the "add new interface" thread just stops after logging an exception if the enumeration of interfaces throws.  So if one of the DirectX interfaces throws, for example, that explains why Process Control et alia are not shown.

**Comment by rudek1980** [comment]
[Profile Editor Problems.log](https://github.com/HeliosVirtualCockpit/Helios/files/7147228/Profile.Editor.Problems.log)

**Comment by rudek1980** [comment]
yes its directx

**Comment by rudek1980** [comment]
dx 12 to dx11 didnt solved

**Comment by rudek1980** [comment]
solved by reconection\replacemant usb hubs and cable

**Comment by rudek1980** [comment]
thx for great help and best projects
