### ISSUE TITLE
Monitors, Maps, DCS down and System button color issues in new Ice’s Falcon BMS Profile 4.35-10

### ISSUE THREAD

**Issue by Drichard1458** [HeliosVirtualCockpit/Helios#459]
After install of Helios 1.6.3605.0000 and Ice’s Falcon BMS Profile 4.35-10 (including the new HeliosFalcon.dll), I've noticed four issues that show up now. 
I removed all of my original Helios files and folders and started the install from scratch, per the install instructions. 
I didn't make any change to the stock v. 10 profile, other than adding my Cougar HOTAS bindings at the end.

1. Helios now reports my two monitors incorrectly, as: 
"The monitor arrangement saved in this profile matches this computer"
"The profile declares a monitor of size 2560x1440" - (Windows actually reports the correct 3840x2160 for main monitor 1)
"The profile declares a monitor of size 1280x720" - (Windows actually reports the correct 1920x1080 for "Helios" monitor 2)
I've reset the monitors several times but it's still the same.
2. The MAP button brings up the Korea map OK, but it's a smaller, fuzzy, low resolution version and when you click on it to expand a region, it either opens the wrong close-up view area or returns you to the main Front Console instead of the close-up view.
3. On the ICP, the DCS switch "down", doesn't work. (It works  OK when I mouse click it on the Main screen ICP view)
4. In the System Menu console, the 'Reset Profile', 'Stop Profile' and 'Exit Mission' buttons are not colored  green, red and blue, as shown on the latest BMS thread. The buttons still work fine, but I didn't know if that was a clue to any of this.

Otherwise, everything else works great. 
Any ideas on what might be the problem?
Should I delete everything again and start over?

Thanks!

[Helios_status_report_132772664276722189.txt](https://github.com/HeliosVirtualCockpit/Helios/files/7240292/Helios_status_report_132772664276722189.txt)

**Comment by Todd1215** [comment]
Do you happen to have windows scaling set to anything but 100%.

**Comment by Drichard1458** [comment]
On the main 4k monitor, the Windows screen scaling is set to 150% (Recommended), the Helios monitor is set to 100%.

**Comment by Drichard1458** [comment]
That fixed everything!  It was the 150% scaling setting on the main monitor causing the problem.
You're incredible!
Thank you!
