### ISSUE TITLE
Unhandled Error in System.Xml

### ISSUE THREAD

**Issue by CGQFK** [HeliosVirtualCockpit/Helios#474]
Hi every one. My first issue summited !!!
![Helios error](https://user-images.githubusercontent.com/92748883/137785308-8858ed01-6a6d-4b02-9483-04660190bebd.png)

My HeliosVirtualCockpit was working fine under Win10-PRO. I had to change my hard drive for an SSHD and they put WIN-Entreprise. Reloaded all my stuff, FSX, DCS, Helios etc .... When I open Helios Control Center I receive the message attached.

I looked in the FAQ and saw a similar bug reported but not about System.Xml. On Google I also saw something about Reinstall Win10 and ways to not loose Files and Programs. I did the "scannow" and all that stuff as described in those forums. I afraid to reset that Win10. Does someone has some resolution about this?. 

Be aware I am not computer expert.

Thank you in advance

**Comment by BlueFinBima** [comment]
Hi @CGQFK,  

as best I can tell, you have a corrupt ???.htpl file.  These are Helios templates, typically found in `%userprofile%\Documents\Helios\Templates\`.  With the information you have provided, I cannot tell you which one might be causing the problem.
Putting aside the fact that there should have been code to catch this exception, there is probably more information about this problem in `%userprofile%\Documents\Helios\Control Center.log`.

Cheers,  BlueFin
(note: TemplateManager.cs 124)
