### ISSUE TITLE
P-51Gunsight_on_off is inverted in Helios vs. DCS

### ISSUE THREAD

**Issue by sedunderi** [HeliosVirtualCockpit/Helios#475]
[Helios has written the report to the file 'Helios_status_report_132792136923509560.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]
[Helios_status_report_132792136923509560.txt](https://github.com/HeliosVirtualCockpit/Helios/files/7381990/Helios_status_report_132792136923509560.txt)
![image](https://user-images.githubusercontent.com/92634023/138113713-9bb5fa40-37aa-4e2b-a96d-57834325b8eb.png)
Regardles of what I try the Gunsight on off butten takes an invesred possition in Helios vs DCS

**Comment by BlueFinBima** [comment]
Closing as over a week without update.  Likely / certain to be a profile issue and not a Helios bug.
