### ISSUE TITLE
MFD cannot be hidden

### ISSUE THREAD

**Issue by MagicLoki** [HeliosVirtualCockpit/Helios#480]
I'm configuring my own f18 config, and I found that Viewports cannot be hidden in the game.
I added Left MFCD and Right MFCD on monitor 2, then superimposed AMPCD and UFC on these two windows, and set AMPCD and UFC to be hidden by default, and switch the show and hide of these four screens through 4 switches. Each window is composed of Viewports and an outer frame. After I entered the game, I found that Viewports cannot be hidden. The outer frame can be switched to the hidden state with a button, but Viewports cannot.

**Comment by Todd1215** [comment]
viewports are rendered by DCS. What you configure in Helios Profile Editor for viewports just writes a config to DCS to tell it where the viewport is to be rendered.

**Comment by MagicLoki** [comment]
> viewports are rendered by DCS. What you configure in Helios Profile Editor for viewports just writes a config to DCS to tell it where the viewport is to be rendered.

So there is no way to hide Viewports through Helios, right?
