### ISSUE TITLE
M2000 VTB patch issue

### ISSUE THREAD

**Issue by gordonkatt** [HeliosVirtualCockpit/Helios#489]
[Helios_status_report_132820018009721837.txt](https://github.com/HeliosVirtualCockpit/Helios/files/7577102/Helios_status_report_132820018009721837.txt)

**Comment by TrooperBanshee** [comment]
[Helios_status_report_132820133359732871.txt](https://github.com/HeliosVirtualCockpit/Helios/files/7577438/Helios_status_report_132820133359732871.txt)

**Comment by EXit77** [comment]
Same here. After DCS Update 2.7.8.1614
[Helios_status_report_132822469114663764.txt](https://github.com/HeliosVirtualCockpit/Helios/files/7597557/Helios_status_report_132822469114663764.txt)
0

**Comment by Todd1215** [comment]
@gordonkatt and @EXit77 its very apparent that the M2000 VTB viewport patch is bad. These will have to be fixed, but in the interim you can set the ATB patch for M2000 to manual by unchecking the ones you don't want Helios to manage. In Helios profile goto the Interface tab for DCS Additional Viewports and expand the Details section and find the line for M2000 VTB and uncheck it. That should allow you to install all the other patches for now.

@TrooperBanshee You have excluded some patches 

{
          "timeStamp": "11/22/2021 11:04:45.824 AM",
          "status": "DCS installation in 'E:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' will not patch Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\DED\\indicator\\DED_init.lua because it was excluded from patching by the user"
        },

Also are you manually managing the export file
{
          "timeStamp": "11/22/2021 10:59:21.287 AM",
          "status": "The Helios driver written by the user is not included in this profile, so Helios cannot check if it is installed.",
          "flags": 2,
          "recommendation": "Please manually check that the export module was correctly placed"
        }

**Comment by Todd1215** [comment]
See Discord chat for a workaround for the M2000 viewport issue
https://discord.com/channels/434241908492075010/702224236030197760/911198259593216030

**Comment by pom2ter-git** [comment]
Same problem with this patch and other M2000 patches since combined updates : DCS 2.7.9.18080 and HELIOS 1.6.5101.0

**Comment by pom2ter-git** [comment]
Sorry but when I try your solution, it doesn't work : I check manually the only M2000 patches, except the M2000 VTB one (because of the identified bug).
Then I do a DCS repair, and reapply the selected patches : i'm stuck... (see attached report file)

[Helios_status_report_132858874997874527.txt](https://github.com/HeliosVirtualCockpit/Helios/files/7817588/Helios_status_report_132858874997874527.txt)

**Comment by Todd1215** [comment]
That leaves you with two options, three really. 
1. Figure out how to fix the patch
2. review issue #484 for some additional things people did to resolve it
3. revert back to Helios version 1.6.5013 where this issue doesn't exist.

There are many users running Helios for DCS and have run into this issue and worked around it.

**Comment by pom2ter-git** [comment]
I reverted to Helios version 1.6.5013, but always issues witch PCN_UR and PCN_BR patches

[Helios_status_report_132860616141476439.txt](https://github.com/HeliosVirtualCockpit/Helios/files/7831250/Helios_status_report_132860616141476439.txt)
