### ISSUE TITLE
Unhandled error in mscorlib when adding a new interface

### ISSUE THREAD

**Issue by Binary-System** [HeliosVirtualCockpit/Helios#491]
Fresh installation in Windows 10 pro 64bit  @ current patchlevel

Way to reproduce:
New Profile => Save with name => Menu: Profile => Add Interface

Errors recieved:
```
---------------------------
Unhandled Error in mscorlib
---------------------------
Unhandled exception occurred.  Please file a bug:
Ein Element mit dem gleichen Schlüssel wurde bereits hinzugefügt.
   bei System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)

   bei System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)

   bei GadrocsWorkshop.Helios.Collections.KeyedObservableCollection`2.OnCollectionChanged(NotifyCollectionChangedEventArgs e)

   bei System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)

   bei GadrocsWorkshop.Helios.Interfaces.DirectX.DirectXControllerInterface.AddFunction(DirectXControllerFunction function)

   bei GadrocsWorkshop.Helios.Interfaces.DirectX.DirectXControllerInterface.PopulateFunctions(IList`1 objects)

   bei GadrocsWorkshop.Helios.Interfaces.DirectX.DirectXControllerInterface.set_ControllerId(DirectXControllerGuid value)

   bei GadrocsWorkshop.Helios.Interfaces.DirectX.DirectXControllerInterfaceFactory.GetInterfaceInstances(HeliosInterfaceDescriptor descriptor, HeliosProfile profile)

   bei GadrocsWorkshop.Helios.ProfileEditor.ViewModel.AvailableInterfaces.Start(HeliosProfile profile)

   bei GadrocsWorkshop.Helios.ProfileEditor.MainWindow.AddInterface_Executed(Object sender, ExecutedRoutedEventArgs e)
---------------------------
OK   
---------------------------

```

**Comment by Binary-System** [comment]
Seems to be a duplicate to #485

Problem in case was indeed the USB Device: HID-compliant game controller with the default Microsoft driver.

Specifically this device: "BEYEE Zero Delay Arcade USB Encoder PC to Joystick"

Don't want to post shopping links here but can provide the amazon store link for the item.

**Comment by Binary-System** [comment]
From the error messages. Is it possible that the problem is having 2 identical named USB devices on the system?

**Comment by ereidelbach** [comment]
I just experienced this exact same bug. I have multiple USB devices (a simpit setup) along with two zero delay encoders mentioned above.

When I have time this weekend I'll start unplugging them one by one until I can successfully add an interface, and then start adding them back in until I can identify the problem on my end.

**Comment by Todd1215** [comment]
@ereidelbach did you ever determine which controller was causing the issue?

**Comment by Todd1215** [comment]
See issue #485 for any further correspondence as this is a duplicate report.

**Comment by BlueFinBima** [comment]
@Binary-System Did you have more than one of these boards attached to your system?  Also, was it / were they on an external USB hub?

**Comment by BlueFinBima** [comment]
Working this under #485
