### ISSUE TITLE
Unhandled Error in System.Xml at first run of software

### ISSUE THREAD

**Issue by obrien979** [HeliosVirtualCockpit/Helios#492]
I recently installed the newest version of Helios (v1.6) and encountered an error when I first try to running the software.  I have looked through some of the posts on this forum and seen that many suggested upgrading to the newest NET Framework edition.  I checked that version and I have the most up-to-date version.  So now I am reaching out for some assistance. 
![Helios Error](https://user-images.githubusercontent.com/34754163/145670513-1a7b3cbd-e65a-48fa-a03c-b7bb01e12998.JPG)

**Comment by Todd1215** [comment]
My suggestion is that you attach your profile editor logs to this issue. There are two in Documents\Helios directory. The more details you can add the better support you will get.

**Comment by obrien979** [comment]
@Todd1215 Thanks for the advice. Here are all the Error Logs.

[Control Center.log](https://github.com/HeliosVirtualCockpit/Helios/files/7698453/Control.Center.log)
[Profile Editor Problems.log](https://github.com/HeliosVirtualCockpit/Helios/files/7698454/Profile.Editor.Problems.log)
[Profile Editor.log](https://github.com/HeliosVirtualCockpit/Helios/files/7698455/Profile.Editor.log)
[Control Center Problems.log](https://github.com/HeliosVirtualCockpit/Helios/files/7698456/Control.Center.Problems.log)

**Comment by Todd1215** [comment]
There should be two xml files under documents/helios. It's possible there is some file corruption. Please delete these two files and try open the profile editor again.

**Comment by derammo** [comment]
it is failing to read the Template files, which is wild....  if this is still happening, it is pretty interesting

**Comment by BlueFinBima** [comment]
This issue can be re-opened if more info becomes available.
