### ISSUE TITLE
Need help setting up

### ISSUE THREAD

**Issue by P-inna** [HeliosVirtualCockpit/Helios#493]
Hello,

Well, its probally a noob question but this is my problem;
I fly the F16 Viper in DCS. I use 2 monitors, one main screen and the other i mounted 2 TM MFD's on, So the second screen is devide by two little screens. My Helios profile is really simple, just the left MFD and the right MFD placed on the second screen. (see attachment)
![Helios](https://user-images.githubusercontent.com/96329483/146632229-d709b7f7-9046-4a75-8bdb-7ecb12245067.jpg)

Now, i would like to add the EHSI and the RWR viewport to the second screen and use a key command or specified key to toggle between viewports presented on the secons screen. 

Is this possible and can you explain it to me, or point me to the direction were a help can be find?

Many many thanks in advance!

Pinna

**Comment by Todd1215** [comment]
This is not possible in the way you want to do it. The viewports are rendered by DCS and cannot be hidden or unhidden, but if you take a look at Capt Zeen's A-10 profile you can hide viewports with panels and just unhide the panel which would then display the viewport but you cannot overlap them and switch between them.
