### ISSUE TITLE
Patches not functioning

### ISSUE THREAD

**Issue by Enabler97** [HeliosVirtualCockpit/Helios#499]
Patches are not functioning and viewports have failed since working last night.

**Comment by Enabler97** [comment]
[Helios_status_report_132851225683717109.txt](https://github.com/HeliosVirtualCockpit/Helios/files/7782053/Helios_status_report_132851225683717109.txt)

**Comment by Todd1215** [comment]
Please review issues before you open bugs. This was sky reported in issue #489
