### ISSUE TITLE
M2000 PCN_BR patch issue

### ISSUE THREAD

**Issue by pom2ter-git** [HeliosVirtualCockpit/Helios#500]
[Helios_status_report_132854970317753319.txt](https://github.com/HeliosVirtualCockpit/Helios/files/7797467/Helios_status_report_132854970317753319.txt)

**Comment by Todd1215** [comment]
This is a known issue. See issue #489 . Quick fix is to do a DCS repair and reapply the patches.

**Comment by pom2ter-git** [comment]
Sorry but when I try it, it doesn't work : I check manually the only M2000 patches, except the M2000 VTB one (because of the identified bug).
Then I do a DCS repair, and reapply the selected patches : i'm stuck... (see attached report file)

[Helios_status_report_132858874997874527.txt](https://github.com/HeliosVirtualCockpit/Helios/files/7817564/Helios_status_report_132858874997874527.txt)
)
