### ISSUE TITLE
HELP:- I cannot get HELIOS to work with a "Slave" Network PC

### ISSUE THREAD

**Issue by JBlyth** [HeliosVirtualCockpit/Helios#505]
I have spent many many hours trying to get Helios working from a second “Slave” PC to my primary “Server” PC, which has two high resolution 32 inch monitors. My Slave PC is a Surface Pro 7, with both PCs running Windows 11 and on the same update patches.

I can confirm that:-
1.	The Server PC can see the Slave PC on the network, and vice versa. Both have fixed IP addresses set on my router.
2.	The Server PC’s Helios Profile is correctly set to the Slave PC’s IP address in the \Saved Games\DCS\Scripts\Helios\HeliosExport16.lua file, and the ports match.
3.	I have disconnected the Documents\Helios folder from OneDrive to ensure the profiles are completely separate (I also had the same issues as mentioned below when they had a shared folder across OneDrive)
4.	I have installed the Capt Zeem F16 data and set it up on both the Server and Slave PCs.
5.	I copied the successful Helios F16 Profile from the Server PC to the Slave PC.
6.	I have run the copied profile on the Slave PC, and adjusted the Monitor Settings to suit.
7.	I am using the Stable Release of DCS

Issues:-
•	The profile works perfectly on the Server PC but…..
•	On the Slave (Second) PC, as soon as I change the “Location” on the Slave PC to “This computer is a remote Helios Computer, not the one running DCS”, I get a warning on the DSC Additional Viewports and DCS Monitor Setup panels in red “You must configure DCS installation locations before configuring monitor setup”.
•	I cannot see a way of resolving those error messages.

Does anyone have a solution or suggestion? I am tearing out what little hair I have left! The images below are screenshots from my Surface 7.

Many thanks
John in Sunny Carnarvon – Western Australia

![noname](https://user-images.githubusercontent.com/30167537/148378064-0a75ca6b-3090-45f4-be2e-7ecc77bd6f17.png)

![noname 2](https://user-images.githubusercontent.com/30167537/148378082-fc694692-7a0a-466f-9574-f7b27a441bd8.png)

**Comment by Todd1215** [comment]
Have you reviewed this wiki article https://github.com/HeliosVirtualCockpit/Helios/wiki/Running-Helios-Control-Center-Remotely

remote PC will look for the Server PC on UDP port 9089 (default). So the Server PC needs to be running the profile in Control Center before you can try and setup the Remote PC.

**Comment by JBlyth** [comment]
Thanks Todd. Yes, I had looked at that a number of times, but it looked as if there was still some info to come as the dot points from "Different monitor configurations" on hadn't been completed. I did follow all the steps mentioned earlier in that post.

I have used the default ports. I copied the Server Profile to the Slave PC, and tried to edit it. I reset the Monitor settings to the Slave screen size, but as soon as I select "This is a remote...." on the Slave, I get the red error message with no apparent means of correcting it.

I'm not sure if it matters, but I am running the F16 Capt Zeen install on both PCs. I seem to lose Instrument clicks and switch linkages between the Server and DCS when I update the Profile on the Server to the Slave's IP address - but I sort of expected that to happen as I would have thought the Server would have been listening to the Slave for those functions after that update (maybe).

A completely clean install of the F16 Capt Zeen Profile on the Slave appeared to give the same error message.

Any further suggestions would be most welcome. It would be wonderful to be able to have my touch screen Surface 7 working as a Slave.....

Cheers
John

**Comment by Todd1215** [comment]
So your client is not another PC but a MS Tablet. I think your best bet is to try and extend the desktop of the PC where Helios and DCS is running to the Surface 7. I don't have a Surface device to test but it seems like others are doing it judging by this article on MS site.

https://answers.microsoft.com/en-us/surface/forum/all/use-surface-pro-7-as-second-monitor-for-desktop-pc/c4c0784f-b27c-4ec7-9f95-a20bf02ea35c

**Comment by JBlyth** [comment]
Thanks again Todd. The screen "Casting" (Windows 11 parlance) does indeed work, but it kills the frame rate by 50-60%. :-(

If you are using a remote PC with Helios, could you see in the cmd command (with admin privileges) netstat -aon shows anything for port 9098 on your Server and Slave devices please. It seems to me that the UDP ports on my devices are not providing the required connectivity.

Of if you know of a best way to test, I would be delight to try anything!

Many thanks
John

**Comment by Todd1215** [comment]
The default udp port is 9089. Was that a typo on your part or are you using port 9098 instead?

**Comment by Todd1215** [comment]
See issue #366 for additional info and some basic guidance on network setup.

**Comment by JBlyth** [comment]
Thanks Tom. Yes, most definitely a typo on my part. I am using the default ports. I had reviewed #366, and complied with all its suggestions, but sadly for some reason I just cannot get the Slave PC Profile to setup properly.

I copied the Server Profile across after having set up the Slave IP in the server setup, and that is reflected in the IP and port in the .lua as expected and described, so I am at a loss at this point. My router has UPnP turned on and every other device I have works fine, included Virtual Serial Ports for another simulator (Condor 2) to send data between the same devices.

I don't know if it is to do with Windows 11. I can confirm that the Surface 7 has the Control Centre software in it's firewall exceptions. The Microsoft Surface Pro 7 is just a standard Windows 11 device - nothing special in it's OS - or at least would have thought so, as is my Gigabyte Gaming laptop.....

Do you have any ideas on how to test that the UPnP ports are actually available/open? 

Many thanks yet again for your help,
John

**Comment by Todd1215** [comment]
You could install Wireshark and inspect the UDP traffic from the server to the client. I'd run it on the Server to ensure the UDP packets are being sent

**Comment by JBlyth** [comment]
Hi Todd. Sorry to be slow in replying. I'm away from home at the moment. However, I have been playing, and I can get DCS to talk to my Android phone via the network using the DCS Tensor Cockpit app, so I tend to think the issue is more the setup of Helios on the remote Windows 11 laptop rather than anything else.

Is there anything else I need to copy across to the remote PC other than setting up the Captain Zeen Profile? Perhaps parts of the Saved Games/DCS folder from the Server PC?

I just can't seem to find a way of getting around the "You must configure DCS locations before ..... " error messages on the remote laptop in the Helios editor as mentioned in earlier posts......

It's bound to be something very small - but elusive ;-)

Cheers
John

**Comment by JBlyth** [comment]
PS.

I have also tried a Helios profile that I made from scratch with just a single MFD in it. I still got exactly the same error messages on the Remote PC, even though I had removed the older scripts.

A different network made no difference either....

**Comment by JBlyth** [comment]
I have made a small breakthrough. I found if I deleted the "DCS Additional Viewports" interface from the Captain Zeen F16 profile, the error messages went away..... BUT, then the viewports did not appear on the remote computer.

Is there a need to use IRIS to scrape the server PC screen (which is mentioned in the incomplete Wiki page) and if so, does it work with Windows 11 and where can I find it?

It all seems to be incredibly complicated and undocumented. However, having said that, HELIOS is a fantastic tool for DCS.

Cheers
John

**Comment by Todd1215** [comment]
@JBlyth yes unfortunately the documentation regarding a network setup is sparse to say the least. Since DCS is not capable of doing the exporting of viewports to another PC on its own it requires a separate tool, that being the IRIS screen exporter. I think most DCS users are all on one PC these days rather than separate ones which is why you don't see much info on this subject. Any networking of programs is complicated and typically not for the lighthearted. Keep at it and you'll get it.

By the way, I'm no DCS export nor do I do any Helios coding for DCS which is why I'm not that much help. If you do get it to work please help the next guy and document those steps you took to get it setup. We are a community and should help each other when we can.

**Comment by JBlyth** [comment]
Thanks Todd1215 - in the end I gave up with networking Helios and have lashed out on a 15 inch touch screen monitor.

This is much easier to setup, and it works a treat!

Cheers
John

**Comment by BlueFinBima** [comment]
Hi @JBlyth,  If you (or anyone else) revisits this, the following might help.  

I've been away from the Helios world so I only caught this in a catch-up.  The video pre-dates the Helios Viewport interface, but it essentially remains true as an overview [Overview of the Helios Virtual Cockpit System for DCS](https://www.youtube.com/watch?v=78to_NENQT8).
If you'd configured the UDP correctly, then the only thing I can think of would be Windows firewall.  There is another video [Trouble Shooting Helios Part 1](https://www.youtube.com/watch?v=LgsVZfRI6q4) which might also help.  What you were attempting to do certainly works, and I have used 10inch Windows tablets for MFDs, as well as traditional "remote" Helios profiles.
