### ISSUE TITLE
allof this needs to be simplified for happier user this only ads to the frustration of new users to dcs

### ISSUE THREAD

**Issue by flyguychrisw** [HeliosVirtualCockpit/Helios#506]
allof this needs to be simplified for happier user this only ads to the frustration of new users to dcs

_Originally posted by @flyguychrisw in https://github.com/HeliosVirtualCockpit/Helios/issues/361#issuecomment-1008060999_

**Comment by Todd1215** [comment]
The issues section is for reporting problems not complaining. If you have coding skills then pitch in.
