### ISSUE TITLE
no setup

### ISSUE THREAD

**Issue by flyguychrisw** [HeliosVirtualCockpit/Helios#507]
[Helios has written the report to the file 'Helios_status_report_132861612548447103.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

**Comment by Todd1215** [comment]
You are suppose to describe your problem in the description area of the github issue. If you don't i can't even begin to try and help you.

Putting 'no setup' as the title tells us nothing about your issue. Helios is a platform for creation profiles for both DCS and Falcon BMS. While some profiles are very good they are not however plug and play. If you are having an issue with a particular profile my suggestion is to go to the author and present your issue to then.

**Comment by Todd1215** [comment]
opening an issue without describing what your problem is, is not helpful
