### ISSUE TITLE
DCS PROBLEM

### ISSUE THREAD

**Issue by Geokat92** [HeliosVirtualCockpit/Helios#508]
[Helios has written the report to the file 'Helios_status_report_132861999972030816.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem 
[Helios_status_report_132861999972030816.txt](https://github.com/HeliosVirtualCockpit/Helios/files/7834915/Helios_status_report_132861999972030816.txt)
y

**Comment by Todd1215** [comment]
You are suppose to describe your problem in the description area of the github issue. If you don't i can't even begin to try and help you.

**Comment by Geokat92** [comment]
After the last update of dcs, helios does not work properly with the game.
Obviously you have to do the necessary actions (update) in a new version in order for the two programs to work together ..

    Στις Κυριακή, 9 Ιανουαρίου 2022, 02:40:53 μ.μ. EET, ο χρήστης wheelchock ***@***.***> έγραψε:  
 
 


You are suppose to describe your problem in the description area of the github issue. If you don't i can't even begin to try and help you.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Todd1215** [comment]
Dcs is constantly updating. For modules that are not completed it's very difficult to keep pace with their updates. With that said you still have not provided any specifics about your issue. Is there a specific issue or a general complaint?

**Comment by Geokat92** [comment]
The problem it presents is in the extract of monitor 2, it does not recognize it and this results in not being able to see the content ..


    Στις Κυριακή, 9 Ιανουαρίου 2022, 03:08:44 μ.μ. EET, ο χρήστης wheelchock ***@***.***> έγραψε:  
 
 


Dcs is constantly updating. For modules that are not completed it's very difficult to keep pace with their updates. With that said you still have not provided any specifics about your issue. Is there a specific issue or a general complaint?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Todd1215** [comment]
This message appears in your log file

{
          "timeStamp": "01/09/2022 01:06:02.543 PM",
          "severity": 1,
          "status": "One or more DCS viewports are masked by a monitor with a fill background. The result is you won't see the DCS viewports being rendered to the monitor.",
          "recommendation": "Review your profile and ensure monitors do not have Fill Background enabled when a viewport is configured for that monitor"
        }


Which means that the monitor where the viewports are being rendered has a background color masking where the viewport would/should be. Follow the recommendations of Helios that is in the log file: 

Review your profile and ensure monitors do not have Fill Background enabled when a viewport is configured for that monitor
