### ISSUE TITLE
DCS PROBLEM

### ISSUE THREAD

**Issue by Geokat92** [HeliosVirtualCockpit/Helios#509]
[Helios has written the report to the file 'Helios_status_report_132862001609075519.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

[Helios_status_report_132862001609075519.txt](https://github.com/HeliosVirtualCockpit/Helios/files/7834917/Helios_status_report_132862001609075519.txt)

**Comment by Todd1215** [comment]
You are suppose to describe your problem in the description area of the github issue. If you don't i can't even begin to try and help you.
