### ISSUE TITLE
Helios keeps converting screen size to smaller size

### ISSUE THREAD

**Issue by jangaloo** [HeliosVirtualCockpit/Helios#511]
Hello!

I´ve looked through the forum but have not come across anything.  Hope someone can help as I've spent nearly 2 days trying to get this to work.

I have a T setup with 3 - 3840 x 2160 screens and a 1920x1080. I have set all the DPI to 100% as mentioned elsewhere but even though all the relevant files seem to be showing 3840x2160 the end product of my 3 main screens keeps being displayed at what looks to be 2560x1440 or somewhere along the lines of. I read on another thread here that a bug was found in 2020 regarding something similar where Helios keeps converting the resolution to something smaller.  Kind of frustrating to say the least. By the way - the Captain Zeen FaA 18 profile I'm trying to use displays everything correctly and in the correct place on the 1920x1080 screen. 

Attached is a screen shot. I have deinstalled Helios and tried to wipe all files and reinstalled twice but to no avail. I have even installed the DCS beta version just to be sure. Also I can use the 3 screen profile from DCS and it displays correctly.

Please can someone help.

Many thanks
![Helios Screenshot](https://user-images.githubusercontent.com/97736023/149513204-55094b80-8fac-4d7e-ac12-ccca1f67500d.jpg)
!

**Comment by Todd1215** [comment]
Please open your profile in profile editor and goto the Interface Status tab and select share report button to the right of the interface status area, then select the Copy to Clipboard button in the popup window that opens. Paste that into the comments section of this issue. If you are having difficulties with sharing the status report you can follow this video for a more indepth explaination. [Video](https://www.youtube.com/watch?v=yC3qXhWaPiw&list=PLCiL8SHubzhyPA38GyeyL2TCLlKjhtLz6&index=3)

**Comment by jangaloo** [comment]
Todd1215 many thanks for responding! Attached as requested.

{
  "product": "Helios",
  "version": "1.6.5101.0",
  "items": [
    {
      "name": "Profile Interface",
      "report": [
        {
          "timeStamp": "01/15/2022 12:26:38.271 AM",
          "status": "Profile is '%USERPROFILE%\\Documents\\Helios\\Profiles\\FA-18C_V3.1b.hpf'",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:26:38.272 AM",
          "status": "The monitor arrangement saved in this profile matches this computer",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:26:38.272 AM",
          "status": "The profile declares a monitor of size 3840x2160 at (-3840, 0)",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:26:38.272 AM",
          "status": "The profile declares a monitor of size 3840x2160 at (0, 0)",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:26:38.272 AM",
          "status": "The profile declares a monitor of size 1920x1080 at (910, 2160)",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:26:38.272 AM",
          "status": "The profile declares a monitor of size 3840x2160 at (3840, 0)",
          "flags": 3
        }
      ]
    },
    {
      "name": "Keyboard",
      "report": []
    },
    {
      "name": "DCS A10C impersonating FA-18C_hornet",
      "report": [
        {
          "timeStamp": "01/15/2022 12:26:35.766 AM",
          "status": "DCS version 2.7.9.18080 installed at 'K:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' with Saved Games at '%USERPROFILE%\\Saved Games\\DCS.openbeta'",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:26:35.767 AM",
          "status": "Export scripts location for DCS.openbeta exists",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:26:35.769 AM",
          "status": "Export.lua stub for DCS.openbeta calls HeliosExport16.lua",
          "flags": 2
        },
        {
          "timeStamp": "01/15/2022 12:26:35.773 AM",
          "status": "The configured DCS export script at '%USERPROFILE%\\Saved Games\\DCS.openbeta\\Scripts\\Helios\\HeliosExport16.lua' is up to date",
          "flags": 2
        },
        {
          "timeStamp": "01/15/2022 12:26:35.779 AM",
          "status": "The export module provided by Capt Zeen (Version 1) at '%USERPROFILE%\\Saved Games\\DCS.openbeta\\Scripts\\Helios\\Mods\\Helios_F18C.lua' is up to date",
          "flags": 2
        }
      ]
    },
    {
      "name": "Thrustmaster Combined",
      "report": []
    },
    {
      "name": "DCS Monitor Setup",
      "report": [
        {
          "timeStamp": "01/15/2022 12:27:57.080 AM",
          "status": "Windows reports a scaling value of 100% (96 dpi)",
          "flags": 3,
          "recommendation": "This version of Helios does not support using different display scaling (DPI) on different monitors.  Make sure you use the same scaling value for all displays."
        },
        {
          "timeStamp": "01/15/2022 12:27:57.081 AM",
          "status": "viewport 'FA_18C_LEFT_MFCD' is provided by 'DCS Additional Viewports'",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:27:57.081 AM",
          "status": "viewport 'FA_18C_RIGHT_MFCD' is provided by 'DCS Additional Viewports'",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:27:57.081 AM",
          "status": "viewport 'FA_18C_CENTER_MFCD' is provided by 'DCS Additional Viewports'",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:27:57.081 AM",
          "status": "viewport 'FA_18C_RWR' is provided by 'DCS Additional Viewports'",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:27:57.081 AM",
          "status": "viewport 'FA_18C_IFEI' is provided by 'DCS Additional Viewports'",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:27:57.081 AM",
          "status": "viewport 'FA_18C_UFC' is provided by 'DCS Additional Viewports'",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:27:57.082 AM",
          "status": "Helios: FA_18C_CENTER_MFCD = { x = 5527, y = 2856, width = 363, height = 344 }",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:27:57.082 AM",
          "status": "Helios: FA_18C_IFEI = { x = 4903, y = 2913, width = 526, height = 205 }",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:27:57.082 AM",
          "status": "Helios: FA_18C_LEFT_MFCD = { x = 5029, y = 2360, width = 391, height = 369 }",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:27:57.082 AM",
          "status": "Helios: FA_18C_RIGHT_MFCD = { x = 6008, y = 2360, width = 389, height = 367 }",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:27:57.082 AM",
          "status": "Helios: FA_18C_RWR = { x = 6242, y = 2880, width = 182, height = 182 }",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:27:57.082 AM",
          "status": "Helios: FA_18C_UFC = { x = 5490, y = 2191, width = 457, height = 259 }",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:27:57.082 AM",
          "status": "Monitor at Windows coordinates (-3840,0) of size 3840x2160 is used for main view",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:27:57.082 AM",
          "status": "Monitor at Windows coordinates (0,0) of size 3840x2160 is used for main view",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:27:57.082 AM",
          "status": "Monitor at Windows coordinates (910,2160) of size 1920x1080 has 6 viewports from this profile",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:27:57.082 AM",
          "status": "Monitor at Windows coordinates (3840,0) of size 3840x2160 is used for main view",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:27:57.082 AM",
          "status": "Monitor at Windows coordinates (3840,0) of size 3840x2160 is used to display the DCS user interface",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:27:57.082 AM",
          "status": "MAIN = { x = 0, y = 0, width = 11520, height = 2160 }",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:27:57.082 AM",
          "status": "UI = { x = 7680, y = 0, width = 3840, height = 2160 }",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:27:57.082 AM",
          "status": "monitor setup file 'Helios.lua' in Saved Games\\DCS.openbeta\\Config\\MonitorSetup is up to date",
          "flags": 2
        },
        {
          "timeStamp": "01/15/2022 12:27:57.083 AM",
          "status": "Saved Games\\DCS.openbeta\\Config\\options.lua has 'Resolution' set to 11520x3240",
          "flags": 2
        },
        {
          "timeStamp": "01/15/2022 12:27:57.083 AM",
          "status": "Saved Games\\DCS.openbeta\\Config\\options.lua has 'Monitors' set to 'helios'",
          "flags": 2
        },
        {
          "timeStamp": "01/15/2022 12:27:57.083 AM",
          "status": "Saved Games\\DCS.openbeta\\Config\\options.lua has 'Fullscreen' set to False",
          "flags": 2
        }
      ]
    },
    {
      "name": "DCS Additional Viewports",
      "report": [
        {
          "timeStamp": "01/15/2022 12:26:35.796 AM",
          "status": "DCS installation in 'K:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\IFEI\\indicator\\IFEI_init.lua",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:26:35.796 AM",
          "status": "DCS installation in 'K:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\Multipurpose_Display_Group\\AMPCD\\indicator\\AMPCD_viewport_cfg.lua",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:26:35.796 AM",
          "status": "DCS installation in 'K:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\Multipurpose_Display_Group\\HUD_AVQ32\\indicator\\AVQ32_init.lua",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:26:35.796 AM",
          "status": "DCS installation in 'K:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\Multipurpose_Display_Group\\MDI_IP1556A\\indicator\\MDI_left_viewport_cfg.lua",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:26:35.796 AM",
          "status": "DCS installation in 'K:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\Multipurpose_Display_Group\\MDI_IP1556A\\indicator\\MDI_right_viewport_cfg.lua",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:26:35.796 AM",
          "status": "DCS installation in 'K:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\TEWS\\indicator\\RWR_ALR67_init.lua",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:26:35.797 AM",
          "status": "DCS installation in 'K:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' has already patched Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\UFC\\indicator\\UFC_init.lua",
          "flags": 3
        },
        {
          "timeStamp": "01/15/2022 12:26:35.797 AM",
          "status": "Helios is managing DCS viewport patches",
          "flags": 3,
          "recommendation": "Do not also install viewport mods manually or via a mod manager like OVGME"
        }
      ]
    }
  ]
}

**Comment by Todd1215** [comment]
When you arrange them manually and it works how are you arranging them? Can you post the monitor setup file you use for that?

**Comment by jangaloo** [comment]
_  = function(p) return p end
name = _('Helios')
description = 'Generated from compatible Helios Profiles'
FA_18C_CENTER_MFCD = { x = 5527, y = 2856, width = 363, height = 344 }
FA_18C_IFEI = { x = 4903, y = 2913, width = 526, height = 205 }
FA_18C_LEFT_MFCD = { x = 5029, y = 2360, width = 391, height = 369 }
FA_18C_RIGHT_MFCD = { x = 6008, y = 2360, width = 389, height = 367 }
FA_18C_RWR = { x = 6242, y = 2880, width = 182, height = 182 }
FA_18C_UFC = { x = 5490, y = 2191, width = 457, height = 259 }
Viewports = 
{
     Left = 
     {
          x = 0;
          y = 0;
          width = 3840;
          height = 2160;
          viewDx = -1;
          viewDy = 0;
          aspect = 2.37037037038;
     },

     Center = 
     {
          x = 3840;
          y = 0;
          width = 3840;
          height = 2160;
          viewDx = 0;
          viewDy = 0;
          aspect = 2.37037037038;
     },

     Right = 
     {
          x = 7680;
          y = 0;
          width = 7680;
          height = 2160;
          viewDx = 1;
          viewDy = 0;
          aspect = 2.37037037038;
     }
}
UI = { x = 7680, y = 0, width = 3840, height = 2160 }
UIMainView = UI
GU_MAIN_VIEWPORT = Viewports.Center

**Comment by jangaloo** [comment]
I fiddled a bit and came up with the above monitor setup It kind of works for now but the aspect/FOV seems a bit off compared to the standard/provided 3 screen setup file. So I have to adjust the view so to look up and move the view down a bit. 

Appreciate your help.

**Comment by Todd1215** [comment]
Dcs wants a horizontal layout that starts from the left at 0,0 and grows to the right. Your windows layout seems to have a T configuration. Not sure if that is the issue. Maybe try logically arranging the monitors horizontally.

**Comment by Todd1215** [comment]
Maybe this video will help you figure it out. https://youtu.be/ioC2TlrWYH8

**Comment by jangaloo** [comment]
Thanks for your reply.

I tried it horizontaly but got the same result... really strange...

**Comment by jangaloo** [comment]
So I tried today again to set it up as I had not tried it since changing all screens to 100%. Same result. Tried Horizontally as well as From top left corner with my Instrument screen arranged horizontally as was suggested.  I watched the video and that says it should work From top left corner or Horizontally. Attached is a copy of my monitor setup script...
 Any other ideas?

_  = function(p) return p end
name = _('Helios')
description = 'Generated from compatible Helios Profiles'
FA_18C_CENTER_MFCD = { x = 12297, y = 1770, width = 363, height = 343 }
FA_18C_IFEI = { x = 11673, y = 1827, width = 525, height = 204 }
FA_18C_LEFT_MFCD = { x = 11799, y = 1273, width = 390, height = 369 }
FA_18C_RIGHT_MFCD = { x = 12777, y = 1273, width = 388, height = 366 }
FA_18C_RWR = { x = 13011, y = 1794, width = 181, height = 181 }
FA_18C_UFC = { x = 12259, y = 1104, width = 456, height = 258 }
Viewports = {
  Center = {
    x = 0,
    y = 0,
    width = 11520,
    height = 2160,
    aspect = 5.33333333333333,
    dx = 0,
    dy = 0
  }
}
UI = { x = 3840, y = 0, width = 3840, height = 2160 }
UIMainView = UI
GU_MAIN_VIEWPORT = Viewports.Center

**Comment by jangaloo** [comment]
Another finding is that even selecting the UI to be spread over the 3 main screens returns the same result. The UI shows across the left and centre and screen and only a small part of the right screen. The same as when the aircraft has loaded.....

**Comment by jangaloo** [comment]
So only solution I found is to download flyelise 30 day free Imersive LCD  Pro and sort things out from there as I already did to setup my screens in P3D. Now I have everything working correctly. Must be some bug in Helios?

**Comment by Todd1215** [comment]
Since you seem to be the only one experiencing this i will chalk it up to your setup.
