### ISSUE TITLE
Helios export- latest dcs openbeta + helios

### ISSUE THREAD

**Issue by hreich11** [HeliosVirtualCockpit/Helios#519]
[Helios has written the report to the file 'Helios_status_report_132880002662502987.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]
[Helios_status_report_132880002662502987.txt](https://github.com/HeliosVirtualCockpit/Helios/files/7965478/Helios_status_report_132880002662502987.txt)

**Comment by Todd1215** [comment]
commit # 7126631cd01686bb364f92cfd904b1a885c6cd28 fixes viewport issue
