### ISSUE TITLE
Patches to install additional viewports are not compatible with this version.

### ISSUE THREAD

**Issue by EvilAnimal** [HeliosVirtualCockpit/Helios#536]
Error in DCS Additional Viewports for F/A18. "The patches to install additional viewports are not compatible with this version of DCS"

I updated DCS and I've downloaded the latest version of Helios today?

{
  "product": "Helios",
  "version": "1.6.5101.0",
  "items": [
    {
      "report": [
        {
          "timeStamp": "02/16/2022 09:32:36.421 PM",
          "status": "Helios viewport patches installation would fail"
        },
        {
          "timeStamp": "02/16/2022 09:32:36.421 PM",
          "status": "Some patches would fail to apply.  No patches have been applied."
        },
        {
          "timeStamp": "02/16/2022 09:32:32.657 PM",
          "severity": 2,
          "status": "DCS installation in 'X:\\Eagle Dynamics\\DCS World OpenBeta256' failed to apply patch to Mods\\aircraft\\M-2000C\\Cockpit\\VTB\\VTB_init.lua: CONTENT_NOT_FOUND\r\nThe patch could not locate the expected content section (searching near character 1478):",
          "code": [
            {
              "text": "iewport(\"RIGHT_M",
              "lineEnding": 0
            }
          ]
        },
        {
          "timeStamp": "02/16/2022 09:32:32.658 PM",
          "severity": 2,
          "status": "DCS 2.7.10.19473 could not be patched using version 002_007_00006_13436_00000 of the patches.  You may need a newer distribution of Helios or of the patches.",
          "recommendation": "Please make sure you do not have viewport mods installed and run a DCS Repair (slow mode) to clean up DCS."
        }
      ],
      "name": "Configuration Results"
    }
  ]
}

**Comment by Todd1215** [comment]
This is a duplicate issue. Please review list of issues before posting a new issue

**Comment by EvilAnimal** [comment]
I was unable to find anything that helped me fix the problem . . .
