### ISSUE TITLE
COMM1 and Comm 2 pushable knobs not working

### ISSUE THREAD

**Issue by derammo** [HeliosVirtualCockpit/Helios#54]
* created by @BlueFinBima on 2018-06-16 13:03:08 +0000 UTC

### comment by @BlueFinBima on 2018-06-20 11:15:41 +0000 UTC

reverted to an overlay pushbutton.  I'm not going to fix this for the AV-8B beta.  It can stay on the backlog.

### comment by @BlueFinBima on 2018-06-26 19:55:07 +0000 UTC

Went for a kludge solution

### please make sure to close upstream issue when this item is closed

**Comment by BlueFinBima** [comment]
Tested with 1.6.611 and DCS 2.9.8.1214 and the problem appears to have been resolved.
