### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by cosmo238977** [HeliosVirtualCockpit/Helios#541]
[Helios has written the report to the file 'Helios_status_report_132911111047823184.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]
[Helios_status_report_132911111047823184.txt](https://github.com/HeliosVirtualCockpit/Helios/files/8195590/Helios_status_report_132911111047823184.txt)

**Comment by Todd1215** [comment]
the recommendation to fix your issue is in the text file you uploaded. Was there some other problem you had? If you want a response on these issue you need to also give us some idea as to what the problem is.

```
"timeStamp": "03/07/2022 04:58:16.829 PM",
          "severity": 2,
          "status": "current profile specifies using combined monitor setup, but its own viewports are not included",
          "recommendation": "Configure DCS Monitor Setup and save the Profile to repair corrupted configuration"
```
