### ISSUE TITLE
4-Way Switch?

### ISSUE THREAD

**Issue by MedievalBunny** [HeliosVirtualCockpit/Helios#547]
I can't seem to get the 4-Way Switch object to work correctly. It seems to work alright when right-click testing it in the profile editor, but once it's active on the screen I can't get more then two directions to work with either my finger or the mouse, even if I make it comically big. 

Is there some trick I'm missing, or is it just weird?

**Comment by Todd1215** [comment]
Sounds like you're using windows scaling and your monitors are using different scaling values. It's that or you need to calibrate your touch monitor.

**Comment by MedievalBunny** [comment]
Windows scaling was it! Thanks!!

It would be nice if it could use swipe interaction like the other switches. But it works for me now, that's great!
