### ISSUE TITLE
First time bug; Helios suddenly not working.  Both editor and control centre.

### ISSUE THREAD

**Issue by aspiteri9** [HeliosVirtualCockpit/Helios#549]
[Helios has written the report to the file 'Helios_status_report_132932377330722982.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]
[Helios_status_report_132932377330722982.txt](https://github.com/HeliosVirtualCockpit/Helios/files/8393307/Helios_status_report_132932377330722982.txt)

Thankyou

**Comment by Todd1215** [comment]
Helios is not able to resolve GitHub.com address. 


          "recommendation": "An exception was thrown: 'The remote name could not be resolved: 'github.com''.  You should file a bug."

Your issue is local to your pc.

**Comment by aspiteri9** [comment]
Ok thanks.

Will investigate further.....

Regards
Adrian Spiteri
+61 403 283 949
***@***.***
