### ISSUE TITLE
cant install patch

### ISSUE THREAD

**Issue by periand** [HeliosVirtualCockpit/Helios#553]
[Helios has written the report to the file 'Helios_status_report_132957803507608587.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]
[Helios_status_report_132957803507608587.txt](https://github.com/HeliosVirtualCockpit/Helios/files/8596430/Helios_status_report_132957803507608587.txt)

**Comment by derammo** [comment]
no problem description was provided

**Comment by BlueFinBima** [comment]
If this is still a problem, please see https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help and https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help-with-Helios-Software
