### ISSUE TITLE
No viewport patches compatible with DCS 2.5.5.41371 found

### ISSUE THREAD

**Issue by eidev1** [HeliosVirtualCockpit/Helios#554]
HOW to fix this problem? 

{
  "product": "Helios",
  "version": "1.6.5200.1",
  "items": [
    {
      "report": [
        {
          "timeStamp": "05/08/2022 03:46:08.648 PM",
          "status": "Helios 1.6.5200.0001\nhttps://github.com/HeliosVirtualCockpit/Helios/"
        },
        {
          "timeStamp": "05/08/2022 03:46:15.181 PM",
          "status": "Loading Profile..."
        },
        {
          "timeStamp": "05/08/2022 03:46:15.728 PM",
          "status": "Generated Export.lua stub is up to date for DCS",
          "flags": 2
        },
        {
          "timeStamp": "05/08/2022 03:46:15.728 PM",
          "status": "The configured DCS export script at '%USERPROFILE%\\Saved Games\\DCS\\Scripts\\Helios\\HeliosExport16.lua' is up to date",
          "flags": 2
        },
        {
          "timeStamp": "05/08/2022 03:46:15.728 PM",
          "status": "The Helios driver generated by this interface at '%USERPROFILE%\\Saved Games\\DCS\\Scripts\\Helios\\Drivers\\FA-18C_hornet.lua' is up to date",
          "flags": 2
        },
        {
          "timeStamp": "05/08/2022 03:46:15.790 PM",
          "status": "monitor setup file 'Helios.lua' in Saved Games\\DCS\\Config\\MonitorSetup is up to date",
          "flags": 2
        },
        {
          "timeStamp": "05/08/2022 03:46:15.822 PM",
          "status": "Saved Games\\DCS\\Config\\options.lua has 'Resolution' set to 4480x1440",
          "flags": 2
        },
        {
          "timeStamp": "05/08/2022 03:46:15.822 PM",
          "status": "Saved Games\\DCS\\Config\\options.lua has 'Monitors' set to 'helios'",
          "flags": 2
        },
        {
          "timeStamp": "05/08/2022 03:46:15.822 PM",
          "status": "Saved Games\\DCS\\Config\\options.lua has 'Fullscreen' set to False",
          "flags": 2
        },
        {
          "timeStamp": "05/08/2022 03:46:15.822 PM",
          "severity": 2,
          "status": "No viewport patches compatible with DCS 2.5.5.41371 found",
          "recommendation": "Please reinstall Helios to install these patches or provide them in documents folder"
        },
        {
          "timeStamp": "05/08/2022 03:46:15.822 PM",
          "severity": 2,
          "status": "Failed preflight check.",
          "recommendation": "Please resolve problems or disable preflight check in preferences."
        }
      ],
      "name": "Control Center Console"
    }
  ]
}

**Comment by eidev1** [comment]
I have fixed this problem already..
go to the path :  \Helios\Plugins\Patches\DCS
duplicate the folde "002_005_00006_49798_00000",
rename it to 002_005_00005_41371_00000

**Comment by BlueFinBima** [comment]
Quick question, 2.5.5.41371 released in December 2019.  I'm interested to understand if there is something blocking you from moving to a more recent stable level.

**Comment by eidev1** [comment]
> 

aha ，just for test....

**Comment by eidev1** [comment]
> Quick question, 2.5.5.41371 released in December 2019. I'm interested to understand if there is something blocking you from moving to a more recent stable level.

aha ，just for test....
