### ISSUE TITLE
Issues With Patches While Trying to Configure F/C18C Dual Monitor Setup

### ISSUE THREAD

**Issue by CopenHayden** [HeliosVirtualCockpit/Helios#558]
I had this working a mere hour ago, and while going through a tutorial, step-by-step-- tediously, it somehow stopped working. This is the status report I received. Any help would be greatly appreciated. Thanks!

{
  "product": "Helios",
  "version": "1.6.5200.1",
  "items": [
    {
      "report": [
        {
          "timeStamp": "05/21/2022 01:40:23.930 AM",
          "status": "Helios viewport patches installation would fail"
        },
        {
          "timeStamp": "05/21/2022 01:40:23.930 AM",
          "status": "Some patches would fail to apply.  No patches have been applied."
        },
        {
          "timeStamp": "05/21/2022 01:40:17.480 AM",
          "status": "Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\AN_ALR69V\\indicator\\AN_ALR69V_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.480 AM",
          "status": "Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\CDU\\indicator\\CDU_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.480 AM",
          "status": "Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\CMSC\\indicator\\CMSC_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.480 AM",
          "status": "Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\CMSP\\indicator\\CMSP_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.480 AM",
          "status": "Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\DigitalClock\\Indicator\\DIGIT_CLK_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.480 AM",
          "status": "Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\HUD\\Indicator\\HUD_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.480 AM",
          "status": "Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\MFCD\\indicator\\MFCD_left_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.480 AM",
          "status": "Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\MFCD\\indicator\\MFCD_right_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.480 AM",
          "status": "Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\UHF_Radio\\indicator\\freq_status_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\UHF_Radio\\indicator\\preset_channel_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\UHF_Radio\\indicator\\repeater_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\AN_ALR69V\\indicator\\AN_ALR69V_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\CDU\\indicator\\CDU_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\CMSC\\indicator\\CMSC_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\CMSP\\indicator\\CMSP_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\DigitalClock\\Indicator\\DIGIT_CLK_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\HUD\\Indicator\\HUD_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\MFCD\\indicator\\MFCD_left_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\MFCD\\indicator\\MFCD_right_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\UHF_Radio\\indicator\\freq_status_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\UHF_Radio\\indicator\\preset_channel_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\UHF_Radio\\indicator\\repeater_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\AV8BNA\\Cockpit\\MPCD\\indicator\\MPCD_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\DED\\indicator\\DED_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\EHSI\\indicator\\EHSI_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\EHSI\\indicator\\LCD\\EHSI_LCD.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\HUD\\indicator\\HUD_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\MFD\\indicator\\MFD_left_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\MFD\\indicator\\MFD_right_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\Displays\\MFD\\indicator\\LCD\\MFD_LCD.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\F-16C\\Cockpit\\Scripts\\EWS\\RWR\\indicator\\RWR_ALR56_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\F14\\Cockpit\\Scripts\\HeadUpDisplay\\Indicator\\init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\F14\\Cockpit\\Scripts\\RWR\\Indicator\\Pilot\\init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\F14\\Cockpit\\Scripts\\RWR\\Indicator\\RIO\\init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\F14\\Cockpit\\Scripts\\UHF_Radio\\Indicator\\Main\\init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\F14\\Cockpit\\Scripts\\UHF_Radio\\Indicator\\RemotePilot\\init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\F14\\Cockpit\\Scripts\\UHF_Radio\\Indicator\\RemoteRIO\\init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\F14\\Cockpit\\Scripts\\VHF_Radio\\Indicator\\Main\\init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.481 AM",
          "status": "Mods\\aircraft\\F14\\Cockpit\\Scripts\\VHF_Radio\\Indicator\\RemotePilot\\init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "05/21/2022 01:40:17.482 AM",
          "severity": 2,
          "status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' failed to apply patch to Mods\\aircraft\\FA-18C\\Cockpit\\Scripts\\TEWS\\indicator\\RWR_ALR67_init.lua: CONTENT_NOT_FOUND\r\nThe patch could not locate the expected content section (searching near character 608):",
          "code": [
            {
              "text": "e  = true",
              "lineEnding": 1
            },
            {
              "text": "\tshaderLineDe",
              "lineEnding": 0
            }
          ]
        },
        {
          "timeStamp": "05/21/2022 01:40:17.482 AM",
          "severity": 2,
          "status": "DCS 2.7.11.22211 could not be patched using version 002_007_00010_19473_00000 of the patches.  You may need a newer distribution of Helios or of the patches.",
          "recommendation": "Please make sure you do not have viewport mods installed and run a DCS Repair (slow mode) to clean up DCS."
        }
      ],
      "name": "Configuration Results"
    }
  ]
}

**Comment by Todd1215** [comment]
I just patched my Helios / DCS install after updating to latest DCS patchset and had no issues.

**Comment by BlueFinBima** [comment]
If this is still a problem, please see https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help and https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help-with-Helios-Software
