### ISSUE TITLE
Issue with Release 1.6.5305.0 and A-10 Patches

### ISSUE THREAD

**Issue by JollyGreenFE** [HeliosVirtualCockpit/Helios#577]
Updated to the latest release ver of Helios and when I opened Capt Zeen's A10CII_v1.0b I received a wealth of errors all relating to viewports.  When attempting to re-install patches, a pop-up says "Some patches would fail to apply. No patches have been applied."

[Helios has written the report to the file 'Helios_status_report_133013436269374894.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

{
  "product": "Helios",
  "version": "1.6.5305.0",
  "items": [
    {
      "report": [
        {
          "timeStamp": "07/03/2022 10:39:48.773 AM",
          "status": "Helios 1.6.5305.0000\nhttps://github.com/HeliosVirtualCockpit/Helios/"
        },
        {
          "timeStamp": "07/03/2022 10:40:03.464 AM",
          "status": "Loading Profile..."
        },
        {
          "timeStamp": "07/03/2022 10:40:05.060 AM",
          "status": "Generated Export.lua stub is up to date for DCS.openbeta",
          "flags": 2
        },
        {
          "timeStamp": "07/03/2022 10:40:05.061 AM",
          "status": "The configured DCS export script at '%USERPROFILE%\\Saved Games\\DCS.openbeta\\Scripts\\Helios\\HeliosExport16.lua' is up to date",
          "flags": 2
        },
        {
          "timeStamp": "07/03/2022 10:40:05.064 AM",
          "status": "The Helios driver generated by this interface at '%USERPROFILE%\\Saved Games\\DCS.openbeta\\Scripts\\Helios\\Drivers\\A-10C_2.lua' is up to date",
          "flags": 2
        },
        {
          "timeStamp": "07/03/2022 10:40:05.064 AM",
          "status": "Generated Export.lua stub is up to date for DCS",
          "flags": 2
        },
        {
          "timeStamp": "07/03/2022 10:40:05.064 AM",
          "status": "The configured DCS export script at '%USERPROFILE%\\Saved Games\\DCS\\Scripts\\Helios\\HeliosExport16.lua' is up to date",
          "flags": 2
        },
        {
          "timeStamp": "07/03/2022 10:40:05.069 AM",
          "status": "The Helios driver generated by this interface at '%USERPROFILE%\\Saved Games\\DCS\\Scripts\\Helios\\Drivers\\A-10C_2.lua' is up to date",
          "flags": 2
        },
        {
          "timeStamp": "07/03/2022 10:40:05.108 AM",
          "status": "monitor setup file 'Helios.lua' in Saved Games\\DCS.openbeta\\Config\\MonitorSetup is up to date",
          "flags": 2
        },
        {
          "timeStamp": "07/03/2022 10:40:05.108 AM",
          "status": "monitor setup file 'Helios.lua' in Saved Games\\DCS\\Config\\MonitorSetup is up to date",
          "flags": 2
        },
        {
          "timeStamp": "07/03/2022 10:40:05.128 AM",
          "status": "Saved Games\\DCS.openbeta\\Config\\options.lua has 'Resolution' set to 3840x3240",
          "flags": 2
        },
        {
          "timeStamp": "07/03/2022 10:40:05.129 AM",
          "status": "Saved Games\\DCS.openbeta\\Config\\options.lua has 'Monitors' set to 'helios'",
          "flags": 2
        },
        {
          "timeStamp": "07/03/2022 10:40:05.129 AM",
          "status": "Saved Games\\DCS.openbeta\\Config\\options.lua has 'Fullscreen' set to False",
          "flags": 2
        },
        {
          "timeStamp": "07/03/2022 10:40:05.130 AM",
          "status": "Saved Games\\DCS\\Config\\options.lua has 'Resolution' set to 3840x3240",
          "flags": 2
        },
        {
          "timeStamp": "07/03/2022 10:40:05.130 AM",
          "status": "Saved Games\\DCS\\Config\\options.lua has 'Monitors' set to 'h_a10c_v3.0b'",
          "flags": 2,
          "recommendation": "Using DCS, please make sure 'Monitors' in the 'System' options is set to 'Helios'"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.130 AM",
          "status": "Saved Games\\DCS\\Config\\options.lua has 'Fullscreen' set to False",
          "flags": 2
        },
        {
          "timeStamp": "07/03/2022 10:40:05.156 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\AN_ALR69V\\indicator\\AN_ALR69V_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.156 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\CDU\\indicator\\CDU_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.156 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\CMSC\\indicator\\CMSC_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.156 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\CMSP\\indicator\\CMSP_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.156 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\DigitalClock\\Indicator\\DIGIT_CLK_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.157 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\HUD\\Indicator\\HUD_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.157 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\MFCD\\indicator\\MFCD_left_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.157 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\MFCD\\indicator\\MFCD_right_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.157 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\UHF_Radio\\indicator\\freq_status_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.157 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\UHF_Radio\\indicator\\preset_channel_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.157 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\A-10C\\Cockpit\\Scripts\\UHF_Radio\\indicator\\repeater_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.157 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\AN_ALR69V\\indicator\\AN_ALR69V_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.158 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\CDU\\indicator\\CDU_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.158 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\CMSC\\indicator\\CMSC_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.158 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\CMSP\\indicator\\CMSP_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.158 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\DigitalClock\\Indicator\\DIGIT_CLK_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.158 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\HUD\\Indicator\\HUD_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.158 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\MFCD\\indicator\\MFCD_left_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.158 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\MFCD\\indicator\\MFCD_right_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.159 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\UHF_Radio\\indicator\\freq_status_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.159 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\UHF_Radio\\indicator\\preset_channel_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.159 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\A-10C_2\\Cockpit\\Scripts\\UHF_Radio\\indicator\\repeater_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.159 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\AH-64D\\Cockpit\\Scripts\\ASE\\CMWS\\CMWS_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.159 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\AH-64D\\Cockpit\\Scripts\\Displays\\EUFD\\EUFD_cpg_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.159 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\AH-64D\\Cockpit\\Scripts\\Displays\\EUFD\\EUFD_plt_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.159 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\AH-64D\\Cockpit\\Scripts\\Displays\\MFD\\indicator\\MFD_cpg_left_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.159 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\AH-64D\\Cockpit\\Scripts\\Displays\\MFD\\indicator\\MFD_cpg_right_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.160 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\AH-64D\\Cockpit\\Scripts\\Displays\\MFD\\indicator\\MFD_plt_left_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.160 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\AH-64D\\Cockpit\\Scripts\\Displays\\MFD\\indicator\\MFD_plt_right_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.160 AM",
          "severity": 2,
          "status": "DCS installation in 'G:\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\AH-64D\\Cockpit\\Scripts\\Displays\\TEDAC\\TEDAC_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "07/03/2022 10:40:05.186 AM",
          "severity": 2,
          "status": "Failed preflight check.",
          "recommendation": "Please resolve problems or disable preflight check in preferences."
        }
      ],
      "name": "Control Center Console"
    }
  ]
}

**Comment by BlueFinBima** [comment]
If this is still a problem, please see https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help and https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help-with-Helios-Software
