### ISSUE TITLE
 KU of AH64 does not display the entered characters

### ISSUE THREAD

**Issue by 453jerry** [HeliosVirtualCockpit/Helios#586]
KU does not display characters entered when add/editing waypoints . Similarly, when entering range in the WPN page, the entered characters will not be displayed. 
![屏幕截图 2022-07-20 020238](https://user-images.githubusercontent.com/15866475/179819148-55db21a4-e47b-4983-a128-2769a16ff15e.png)    

![屏幕截图 2022-07-20 015952](https://user-images.githubusercontent.com/15866475/179819463-f9107f1c-ac20-4b1f-8a84-24b69250a4cf.png)

**Comment by BlueFinBima** [comment]
Colon is a reserved character and is not supposed to be sent by the exports because colon is a data termination (but it is being sent).   This is fixed in https://github.com/HeliosVirtualCockpit/Helios/commit/55a5bb860b8a19604e07a0feee92b704f9c8cf01

**Comment by BlueFinBima** [comment]
@453jerry 1.6.5305.2 is now available with the fix.  From the photographs, it looks like you need to adjust your Iris config xml.  There is also V0.0.8 of the [ Apache Profile ](https://github.com/BlueFinBima/DCS-AH-64D-Profile/releases/latest ) which has just been released.
I am going to close this issue, but ift can always be reopened if 1.6.5305.2 is not a complete fix.
