### ISSUE TITLE
Falcon Textures are incorrectly displayed after switching aircraft

### ISSUE THREAD

**Issue by Todd1215** [HeliosVirtualCockpit/Helios#594]
**Describe the Helios Issue**
If a user starts his/her profile that contains Falcon Textures and they commit to 3D then backout and switch to another aircraft type ie: from F16 to F18, the definition of the texture areas are not reread and the texture areas in the already running profile and what is defined in shared memory are out of sync.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start your Helios profile that contains Falcon Textures2. 
2. Select a TE and aircraft and commit to 3D.
3. Once in 3D back out of 3D back to the 2D UI4. 
4. select a different aircraft type and commit to 3D

**Expected behavior**
If a user switches aircraft without stopping and starting the profile Helios should understand this and require the new shared memory locations for each texture extraction.

**Screenshots**
Initial commit to 3D with good textures
![falcon-textures1](https://user-images.githubusercontent.com/6605805/181830830-c20a45e8-02f9-4963-be6a-0155adfb6b85.png)

Secondary commit to 3D after changing aircraft type
![falcon-textures2](https://user-images.githubusercontent.com/6605805/181830846-ad0a698d-0d65-4c31-9a35-7cf6beaf2f75.png)

**please complete the following information:**
 - Helios Version [eg 1.6.5305.3]
 - Falcon BMS 4.36.1

This issue is not specific to Falcon BMS version changes. There has been no significant updates to Falcon BMS where it pertains to Shared Memory textures

**Comment by BlueFinBima** [comment]
Shipped in 1.6.5306.4 @Todd1215 can you close this please?
