### ISSUE TITLE
DCS AH-64 TEDAC Display Mode Switch Incorrect Values

### ISSUE THREAD

**Issue by MedievalBunny** [HeliosVirtualCockpit/Helios#596]
In the new Interface for the AH-64, the argument values for the TEDAC Display Mode switch are inverted. The JSON should read:

`{
      "heliosType": "DCS.Common.Switch",
      "device": "TEDAC",
      "name": "Display Mode",
      "description": "Current position of this switch.",
      "exports": [
        {
          "format": "%0.1f",
          "isExportedEveryFrame": false,
          "id": "154"
        }
      ],
      "deviceId": "51",
      "positions": [
        {
          "argumentValue": "0.0",
          "name": "Day",
          "actionID": "3001"
        },
        {
          "argumentValue": "0.5",
          "name": "Night",
          "actionID": "3001"
        },
        {
          "argumentValue": "1.0",
          "name": "Off",
          "actionID": "3001"
        }
      ]
    },`

**Comment by MedievalBunny** [comment]
Well, that looks ugly. I'll make the change on my fork and submit a pull request as well, though I know it'll just need to be mirrored to a different file.

**Comment by BlueFinBima** [comment]
I expect this to be fixed in https://github.com/HeliosVirtualCockpit/Helios/commit/9b794af47f6821fa3f68821f15d496a743bfaf19 and https://github.com/HeliosVirtualCockpit/HeliosInterfaces/commit/1211c3c790956fa2efe2a11137e0fa6d783ed740 because the TEDAC gauge was needed a little tweak.

**Comment by BlueFinBima** [comment]
fixed in 1.6.5306.4
