### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by Eraseri** [HeliosVirtualCockpit/Helios#601]
Hi, not really an issue but couldn't open up discussion in tab. Nevertheless I wonder would if it be easy or even possible to make this run on linux?

**Comment by BlueFinBima** [comment]
@Eraseri Easy?  No.  This has been looked at in the past and there are Windows native methods in the code which would need to replaced which would be just one of the many hurdles to achieving what you ask.  It is do-able by someone with the necessary skills, time and desire to have the Control Center running on Linux.  Unfortunately that person is not on this development team at this time.  
I've added to the fridge.
