### ISSUE TITLE
The Viewport of Helios F16 cant be used for DCS F-16I SUFA MOD. 

### ISSUE THREAD

**Issue by Torattacker** [HeliosVirtualCockpit/Helios#602]
I spent much time.I found the DCS F-16I SUFA MOD cant be used with extra screen for MFCD,RWR and DED.I didnt know how to overcome the problem.
The F-16i SUFA mod is here:
https://www.mediafire.com/file/cep6u3ict6pv40m/F-16I_SUFA_V1.5.rar/file
![1660407714173](https://user-images.githubusercontent.com/111193971/184503143-767893e5-b83b-4286-9bb8-fb749634ea7f.jpg)
.

**Comment by Torattacker** [comment]
![1660409190341](https://user-images.githubusercontent.com/111193971/184503278-3c730508-04cf-46be-a5d7-81425fc88c7e.jpg)
i think this mod duplicated the systems to make F-16I own two cockpits. so we cant use the normal way to export the MFCD、RWR,DED.

**Comment by Torattacker** [comment]
![1660409956647](https://user-images.githubusercontent.com/111193971/184503686-357e8be4-2fb5-4d45-b7ae-422b51ec18c6.jpg)
The DED become "double show"

**Comment by BlueFinBima** [comment]
Hi @Torattacker, the SUFA mod is not supported by Helios at this time.  If you find a way to make the viewports co-exist with the DCS F-16 module, then it would be great if you documented this for others to benefit from.
