### ISSUE TITLE
AV-8B Fuel Panel Bingo Knob only increments, can't decrement

### ISSUE THREAD

**Issue by GAKB** [HeliosVirtualCockpit/Helios#603]
Turning the Bingo Fuel knob clockwise to increment does increment the bingo fuel value.
Turning the Bingo Fuel knob counter-clockwise to decrement results in the value being incremented.
This also happens if a separate encoder is used and configured to increment or decrement the Bingo Fuel value.

[Helios_status_report_133056678450306180.txt](https://github.com/HeliosVirtualCockpit/Helios/files/9396836/Helios_status_report_133056678450306180.txt)

**Comment by BlueFinBima** [comment]
Yes,  that is a problem.  I'll look into it.

**Comment by BlueFinBima** [comment]
Shipped in [1.6.5307.9](https://github.com/HeliosVirtualCockpit/Helios/releases/latest)

**Comment by GAKB** [comment]
That's superb, many thanks.
