### ISSUE TITLE
M-2000C Viewport Patches for PCN_BR, PCN_UR, VTB & VTH/HUD Not Installing at 1.6.5307.9

### ISSUE THREAD

**Issue by BlueFinBima** [HeliosVirtualCockpit/Helios#614]
If you are having problems installing / configuring / using a profile then you should use the support process for the provider of that profile.

- [X] I have read [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)

**Describe the Helios Issue**
DCS Additional Viewports interface won't install M-2000C Viewport Patches for PCN_BR, PCN_UR, VTB & VTH/HUD  **1.6.5307.9** due to the patch being created to patch files which are line terminated with LF rather than CRLF.

**Screenshots**
![image](https://user-images.githubusercontent.com/18526232/189363627-5dfe6c07-b2d6-44d5-b33c-dbbc173b3bef.png)
**please complete the following information:**
 - Helios Version 1.6.5307.9
 - [X] Profile Editor
 - [ ] Control Center
 - [ ] Keypress Receiver
 - [ ] Something else (*remember to tell us what it is*)

**Additional context**
```
        {
          "timeStamp": "09/09/2022 02:35:52.146 PM",
          "severity": 2,
          "status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\M-2000C\\Cockpit\\PCN\\PCN_BR_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "09/09/2022 02:35:52.146 PM",
          "severity": 2,
          "status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\M-2000C\\Cockpit\\PCN\\PCN_UR_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "09/09/2022 02:35:52.146 PM",
          "severity": 2,
          "status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\M-2000C\\Cockpit\\VTB\\VTB_init.lua",
          "recommendation": "Apply patches"
        },
        {
          "timeStamp": "09/09/2022 02:35:52.146 PM",
          "severity": 2,
          "status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\M-2000C\\Cockpit\\VTH\\HUD_init.lua",
          "recommendation": "Apply patches"
        },
```

**Comment by BlueFinBima** [comment]
Circumvention:  Untick the following patches in the advanced section of the DCS Additional Viewports interface.
![image](https://user-images.githubusercontent.com/18526232/189364734-26cdb8eb-be2d-4f52-b9be-a27916ecfb6b.png)

**Comment by BlueFinBima** [comment]
New patches built under 0bb4db73218459334659874e174500169a1308ea

**Comment by BlueFinBima** [comment]
It appears that Razbam changed the VTB and the RWR (now called VCN) so different files need to be patched for these.

**Comment by pom2ter-git** [comment]
Hi

Same problem

{
  "product": "Helios",
  "version": "1.6.5307.9",
  "items": [
    {
      "report": [
        {
          "timeStamp": "09/11/2022 09:14:54.532 PM",
          "status": "Helios viewport patches installation incomplete"
        },
        {
          "timeStamp": "09/11/2022 09:14:54.532 PM",
          "status": "Not all patches were installed"
        },
        {
          "timeStamp": "09/11/2022 09:14:48.478 PM",
          "status": "Mods\\aircraft\\M-2000C\\Cockpit\\RWR\\RWR_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "09/11/2022 09:14:52.233 PM",
          "status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' successfully wrote Mods\\aircraft\\M-2000C\\Cockpit\\COM\\COM_GreenBox_init.lua after applying patch"
        },
        {
          "timeStamp": "09/11/2022 09:14:52.237 PM",
          "status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' successfully wrote Mods\\aircraft\\M-2000C\\Cockpit\\COM\\COM_init.lua after applying patch"
        },
        {
          "timeStamp": "09/11/2022 09:14:52.240 PM",
          "status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' successfully wrote Mods\\aircraft\\M-2000C\\Cockpit\\FUEL\\FUEL_init.lua after applying patch"
        },
        {
          "timeStamp": "09/11/2022 09:14:52.245 PM",
          "status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' successfully wrote Mods\\aircraft\\M-2000C\\Cockpit\\PCA_PPA\\PCA_BR_init.lua after applying patch"
        },
        {
          "timeStamp": "09/11/2022 09:14:52.248 PM",
          "status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' successfully wrote Mods\\aircraft\\M-2000C\\Cockpit\\PCA_PPA\\PCA_UR_init.lua after applying patch"
        },
        {
          "timeStamp": "09/11/2022 09:14:52.252 PM",
          "status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' successfully wrote Mods\\aircraft\\M-2000C\\Cockpit\\PCA_PPA\\PPA_init.lua after applying patch"
        },
        {
          "timeStamp": "09/11/2022 09:14:52.302 PM",
          "status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' successfully wrote Mods\\aircraft\\M-2000C\\Cockpit\\PCN\\PCN_BR_init.lua after applying patch"
        },
        {
          "timeStamp": "09/11/2022 09:14:52.305 PM",
          "status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' successfully wrote Mods\\aircraft\\M-2000C\\Cockpit\\PCN\\PCN_UR_init.lua after applying patch"
        },
        {
          "timeStamp": "09/11/2022 09:14:52.305 PM",
          "status": "Mods\\aircraft\\M-2000C\\Cockpit\\RWR\\RWR_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World'; ignoring patch"
        },
        {
          "timeStamp": "09/11/2022 09:14:52.309 PM",
          "status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' successfully wrote Mods\\aircraft\\M-2000C\\Cockpit\\VTB\\VTB_init.lua after applying patch"
        },
        {
          "timeStamp": "09/11/2022 09:14:52.313 PM",
          "status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World' successfully wrote Mods\\aircraft\\M-2000C\\Cockpit\\VTH\\HUD_init.lua after applying patch"
        }
      ],
      "name": "Configuration Results"
    }
  ]
}

**Comment by BlueFinBima** [comment]
Shipped in https://github.com/HeliosVirtualCockpit/Helios/releases/tag/1.6.5308.1
