### ISSUE TITLE
ADI F-18

### ISSUE THREAD

**Issue by Coolands** [HeliosVirtualCockpit/Helios#618]
Hello,
I have a small problem with the F18 and the SAI panel. As soon as I activate the pitch or the bank of the ADI, the instruments all jerk and the needles are no longer fluid at all. Without the ADI everything works normally

**Comment by BlueFinBima** [comment]
Hi @coolands, have you used this link [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)?  Also the issue template which appears to have been deleted, is intended to get a good starter set of information for any issue.
https://www.youtube.com/watch?v=wcaAk7r4JfA

**Comment by BlueFinBima** [comment]
New Standby ADI in 1.6.5700.0 but shouldn't change anything with respect to this minimal set of information.

Closing until more information is received.
