### ISSUE TITLE
update dcs beta broke helios

### ISSUE THREAD

**Issue by Crass007** [HeliosVirtualCockpit/Helios#620]
Cant install patches

{
  "product": "Helios",
  "version": "1.6.5308.1",
  "items": [
    {
      "report": [
        {
          "timeStamp": "09/24/2022 07:26:18.919 AM",
          "status": "Helios viewport patches installation would fail"
        },
        {
          "timeStamp": "09/24/2022 07:26:18.919 AM",
          "status": "Some patches would fail to apply.  No patches have been applied."
        },
        {
          "timeStamp": "09/24/2022 07:25:58.410 AM",
          "severity": 2,
          "status": "DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta' failed to apply patch to Mods\\aircraft\\AH-64D\\Cockpit\\Scripts\\Displays\\MFD\\indicator\\MFD_plt_right_init.lua: CONTENT_NOT_FOUND\r\nThe patch could not locate the expected content section (searching near character 609):",
          "code": [
            {
              "text": "_\" )",
              "lineEnding": 1
            },
            {
              "text": "",
              "lineEnding": 1
            },
            {
              "text": "",
              "lineEnding": 1
            },
            {
              "text": "\u0001\u0002",
              "lineEnding": 0
            }
          ]
        },
        {
          "timeStamp": "09/24/2022 07:25:58.412 AM",
          "severity": 2,
          "status": "DCS 2.7.18.30348 could not be patched using version 002_007_00017_29140_00000 of the patches.  You may need a newer distribution of Helios or of the patches.",
          "recommendation": "Please make sure you do not have viewport mods installed and run a DCS Repair (slow mode) to clean up DCS."
        }
      ],
      "name": "Configuration Results"
    }
  ]
}

**Comment by BlueFinBima** [comment]
@Crass007 Did you take the recommended action shown above?  **"recommendation": "Please make sure you do not have viewport mods installed and run a DCS Repair (slow mode) to clean up DCS."**

I've just applied all the patches to 2.7.18.30348 from 002_007_00017_29140_00000 and they go on fine.

![image](https://user-images.githubusercontent.com/18526232/192330737-4f423693-b464-4e8c-aead-be7ff6bc419f.png)

If you continue to have a problem after a DCS Repair (Slow Mode), then assistance can be obtained from reading the following information [Get Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)

**Comment by Crass007** [comment]
i did not see that, tried it and yep you are correct that fixed it , thanks

**Comment by BlueFinBima** [comment]
Glad this is now resolved.
