### ISSUE TITLE
Request: av8b mfd rocker switch function

### ISSUE THREAD

**Issue by MadKreator37** [HeliosVirtualCockpit/Helios#625]
Is it possible to get the av8b mfd rocker switches to function? SYM, GAIN etc.. when I press them on my touchscreen it looks like it’s registering the click, but nothing happens in the actual game. Only been using Helios for a week or so. I do see that when you click the in-game cockpit they register on helios though. Be easy on me lol

**Comment by MadKreator37** [comment]
I tried messing with the outputs but I just screwed things up and had to re-install the profile lol.  I found that due to the nature of the av8b exports ( the text being blurry and not small crispy lines, even after trying to adjust the lua settings for the displays) that’s just dialing down the symbology rocker helps clear them just before the texts starts darkening. Not a deal breaker, but would be nice to use the touchscreen instead of that being the only thing I have to click the in-game cockpit for.

On captnzeen a-10c2 profile the ufc intensity rocker is reversed and I managed to swap those outputs just fine, but couldn’t for the life of me figure out how to make the av8b rockers work from the touchscreen.

**Comment by BlueFinBima** [comment]
The commands being used by the AV-8B interface are incorrect for the rockers on both the left and right MFCDs.  This said, correcting them is not all that is required.   More work needed.

**Comment by MadKreator37** [comment]
Thank you for looking into it! Also thank you for the hard work on the profile! These are a monumental tasks and your work is very, very much appreciated by us dummies who can’t figure it out 😃

**Comment by BlueFinBima** [comment]
@MadKreator37 Thanks for the kind words... much appreciated because as you say, a huge number of hours go into the profiles and Helios. 
I think I've now resolved this issue and the fix will appear in the next release of Helios

**Comment by MadKreator37** [comment]
Wow that was fast! Looking forward to it. Thank you again!… from everyone😁

**Comment by BlueFinBima** [comment]
Delivered in 1.6.5500.0
