### ISSUE TITLE
Missing patch DCS Steam version 2.7.18.30765

### ISSUE THREAD

**Issue by paaaho** [HeliosVirtualCockpit/Helios#629]
If you are having problems installing / configuring / using a profile then you should use the support process for the provider of that profile.

- [x ] I have read [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)

**Describe the Helios Issue**
Missing patch DCS Steam version 2.7.18.30765

**To Reproduce**
Missing patch DCS Steam version 2.7.18.30765

**Expected behavior**
Excisting patch DCS Steam version 2.7.18.30765

**Screenshots**
NA

**please complete the following information:**
 - Helios Version 1.6.5400.2
 - DCS Version [Open Beta 2.7.18.30765]

**Comment by BlueFinBima** [comment]
@Paaaho I don't have DCS on steam so more specifics about the problem are required.  Is the problem related to one or more patches?  If so which one(s).

**Comment by paaaho** [comment]
There has been couple of patches missing. The steam does not seem to follow the same buiöd cycles. Lähetetty puhelimestani-------- Alkuperäinen viesti --------Lähettäjä: BlueFinBima ***@***.***>Päivämäärä: la 29. lokak. 2022 klo 11.50Vastaanottaja: HeliosVirtualCockpit/Helios ***@***.***>Kopio: paaaho ***@***.***>, Mention ***@***.***>Aihe: Re: [HeliosVirtualCockpit/Helios] Missing patch DCS Steam version 2.7.18.30765 (Issue #629)
@paaaho I don't have DCS on steam so more specifics about the problem are required.  Is the problem related to one or more patches?  If so which one(s).

**Comment by BlueFinBima** [comment]
@paaaho,  really difficult to help you without facts.  Which specific patches are missing?

**Comment by paaaho** [comment]
HiSorry I wanted to just inform that whole patch folders for this DCS revision is missing. I ended up looking the patch files myself and manualky adjusting the fa18 viewport patches I needed. I am therefore now Ok, so no worries. BrJouniLähetetty puhelimestani-------- Alkuperäinen viesti --------Lähettäjä: BlueFinBima ***@***.***>Päivämäärä: su 30. lokak. 2022 klo 18.18Vastaanottaja: HeliosVirtualCockpit/Helios ***@***.***>Kopio: paaaho ***@***.***>, Mention ***@***.***>Aihe: Re: [HeliosVirtualCockpit/Helios] Missing patch DCS Steam version 2.7.18.30765 (Issue #629)
@paaaho,  really difficult to help you without facts.  Which specific patches are missing?
