### ISSUE TITLE
Patching Ka-50 at DCS 2.8.0.32066 not working

### ISSUE THREAD

**Issue by xfirf** [HeliosVirtualCockpit/Helios#630]
[Helios has written the report to the file 'Helios_status_report_133114589221630465.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

[Helios_status_report_133114589221630465.txt](https://github.com/HeliosVirtualCockpit/Helios/files/9891241/Helios_status_report_133114589221630465.txt)

**Comment by BlueFinBima** [comment]
Modified the title to more accurately describe the problem which is a single patch not applying.
![image](https://user-images.githubusercontent.com/18526232/198728151-624920f3-3347-46e4-ba8a-0efa12fc2f4b.png)

**Comment by mnp555** [comment]
Same problem.
I bypassed the patch to device_int.lua writing directle le modification.
I need to run Helios without the preflight check.
But remain some issue. Other profiles works well.
The Ka-50 works in ISTANT ACTION and in Multiplayer, but in Singleplayer DCS crash.
see tha attached file.
thx for attention.
![Screenshot 2022-10-28 225029](https://user-images.githubusercontent.com/69124673/198730211-5547c6e2-e26e-4164-a747-488400c4979a.jpg)

**Comment by mnp555** [comment]
furter log

2022-10-28 18:43:52.180 INFO    Lua::Config (Main): stack traceback:
	[C]: in function 'update_arguments'
	[string "C:\Users\gmv\Saved Games\DCS.openbeta\Scripts\Helios\HeliosExport16.lua"]:160: in function <[string "C:\Users\gmv\Saved Games\DCS.openbeta\Scripts\Helios\HeliosExport16.lua"]:123>
	[C]: in function 'pcall'
	[string "C:\Users\gmv\Saved Games\DCS.openbeta\Scripts\Helios\HeliosExport16.lua"]:968: in function <[string "C:\Users\gmv\Saved Games\DCS.openbeta\Scripts\Helios\HeliosExport16.lua"]:966>
2022-10-28 18:43:52.180 INFO    APP (Main): enumerating loaded modules

**Comment by BlueFinBima** [comment]
@mnp555 DCS crash - especially immediately after a major DCS update - is not something I'm going to investigate without any clear link to Helios.  It is also unrelated to this issue which relates to a patch not being applied.

**Comment by xfirf** [comment]
@BlueFinBima Thanks for debugging. After disabling the KA-50 its working for all others. :-)

**Comment by BlueFinBima** [comment]
@mnp555 The failure in HeliosExports16 is unrelated to the reported issue.  It may be a problem, but probably best to raise it (and describe the circumstances where you saw it) in [helios-support on CZ's server](https://discord.com/channels/434241908492075010/434269438884184084)

**Comment by BlueFinBima** [comment]
The new patch applies.  Not tested with Ka-50, but simple enough re-patch necessitated due to the changes to the Ka-50 devices-init.lua.  It will ship in the next release of Helios.

**Comment by BlueFinBima** [comment]
Circumvention is to untick the single patch file 
![image](https://user-images.githubusercontent.com/18526232/198832650-8cc1ae45-e098-411e-b370-b36d0236653a.png)

**Comment by PSYKO-nz** [comment]
@BlueFinBima thanks a ton for sorting this and posting a fix, super appreciate it :)

**Comment by mnp555** [comment]
@BlueFinBima Thx for answer and good job.

**Comment by BlueFinBima** [comment]
Awaiting Delivery

**Comment by BlueFinBima** [comment]
Delivered in 1.6.5500.0
