### ISSUE TITLE
patching dcs  2.8

### ISSUE THREAD

**Issue by Sharkfin61** [HeliosVirtualCockpit/Helios#632]
[Helios has written the report to the file 'Helios_status_report_133115952300402529.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

[Helios_status_report_133115952300402529.txt](https://github.com/HeliosVirtualCockpit/Helios/files/9895504/Helios_status_report_133115952300402529.txt)

**Comment by BlueFinBima** [comment]
From the supplied log. this is a duplicate of #630
