### ISSUE TITLE
Error Processing Tick or Refresh

### ISSUE THREAD

**Issue by JollyGreenFE** [HeliosVirtualCockpit/Helios#633]
Just noticed this after flying a BMS Sortie.  Using a modified Ices F-16 profile. Only noticed that the Center console no longer shows datacard information (E.G. steerpoints, threats, etc) and the error message in the Helios Control Center.  

[Helios_status_report_133116222888965297.txt](https://github.com/HeliosVirtualCockpit/Helios/files/9896335/Helios_status_report_133116222888965297.txt)

**Comment by Todd1215** [comment]
I checked my Ice Linknet profile and have no issues with the data card getting updated. This must be an issue in your environment. Ensure you have given rights to run third party apps within Helios Processes tab
