### ISSUE TITLE
Patches not installing in 2.8 helios 1.6.5400.0002

### ISSUE THREAD

**Issue by MadKreator37** [HeliosVirtualCockpit/Helios#636]
[Helios_status_report_133118076160594880.txt](https://github.com/HeliosVirtualCockpit/Helios/files/9913727/Helios_status_report_133118076160594880.txt)

**Comment by MadKreator37** [comment]
just found discord chat with this issue.. disabled only the ka-50 patches and all others install fine

**Comment by BlueFinBima** [comment]
Another duplicate of #630
