### ISSUE TITLE
Helios crash the new DCS module: MB-339 PAN.

### ISSUE THREAD

**Issue by PVI-Bat** [HeliosVirtualCockpit/Helios#640]
If you are having problems installing / configuring / using a profile then you should use the support process for the provider of that profile.

- [x ] I have read [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)

**Describe the Helios Issue**
Helios crash the new DCS module: MB-339 PAN.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'any missions with MB-339 PAN'
2. Click on 'start'
3. Scroll down to 'select a role as MB-339 PAN then ok' 
4. See error DCS OPENBETA CRASH

**Expected behavior**
If I turn HELIOS off from my export.lua, MB-339 PAN works again.

**Screenshots**
None.

**please complete the following information:**
 - Helios Version [eg 1.6.5101.0]
 - DCS Version [e.g. Open Beta 2.8.0.32235]
 - [ ] Profile Editor
 - [ ] Control Center
 - [ ] Keypress Receiver
 - [ x] Something else (*remember to tell us what it is*)
Helios crash the new DCS module: MB-339 PAN.
**Additional context**
Add any other context about the problem here.  (*this problem started happening when I select a role as MB-339 PAN player in single and multiplayer missions*)
[dcs.log-20221107-210535.zip](https://github.com/HeliosVirtualCockpit/Helios/files/9955472/dcs.log-20221107-210535.zip)

**Comment by BlueFinBima** [comment]
@PVI-Bat  Can you unpack the attached file to `Saved Games\DCS.openbeta\` and re-test please?  I'm interested to know if this stops the DCS crash. 
[Helios_Issue_640_Test.zip](https://github.com/HeliosVirtualCockpit/Helios/files/9962139/Helios_Issue_640_Test.zip)

**Comment by BlueFinBima** [comment]
@PVI-Bat I've withdrawn the code and request to test I mentioned above.  Your zip file above is corrupt, but Pvt Joker provided three instances of a failure. Assuming that these are the same as the failure you're seeing, I have come to the conclusion that this is a bug in the MB339 module. 
The crash happens after a call at line 158 in HeliosExport16.lua 
```
2022-11-03 23:00:34.281 INFO    Lua::Config (Main): stack traceback:
	[C]: in function 'update_arguments'
	[string "C:\Users\@@@@\Saved Games\DCS.openbeta\Scripts\Helios\HeliosExport16.lua"]:158: in function <[string "C:\Users\@@@@\Saved Games\DCS.openbeta\Scripts\Helios\HeliosExport16.lua"]:121>
	[C]: in function 'pcall'
	[string "C:\Users\@@@@\Saved Games\DCS.openbeta\Scripts\Helios\HeliosExport16.lua"]:956: in function <[string "C:\Users\@@@@\Saved Games\DCS.openbeta\Scripts\Helios\HeliosExport16.lua"]:954>
	[C]: in function 'pcall'
	[string "C:\Users\@@@@\Saved Games\DCS.openbeta\Mods\Services\DCS-SRS\Scripts\DCS-SimpleRadioStandalone.lua"]:4888: in function <[string "C:\Users\@@@@\Saved Games\DCS.openbeta\Mods\Services\DCS-SRS\Scripts\DCS-SimpleRadioStandalone.lua"]:4861>
```
The code at  line 158 is 
`        local mainPanelDevice = GetDevice(0)`
and this line is the core of extracting data from DCS and is used extensively by Helios and other similar programs.  Helios does not have an interface for the MB-339, but that to a certain extent is irrelevant.  The failure happens inside the GetDevice(0) call which is code for the MB-339 module.  I don't think that there is anything Helios can do to avoid this crash which is a `C0000005 ACCESS_VIOLATION` 
```
0x00000000000AB81B (MB339A): ed_fm_release + 0x39A0B
0x0000000000094430 (MB339A): ed_fm_release + 0x22620
0x000000000002E150 (MB339A): (function-name not available) + 0x2E150
0x0000000000071B1A (MB339A): ed_fm_set_fc3_cockpit_draw_args_v2 + 0x3A
0x00000000001D6DBB (CockpitBase): cockpit::ccMainPanel::set_arguments + 0xFB
0x00000000001D43BF (CockpitBase): cockpit::ccMainPanel::l_update_arguments + 0x4F
```

As this information shows, the access violation is related to the MB339.

[dcs.log-20221105-035625.zip](https://github.com/HeliosVirtualCockpit/Helios/files/9964208/dcs.log-20221105-035625.zip)
[dcs.log-20221103-230034.zip](https://github.com/HeliosVirtualCockpit/Helios/files/9964210/dcs.log-20221103-230034.zip)
[dcs.log-20221104-181928.zip](https://github.com/HeliosVirtualCockpit/Helios/files/9964211/dcs.log-20221104-181928.zip)

So.... my conclusion is that this is a bug in the MB-339 module code, and unless there is more information which indicates that Helios is doing something incorrectly, I feel that this is a problem needing to be investigated by the module developers.

**Comment by BlueFinBima** [comment]
@PVI-Bat A remarkably similar issue reported on the Ka-50 in multiplayer has now been resolved by Eagle Dynamics.  
See https://forum.dcs.world/topic/311164-after-last-update-28-ka-50-crash-in-sp/#comment-5105520
