### ISSUE TITLE
F/A-18C Parking Brake Interface Malfunction

### ISSUE THREAD

**Issue by BlueFinBima** [HeliosVirtualCockpit/Helios#644]
Raised by [CPC]David https://discord.com/channels/434241908492075010/434269438884184084/1041133717311201361 The interface entry for 240 / 241 needs adjustment.
json change suggested by [CPC]David
```
 {
      "heliosType": "DCS.Common.Switch",
      "device": "Gear system",
      "name": "Emergency / Parking Brake Handle On/Off",
      "description": "Current position of this switch.",
      "exports": [
        {
          "format": "%0.3f",
          "isExportedEveryFrame": false,
          "id": "240"
        }
      ],
      "deviceId": "5",
      "positions": [
        {
          "argumentValue": "1.0",
          "name": "Pulled",
          "actionID": "3005"
        },
        {
          "argumentValue": "0.5",
          "name": "Middle",
          "actionID": "3005"
        },
        {
          "argumentValue": "0.0",
          "name": "Off",
          "actionID": "3005"
        }
      ]
    },
    {
      "heliosType": "DCS.Common.Switch",
      "device": "Gear system",
      "name": "Brake Handle Park/Emergency",
      "description": "Current position of this switch.",
      "exports": [
        {
          "format": "%0.3f",
          "isExportedEveryFrame": false,
          "id": "241"
        }
      ],
      "deviceId": "5",
      "positions": [
        {
          "argumentValue": "1.0",
          "name": "Vertical Left",
          "actionID": "3006"
        },
        {
          "argumentValue": "0.7",
          "name": "Vertical",
          "actionID": "3006",
          "stopActionID": "3006",
          "stopActionValue": "0.5"
        },
        {
          "argumentValue": "0.0",
          "name": "Horizontal",
          "actionID": "3006"
        }
      ]
    }
```

**Comment by davidmontpellier** [comment]
Hi @BlueFinBima ,

Found a bug in my correction.
The format is %0.1f
Here is the correct one;
{
      "heliosType": "DCS.Common.Switch",
      "device": "Gear system",
      "name": "Emergency / Parking Brake Handle On/Off",
      "description": "Current position of this switch.",
      "exports": [
        {
          "format": "%0.1f",
          "isExportedEveryFrame": false,
          "id": "240"
        }
      ],
      "deviceId": "5",
      "positions": [
        {
          "argumentValue": "1.0",
          "name": "Pulled",
          "actionID": "3005"
        },
        {
          "argumentValue": "0.5",
          "name": "Middle",
          "actionID": "3005"
        },
        {
          "argumentValue": "0.0",
          "name": "Off",
          "actionID": "3005"
        }
      ]
    },
    {
      "heliosType": "DCS.Common.Switch",
      "device": "Gear system",
      "name": "Brake Handle Park/Emergency",
      "description": "Current position of this switch.",
      "exports": [
        {
          "format": "%0.1f",
          "isExportedEveryFrame": false,
          "id": "241"
        }
      ],
      "deviceId": "5",
      "positions": [
        {
          "argumentValue": "1.0",
          "name": "Vertical Left",
          "actionID": "3006"
        },
        {
          "argumentValue": "0.7",
          "name": "Vertical",
          "actionID": "3006",
          "stopActionID": "3006",
          "stopActionValue": "0.5"
        },
        {
          "argumentValue": "0.0",
          "name": "Horizontal",
          "actionID": "3006"
        }
      ]
    }

**Comment by BlueFinBima** [comment]
@davidmontpellier my investigations and endless testing has resulted in a different fix for this
```
    {
      "heliosType": "DCS.Common.Switch",
      "device": "Gear system",
      "name": "Emergency / Parking Brake Handle On/Off",
      "description": "Current position of this switch.",
      "exports": [
        {
          "format": "%0.1f",
          "isExportedEveryFrame": false,
          "id": "240"
        }
      ],
      "deviceId": "5",
      "positions": [
        {
          "exitValue": "0.0",
          "argumentValue": "0.0",
          "name": "Brake Off",
          "actionID": "3005",
          "stopActionID": "3005"
        },
        {
          "exitValue": "1.0",
          "argumentValue": "1.0",
          "name": "Parking Brake On",
          "actionID": "3005",
          "stopActionID": "3005"
        }
      ]
    },
    {
      "heliosType": "DCS.Common.Switch",
      "device": "Gear system",
      "name": "Emergency / Parking Brake Handle Park/Emergency",
      "description": "Current position of this switch.",
      "exports": [
        {
          "format": "%0.3f",
          "isExportedEveryFrame": false,
          "id": "241"
        }
      ],
      "deviceId": "5",
      "positions": [
        {
          "exitValue": "0.000",
          "argumentValue": "0.999",
          "name": "Release",
          "actionID": "3006",
          "stopActionID": "3006",
          "stopActionValue": "0.000"
        },
        {
          "exitValue": "0.666",
          "argumentValue": "0.666",
          "name": "Park",
          "actionID": "3007",
          "stopActionID": "3007",
          "stopActionValue": "0.666"
        },
        {
          "exitValue": "0.000",
          "argumentValue": "0.000",
          "name": "Emergency",
          "actionID": "3007",
          "stopActionID": "3007",
          "stopActionValue": "0.000"
        }
      ]
    },
```
The attached profile contains two switches which when combined, cover all the actions of the parking brake.  While you are correct that the "pull" feature of the control can have intermediate values (it can actually have more than 3 values), I found that two positions were sufficient to cater for this operation in Helios. 
[_1.zip](https://github.com/HeliosVirtualCockpit/Helios/files/10158188/_1.zip)
Many thanks for investigating this and for proposing a solution! 
I expect that this will go out in 1.6.5500.

**Comment by BlueFinBima** [comment]
Just about to complete the release so I'll see if I can get these fixed
myself today.

**Comment by BlueFinBima** [comment]
- [x] Bleed Air Knob
- [ ] Pitot Heater Switch
- [ ] Engine Anti-Ice Switch
- [ ] HUD Symbology Reject Switch
- [ ] HUD Video Control Switch
- [ ] Attitude Selector Switch
- [ ] ALR-67 DIS TYPE Switch
- [ ] SAI/Caging Knob
- [ ] Cage Standby Attitude Indicator

**Comment by BlueFinBima** [comment]
@davidmontpellier thanks, but in the interests of getting the release out, I've committed the entries you told me about this morning, If there are even more changes, then these will have to wait for another release.  It would be useful if you could assess 1.6.5500 to see what additional changes are needed.

**Comment by BlueFinBima** [comment]
@davidmontpellier David,  below is the current status.  I spent way too long on the pitch adjust knob and still could not coax the output binding to behave.  Input binding is fine.  It'll just have to wait (unless you have the magic incantation for a control) which works. 

- [x] Bleed Air Knob
- [x] Pitot Heater Switch
- [x] Engine Anti-Ice Switch
- [x] HUD Symbology Reject Switch
- [x] HUD Video Control Switch
- [x] Attitude Selector Switch
- [x] ALR-67 DIS TYPE Switch
- [ ] SAI/Caging Knob - Partially complete.... simple output binding to this isn't quite there.  It'll have to wait for more time
- [x] Cage Standby Attitude Indicator

**Comment by BlueFinBima** [comment]
Delivered in 1.6.5500.0
