### ISSUE TITLE
cant load profile on newest version of Helios 

### ISSUE THREAD

**Issue by halfassedflightsim** [HeliosVirtualCockpit/Helios#645]
hey just started messing with helios and cant seem to get it to load my profles it keeps saying 

 "timeStamp": "11/13/2022 02:16:19.212 PM",
          "status": "Error loading Profile" 

it would be nice to have some help

**Comment by Todd1215** [comment]
Sadly the documentation isn't complete but there are some good videos on you tube. Visit the Helios [Wiki](https://github.com/HeliosVirtualCockpit/Helios/wiki/Video-Resources-for-Helios) for the links.
