### ISSUE TITLE
"Reload Images" Feature request for Profile Editor

### ISSUE THREAD

**Issue by CEPEGA-81** [HeliosVirtualCockpit/Helios#648]
It would be great to have a option to reload textures in Profile Editor. It happens often while creating new gauges etc. that you need to edit your textures. But as of now, to get Profile Editor to show the updated texture(s) instead of the old version(s) of it, you have to restart Profile Editor and load the your profile to get the programm to show the edited textures.

I think this feature would make life of profile creators much easier.
![Helios Feature Request](https://user-images.githubusercontent.com/118360910/202451995-b2df0b82-84ee-4fcd-96c6-13d084c92377.png)

**Comment by BlueFinBima** [comment]
@CEPEGA-81 What effect does turning this to "off" have on your use case?
![image](https://user-images.githubusercontent.com/18526232/202455118-6411b9de-ed20-4075-8901-47c775e7276e.png)

**Comment by CEPEGA-81** [comment]
sorry, but i have no knowledge of programming at all, i'm not much of help regarding this.

**Comment by Todd1215** [comment]
@CEPEGA-81 I was referring to the control in your profile that isn't refreshing the image when you change it.

**Comment by CEPEGA-81** [comment]
it is not profiles related. What i mean, is if you for example start from scratch, add anything from the toolbox to a monitor and change the image in "Appearence", then jump in Photoshop, make changes to the texture you selected before in "Appearence" and save it. Then you go back to Profile Editor, but it shows still the old, unchanged texture, even after saving the profile and reopen it.

**Comment by BlueFinBima** [comment]
Hi Wheelchock, I was thinking of the situation where the image was changed
(same name) without any changes being made in PE.  I've certainly seen (and
fixed) problems where the control is not updated when there is a property
change, and there are probably more instances of this.
I think we need a better understanding of what the specific scenario is.

**Comment by MadKreator37** [comment]
I have run into this recently. I made a few different versions of a landing gear handle. Took a toggle switch from the toolbox, changed the image(s) to one of my graphics. Messed with it a bit, didn’t like one of them so I changed that image to a different one and it did not change on screen. Even though it showed the correct file name/path, the actual graphic in the editor did not change until I re-started the editor.

**Comment by MadKreator37** [comment]
I'm happy you gentlemen are so intelligent! 🤯 This would be a great update. As I'm getting deep into profile creation, I've come to terms working around it. Closing and re-opening the editor. There's many times where I'm not happy with an image I made and hop back in PS, edit it, then re-assign it. The downfall of it having the same name is it will not refresh automatically and an editor restart is necessary.

**Comment by MadKreator37** [comment]
Yes, I do that quite a bit but it doesn't always re-load the image. As I'm working on p-47 here, I will do a more thorough test on an image to  pinpoint  the exact scenario(s) where helios won't reload an image without a full restart. There are some combinations of re-applying a changed image, saving/opening the profile and re-loading Helios that I will keep track of to try to figure out exactly when the full reboot is required. As of now, Helios doesn't like to show a changed/modified image that is saved using the same name as the image currently applied to something, without a restart. That too may vary depending on what type of control its being applied to. I suppose a more in depth test of each type of control is necessary, along with things like "user image" and gauges from the "custom controls". I've never paid much attention to what the image was applied to. I got it in my head that whenever I modify an image thats already applied to something, restart helios.

**Comment by BlueFinBima** [comment]
As @Todd1215 mentioned earlier, this enhancement request represents wide ranging changes to the controls and gauges.   This said, the commits added cover most of the controls and some of the gauge mechanisms (but I'm not going to claim all).  The commits only apply to Profile Editor, and uses the operating system to detect changed images, and then the altered images are reloaded by Helios the next time that Profile Editor is activated.  This should address this enhancement request in most of the scenarios where an image is being edited externally while the profile is being developed in Profile Editor.

**Comment by MadKreator37** [comment]
You are eternally amazing!

**Comment by BlueFinBima** [comment]
Delivered in 1.6.6040.3
