### ISSUE TITLE
an update export script and associated files must be installed to support this profile in DCS?

### ISSUE THREAD

**Issue by camperbeast1** [HeliosVirtualCockpit/Helios#651]
[Helios has written the report to the file 'Helios_status_report_133132923580600282.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

[Helios_status_report_133132923580600282.txt](https://github.com/HeliosVirtualCockpit/Helios/files/10045664/Helios_status_report_133132923580600282.txt)

**Comment by camperbeast1** [comment]
unrecognized export.lua

**Comment by camperbeast1** [comment]
{
  "product": "Helios",
  "version": "1.6.5400.2",
  "items": [
    {
      "report": [
        {
          "timeStamp": "11/19/2022 05:07:57.113 PM",
          "status": "Unrecognized Export.lua"
        },
        {
          "timeStamp": "11/19/2022 05:07:57.113 PM",
          "status": "Helios cannot understand the Export.lua script\nat %USERPROFILE%\\Saved Games\\DCS.openbeta\\Scripts\\Export.lua.\nIn order to install this version of Helios, you will need to rename this script and then configure this interface again.  Afterwards, you can edit this file again to add your changes.  Alternatively, you can configure Helios not to create Export.lua at all if you have an unusual Export.lua that works with this version of Helios."
        },
        {
          "timeStamp": "11/19/2022 05:04:59.549 PM",
          "severity": 1,
          "status": "The contents of this file did not match any of the patterns we recognize",
          "code": [
            {
              "text": "local wwtlfs=require('lfs')",
              "lineEnding": 1
            },
            {
              "text": "dofile(wwtlfs.writedir()..'Scripts/wwt/wwtExport.lua')",
              "lineEnding": 1
            },
            {
              "text": "local wwtlfs=require('lfs')",
              "lineEnding": 1
            },
            {
              "text": "dofile(wwtlfs.writedir()..'Scripts/wwt/wwtExport.lua')",
              "lineEnding": 0
            }
          ]
        }
      ],
      "name": "Configuration Results"
    }
  ]
}

**Comment by BlueFinBima** [comment]
@camperbeast1 Helios expects the Exports.Lua to be in a format that it knows so that it is able to link in other non-Helios exports by having them declared in Helios Profile Editor.  Did Helios install the export.lua script?  As the message says, you are at liberty to control your export.lua if that is what you want to do, but you take responsibility for supporting it.

```Helios cannot understand the Export.lua script at %USERPROFILE%\Saved Games\DCS.openbeta\Scripts\Export.lua.  In order to install this version of Helios, you will need to rename this script and then configure this interface again. Afterwards, you can edit this file again to add your changes. Alternatively, you can configure Helios not to create Export.lua at all if you have an unusual Export.lua that works with this version of Helios.```
