### ISSUE TITLE
Profile Editor Crash

### ISSUE THREAD

**Issue by BushWookie18** [HeliosVirtualCockpit/Helios#667]
If you are having problems installing / configuring / using a profile then you should use the support process for the provider of that profile.

- [ ] I have read [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)

**Describe the Helios Issue**
When trying to open Premade profile from Capt Zeen, I get the attached error within the Helios profile editor. Program then closes.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**
Profile opens

**Screenshots**
![image](https://user-images.githubusercontent.com/119915954/205821627-e063fd99-f059-4a05-a1cb-5c75b1e89429.png)

**please complete the following information:**
 - Helios Version [eg 1.6.5100.1]
 - DCS Version [e.g. Open Beta 2.8.0.33006]
 - [ x] Profile Editor
 - [ ] Control Center
 - [ ] Keypress Receiver
 - [ ] Something else (*remember to tell us what it is*)

**Additional context**
Add any other context about the problem here.  (*this problem started happening when I ....*)
[Profile Editor Problems.log](https://github.com/HeliosVirtualCockpit/Helios/files/10162805/Profile.Editor.Problems.log)

**Comment by BlueFinBima** [comment]
@BushWookie18 Does profile editor work ok with other profiles?  Have you made any changes to `Eagle Dynamics\DCS World xxxx\autoupdate.cfg` or had other programs making changes to this file?  If not then please provide me with the contents of autoupdate.cfg.  Thanks

**Comment by BushWookie18** [comment]
Hi Blue,

The profile editor only works with custom profiles. I tried downloading
Capt Zeen's F-16 profile and received the same result. I did however find a
resolution. The Helios profile was being stored within DCS stable instead
of DCS open beta. I wasn't aware I still had the files for stable still on
my PC, so once I completely uninstalled stable the profiles worked fine.
Normally I would not have reported a bug but the script/command center said
I should enter one.

Thanks,
BW

**Comment by BlueFinBima** [comment]
@BushWookie18 Thanks for feeding back.  What you describe makes some sense, since the error is that there is a missing or corrupt autoupdate.cfg.  There should be a autoupdate.cfg for each of the DCS instances that Helios has been told about, and I guess that this might not have been the case with one of the instances of DCS on your system.
The exception thrown is not the most graceful way of informing you about the problem so I'll review the code to see if we can do better in the future.

**Comment by BlueFinBima** [comment]
Finally had a chance to review the code.  The exception is probably the safest solution to the problem, however in a similar situation to the one found by you, message `No viewport patches compatible with DCS INVALID_AUTOUPDATE.CFG_VERSION found`  and error `GadrocsWorkshop.Helios.LogManager|The version number "xxxxx" read from "autoupdate.cfg" in DCS installation "C:\Program Files\Eagle Dynamics\DCS World OpenBeta" was either corrupt, or in a format unknown to Helios.  Run DCS repair (slow mode) or reinstall the DCS installation.` will be written to the Profile Editor Error Log.
Commit cfd13b75 introduces this behaviour .

**Comment by BlueFinBima** [comment]
Delivered in 1.6.6010.4
