### ISSUE TITLE
Self manage config files "are you sure" menu

### ISSUE THREAD

**Issue by MrBuzzKillington** [HeliosVirtualCockpit/Helios#678]
When you uncheck a file from the config manager to tell helios you will self manage this file and that it should stop checking for it you get a pop-up that says are you sure you want to do this.  It happens for every single file you uncheck. With the new scripting purity checks I want to only let helios manage the ones I absolutely need but its maddening to have to click the yes im sure button for every single file. can you improve this with maybe a checkbox or something that lets me say dont show this again?

**Comment by BlueFinBima** [comment]
The commit referenced above displays the warning message only once for each batch of unchecks.  The warning will appear again on the first uncheck following a patch getting checked.

Awaiting delivery

**Comment by BlueFinBima** [comment]
Shipped in 1.6.5700.0
