### ISSUE TITLE
Radio selectors not in the correct positions

### ISSUE THREAD

**Issue by derammo** [HeliosVirtualCockpit/Helios#68]
* created by @BlueFinBima on 2018-06-24 11:09:54 +0000 UTC

AV-8B

### comment by @BlueFinBima on 2018-06-24 13:46:05 +0000 UTC

This will be a profile problem, so dropping this back to a ToDo

### please make sure to close upstream issue when this item is closed

**Comment by BlueFinBima** [comment]
Tested with 1.6.611 and DCS 2.9.8.1214 and the problem appears to have been resolved.
