### ISSUE TITLE
F-18 FLIR switches

### ISSUE THREAD

**Issue by kcharlie2** [HeliosVirtualCockpit/Helios#680]
Sorry for posting a git issue, but I couldn't find another way to contact you developers :)

Is there a possibility of getting an F-18 interface for the FLIR switches, specifically the "FLIR", "LDT/R", and "LST/NFLR" on the right panel? They're the only switches need to make the F-18 really feel complete in my opinion.

**Comment by BlueFinBima** [comment]
Fixed in commit 65b9d36c which will go out in the next release of Helios.  
@kcharlie2 I responded to you on Discord.

**Comment by BlueFinBima** [comment]
Awaiting delivery

**Comment by kcharlie2** [comment]
Amazing thank you!

**Comment by BlueFinBima** [comment]
Shipped in 1.6.5700.0

**Comment by BlueFinBima** [comment]
Shipped in 1.6.5700.0
