### ISSUE TITLE
Helios Error Please help

### ISSUE THREAD

**Issue by Busterheiman** [HeliosVirtualCockpit/Helios#684]
[Helios has written the report to the file 'Helios_status_report_133165037147568247.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

[Helios_status_report_133165037147568247.txt](https://github.com/HeliosVirtualCockpit/Helios/files/10301570/Helios_status_report_133165037147568247.txt)

**Comment by Busterheiman** [comment]
![image](https://user-images.githubusercontent.com/106287965/209502767-1863433b-e544-49fb-9dbf-cc324c311e00.png)
![image](https://user-images.githubusercontent.com/106287965/209502790-494fc5cb-0a3d-42d7-815a-455188c46aad.png)

screen shot of error

**Comment by Busterheiman** [comment]
I have tried running Helios as admin with the same results.

**Comment by BlueFinBima** [comment]
@Busterheiman basically Windows is not allowing access to one of Helios' control files 
![image](https://user-images.githubusercontent.com/18526232/209527068-d3e5c1c0-6e37-4f04-9fdb-edd598e643e6.png)
Do you have the file mentioned in the above image open in another program or process?  Did a restart of windows change the problem?

**Comment by BlueFinBima** [comment]
@Busterheiman 
You also have some strange messages in the log which seems to relate to you defining 3 800x600 displays (MFD's?).  Have you changed your MonitorSetup recently?

**Comment by BlueFinBima** [comment]
Closing "More Info Needed"
