### ISSUE TITLE
Profile Editor - Controls LayoutPropertyEditor returns "Name cannot be blank" for all Name Validations

### ISSUE THREAD

**Issue by linknetx** [HeliosVirtualCockpit/Helios#686]
**Profile Editor - Controls LayoutPropertyEditor**

The name validation should return the validation text associated with the respective error, however it returns the same error message "Name cannot be blank" for all of the following cases:
1. "Name cannot be blank."
2. "Name must not contain special characters."
3. "Name must be unique."

       string IDataErrorInfo.this[string columnName]
        {
            get
            {
                if (!columnName.Equals("VisualName"))
                {
                    return null;
                }
                if (string.IsNullOrWhiteSpace(VisualName))
                {
                    return "Name cannot be blank.";
                }
                if (!Regex.IsMatch(VisualName, "^[a-zA-Z0-9_ ]*$"))
                {
                    return "Name must not contain special characters.";
                }
                if (Control != null && Control.Parent != null && !VisualName.Equals(Control.Name) &&
                    Control.Parent.Children.ContainsKey(VisualName))
                {
                    return "Name must be unique.";
                }
                return null;
            }
        }
The problem seems to be that all of the validations work but the xaml validation then returns a blank string therefore the result is a "Name cannot be blank." error message for all cases.

Also in view of the fact that many of the controls have a dash in their name would it not be better to allow a dash in the names rather than exclude it?

![2022-12-27_125244](https://user-images.githubusercontent.com/25765532/209670975-63741237-132e-40ba-85dd-077d92f9f482.jpg)

**Comment by Todd1215** [comment]
I agree with the 'dash' in the name. It's currently not breaking any functionality so why not just let it be valid?

**Comment by linknetx** [comment]
Issue fixed with PR #689

**Comment by BlueFinBima** [comment]
Shipped in 1.6.5700.0
