### ISSUE TITLE
Generic Viewport MFCD export not working with AV8BNA

### ISSUE THREAD

**Issue by JLeslie1004** [HeliosVirtualCockpit/Helios#696]
Not sure if this is a bug, version patch issue, or ID10T error on my end. 

I have a 3 monitor setup and have successfully used Helios 1.4 and earlier, and am just getting back into DCS with Helios 1.6. I followed the instructions in Derammo's video "DCS Viewport Exports Only" because that's exactly what I want - left MFCD on my left monitor and right MFCD on my right monitor. Using the "generic aircraft left/right MFCD" files worked just fine on all my aircraft EXCEPT for the AV8BNA. Creating another profile the same way using the AV8BNA MFCD files instead of the generic ones now gives me the red errors that the files need patched. I can clear the checkbox on needs patched which also clears the red warnings, but I still can't get the MFCD's to project when using the AV8BNA.

**Comment by BlueFinBima** [comment]
@JLeslie1004 Hi Jeff, nobody likes filling in a template, I get it.  But the template is there to help you.

If you are having problems installing / configuring / using a profile then you should use the support process for the provider of that profile.
- [ ] I have read [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)

There is a community available to help with these sorts of issue.

The most likely cause of the patch not going onto the AV-8B is that the files have already been changed.  In the wiki page the template asks you to read... there is a section which covers this.  See [3 if apply patches fails with an error saying the patches dont fit](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help#3-if-apply-patches-fails-with-an-error-saying-the-patches-dont-fit-this-version-of-dcs-and-to-get-new-ones)

**Comment by BlueFinBima** [comment]
If working through the getting help indicates that there is an issue with Helios, by all means reopen this issue.
Closing as "More Info Needed"
