### ISSUE TITLE
Bug with BMS 4.37

### ISSUE THREAD

**Issue by MadFlyFFW01** [HeliosVirtualCockpit/Helios#697]
[Helios has written the report to the file 'Helios_status_report_133176740276670585.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

[Helios_status_report_133176740276670585.txt](https://github.com/HeliosVirtualCockpit/Helios/files/10369105/Helios_status_report_133176740276670585.txt)

The line indicated in bug report starts with
<Interaction>
                    <AllowInteraction>True</AllowInteraction>
                  </Interaction>

At this point I can not use it anymore.
Best regards

**Comment by MadFlyFFW01** [comment]
Issue started after installation of vesion 1.67.
Returned to Helios version 1.6.5101.0000.
Nos change , the issue's still here.

**Comment by MadFlyFFW01** [comment]
![image](https://user-images.githubusercontent.com/122226800/211211664-fcef2c62-40e1-4b04-92b7-558fc41571c6.png)

**Comment by MadFlyFFW01** [comment]
initially
![image](https://user-images.githubusercontent.com/122226800/211211732-d5faa683-7680-4684-8081-d948797bfd94.png)

**Comment by linknetx** [comment]
Can you could post a link to the "WIP 437 BMS TO taxiway.hpf" profile which appears to be giving the problem.

**Comment by MadFlyFFW01** [comment]
i tried an DCS pofile which has the same issue
[UH-1H_v3.0b.zip](https://github.com/HeliosVirtualCockpit/Helios/files/10369433/UH-1H_v3.0b.zip)
[WIP 437 BMS TO taxiway.zip](https://github.com/HeliosVirtualCockpit/Helios/files/10369434/WIP.437.BMS.TO.taxiway.zip)

**Comment by linknetx** [comment]
Apart from the warnings regarding missing images the "WIP 437 BMS TO taxiway.hpf" still runs but with an exception for missing images in the [F16GaugePack] which hasn't been included in any Helios version for several years, That's an extremely old profile. I can't test the DCS profile since I don't have DCS installed.

**Comment by BlueFinBima** [comment]
@linknetx  I think at one time (1.3?) Gadroc was going to (or did) sell additional packs in DLL form and this might be one of them.   It certainly does not get shipped with Helios 1.4 and up.
One of the errors seems to be on interaction for an indicator. 
```
                  <Interaction>
                    <AllowInteraction>True</AllowInteraction>
                  </Interaction>
```
If the profile was created **or saved** at 1.6.5700 and then opened on 1.6.5100 - then https://github.com/HeliosVirtualCockpit/Helios/issues/697#issuecomment-1374892984 this would be the result.

**Comment by linknetx** [comment]
@BlueFinBima The FalconInterface is installed in the profile which caused the initial error so as you suspect it might well be registry related. If so this has been fixed in PR #695 in an as yet to be released version of Helios.

@MadFlyFFW01 Can you check the following registry entry to determine if it has any subkeys.

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Benchmark Sims

So in the Benchmark Sims key there should be at least one subkey of the form Falcon BMS 4.33, Falcon BMS 4.34, Falcon BMS 4.35 and so on.

**Comment by MadFlyFFW01** [comment]
> Apart from the warnings regarding missing images the "WIP 437 BMS TO taxiway.hpf" still runs but with an exception for missing images in the [F16GaugePack] which hasn't been included in any Helios version for a number of years, That's quite an old profile. I can't test the DCS profile since I don't have DCS installed.
> 
> I think the F16GaugePack.dll may have been an add-on for an earlier version of Helios. Check in the Helios installation folder C:\Program Files\Helios Virtual Cockpit\Helios\Plugins to see if it exists.

I confirm that this warning has not effect on the current issue

**Comment by MadFlyFFW01** [comment]
i removed the instructons not supported such as <ScalingMode> and <Interaction>.
So it worked again.

I am able to generate a new issue if I used some older keystroke (.key files).
It seems there's a lead to follow.

**Comment by linknetx** [comment]
@MadFlyFFW01 That runs perfectly with no issues in Helios 1.6.5700 therefore can we consider this problem resolved and close the issue. You can always reopen it if you get further problems.

**Comment by MadFlyFFW01** [comment]
no it doesn't work.
The program stops with an error messge when I try to affect a send call back binding.
![image](https://user-images.githubusercontent.com/122226800/211659770-ff592f42-e000-49c4-94ca-c622ffec6a01.png)

**Comment by linknetx** [comment]
@MadFlyFFW01 There must be a problem with the key file you're using. The profile you have just sent doesn't have any problem with the standard BMS Full key file. It would help if you could post a link to the key file that is giving the problem.

**Comment by MadFlyFFW01** [comment]
that's why I mentionned a possible pb with the key file yesterday ;)
[mad fly 437 pitbuilder.zip](https://github.com/HeliosVirtualCockpit/Helios/files/10386937/mad.fly.437.pitbuilder.zip)

**Comment by linknetx** [comment]
@MadFlyFFW01 
You've added this line which is in the incorrect format for a comment:

“======== NEW 4.37.0 FUNCTIONS ========”

I should look like this:

#======== NEW 4.37.0 FUNCTIONS ========#

After removing that line the key file loaded fine.

**Comment by MadFlyFFW01** [comment]
well done Sir
I copied this line directly from BMS , I assumed this was correct.
Thx.

**Comment by linknetx** [comment]
The issue was due to a line that had been added to the key file in an incorrect format for a comment.

**Comment by BlueFinBima** [comment]
Delivered in 1.6.5800
