### ISSUE TITLE
Log Error from Export lua

### ISSUE THREAD

**Issue by TheHornetProject** [HeliosVirtualCockpit/Helios#704]
I keep getting this master caution warning in helios.  Unfortunately i don't know the trigger but i do know at least 10 secs into every flight it will happen.  so very consistent.  I don't notice any adverse effects in game,  helios continues to run.

[Helios_status_report_133192963082093376.txt](https://github.com/HeliosVirtualCockpit/Helios/files/10518822/Helios_status_report_133192963082093376.txt)

**Comment by BlueFinBima** [comment]
@TheHornetProject Did you have a look at the status report?
```
          "status": "Error received from Export.lua: \"thirdparty LuaExportBeforeNextFrame[string \"%USERPROFILE%\\Saved Games\\DCS.openbeta\\Scri",
          "flags": 4,
          "fullText": **"Error received from Export.lua: \"thirdparty LuaExportBeforeNextFrame[string \"%USERPROFILE%\\Saved Games\\DCS.openbeta\\Scripts\\DCS-BIOS\\lib\\Util.lua\**"]:478: attempt to compare nil with number\""

```
Problem is spotted by Helios, but is in `DCS-BIOS\\lib\\Util.lua`

**Comment by BlueFinBima** [comment]
Closing as more info required but supplied information suggests this is a problem with DCS-BIOS.
