### ISSUE TITLE
Helios DCS Monitor Setup should allow configuration of extremely wide monitors

### ISSUE THREAD

**Issue by BlueFinBima** [HeliosVirtualCockpit/Helios#708]
Currently DCS (or possibly GPU stack) seems to have a hard limit on the screen width for the DCS 3D view of 8192.  In such situations, there should be an option for DCS to limit the width of the DCS 3D view being configured in the "center" viewport to a maximum value and to centralize  the DCS 3D view to the left, center or right of the real monitors.

Example:  monitor setup comprising 2560x1440, 3440x1440, 2560x1440 in horizontal setup.  Combined screen size of 8560x1440.  An ideal configuration for center viewport might be x = 184, y = 0, width = 8192, height = 1440 so the 8192 is central on the real monitors.

There are reports of visual artifacts when running at 8192, so the maximum width should ultimately be user configurable.

**Comment by ayusoff01** [comment]
![helios issues wide screen 2](https://github.com/HeliosVirtualCockpit/Helios/assets/63418957/3b79cc85-27c7-4b7f-8050-352bf25fe66f)
![helios issues wide screen 1](https://github.com/HeliosVirtualCockpit/Helios/assets/63418957/f24fbec7-9b8a-47b1-b1de-80dec0fec577)

**Comment by BlueFinBima** [comment]
@ayusoff01 when you say "Triple Monitor" do you mean "3camera" or something else?  
Ultimately, I think you're confirming that the single display mode supported by DCS Monitor Setup has the same limitation in 2160p - which is not a Helios limitation - as described as the main issue which was 1440p.

**Comment by ayusoff01** [comment]
Yes, I meant 3 Screens

**Comment by NoLegalMoves129** [comment]
I am new to Helios so would like some help in determining whether my use case is supported. I've worked on it for a couple of weeks and ready to give up at this point..
I have a triple 4k TV cockpit view and an additional 3 small screens for MFCDs (for the FA/18)
I tried configuring Helios with or without Nvidia surround and variations of various resolutions. What works is triple screen (triple 4k) with the '3 screens' option in DCS. I managed to setup the 4 MFCDs and display them in game but it's always blacking out my right most 4k screen and compressing the view into the 2 left most TVs. Any use cases identical to mine out there that do work? (My research online always only yields simplified, lower resolution examples)

**Comment by BlueFinBima** [comment]
@NoLegalMoves129 To this point in time, you've been asking your questions in the correct place, and I have been reading your updates but have nothing really to add to the advice you've received.  
Commenting on an issue which is clearly framed, to ask for assistance on something else is not appropriate, but I do understand how keen you are to get an answer.  
I suggest you continue to refine your experiments showing what does and does not work and continue the discussion in CZ's forum.
