### ISSUE TITLE
New version HELIOS 

### ISSUE THREAD

**Issue by Chonaa340** [HeliosVirtualCockpit/Helios#714]
[Helios has written the report to the file 'Helios_status_report_133208232023694528.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

[Helios_status_report_133208232023694528.txt](https://github.com/HeliosVirtualCockpit/Helios/files/10728814/Helios_status_report_133208232023694528.txt)

**Comment by BlueFinBima** [comment]
@Chonaa340 I refer you to the text you just posted... "**replace this message with a description of the problem you are reporting.**"

Please also check the status reports before submitting an issue.  The following recommendations are contained within the status report:
```
          "status": "Windows reports a scaling value of 100% (96 dpi)",
          "recommendation": "This version of Helios does not support using different display scaling (DPI) on different monitors.  Make sure you use the same scaling value for all displays."

          "status": "Monitor configuration in profile does not match this computer",
          "recommendation": "Perform 'Reset Monitors' function from the 'Profile' menu"
```

and multiple messages recommending that you install patches to your system.

for example 
```
          "status": "DCS installation in 'K:\\DCS ALL\\DCS World 2.5\\DCS World OpenBeta' is missing some patches in mods\\Aircraft\\A-10C\\Cockpit\\Scripts\\AN_ALR69V\\indicator\\AN_ALR69V_init.lua",
          "recommendation": "Apply patches"
```
