### ISSUE TITLE
Request: Add support for the MH-60R

### ISSUE THREAD

**Issue by ANDR0ID-DCS** [HeliosVirtualCockpit/Helios#717]
Requesting Helios support the MH-60R mod. 

As the MH-60R mod is based off of the UH-60L I believe this request will only require updating the aircraft name from UH-60L to MH-60R for the appropriate Helios files. The MH-60R should be using the same device names/numbers & arguments. This update would allow for more than basic telemetry for the MH-60R, such as exporting the navigation system screen, etc. 

Mod link: https://drive.google.com/drive/folders/1cWuCRfE_Npqpx3HPwlp4XY5AeMcj6zzL?usp=sharing 

Thanks for your consideration.

**Comment by BlueFinBima** [comment]
@ANDR0ID-DCS I can't promise anything, but I'll certainly take a look.

**Comment by ANDR0ID-DCS** [comment]
Thanks for being willing to take a look... happy to assist if able.

**Comment by BlueFinBima** [comment]
@ANDR0ID-DCS  I've just spent the last two days investigating.  The command numbers are similar but not exactly the same as the level of UH-60L (1.3.1 I think was the level I originally built the interface against) from what I've determined while exploring, so I was not super confident about diving in and creating a common parent interface for both the Blackhawk and Seahawk on the grounds of what I've seen so far.  I have a prototype interface now, but I'm running out of time to "kick the tyres", and I have not yet gotten around to installing the Seahawk.   I'm hoping to carve out a couple of hours tomorrow to do some of that.
I'm not at the stage yet where I can do a dev build of Helios, but I will let you know when there is one available.  
Do you know if there is a Helios profile available for the Blackhawk?  Having one might make the job of testing that little bit easier.

**Comment by ANDR0ID-DCS** [comment]
I have a very basic profile I use for the UH-60L that I can attach later today. Thanks again for looking into it.

**Comment by ANDR0ID-DCS** [comment]
[UH60L Profile Files.zip](https://github.com/HeliosVirtualCockpit/Helios/files/10829735/UH60L.Profile.Files.zip)

My basic profile that I use at the moment for the UH-60L.

**Comment by BlueFinBima** [comment]
@ANDR0ID-DCS I have been so close on several occasions to throwing this whole interface in the dust-bin.  The profile you provided is - as you say - "very basic" and cannot be used to test the interface.
Because there are many differences between UH-60L and MH-60R (some might be needed, some may be bugs in the mod) the interface really does need a thorough test, which typically only happens when a full profile is built (and I simply do not have the time to do this).

You requested this support so how much effort are you willing to put in to get this interface fully tested and operational?

**Comment by ANDR0ID-DCS** [comment]
Happy to help as my skills & time allow. 

How full is full profile? I don't have the time or skill to make something on the order of Capt Zeen's profiles. With the UH-60L components, like the navigation system, outputs already in the helios profile editor I assumed this should be a relatively simple aircraft ID replacement as the systems/devices should be the same between the mods (ie where the data is being pulled from). 

I haven't looked into how helios is programed in depth to understand how this is done, but am willing to learn/try to teach myself as well if you can point me to the correct files to examine.

**Comment by BlueFinBima** [comment]
Delivered in 1.6.6010.4.  This interface is a JSON interface, and is "user supported" (ie you should not raise any issues against the Helios project, but feel free to fix any issues in the JSON file and contribute them back in the [Helios Interfaces Project](https://github.com/HeliosVirtualCockpit/HeliosInterfaces) )
