### ISSUE TITLE
Profile Editor -> Invalid viewport name breaks Helios.lua file

### ISSUE THREAD

**Issue by MaxGuillen** [HeliosVirtualCockpit/Helios#721]
**Describe the Helios Issue**
Profile Editor -> Invalid viewport name breaks Helios.lua file

**To Reproduce**
1. Profile Editor 
2. Add a viewport with a name containing whitespace as separator like "My viewport"
3. Save and make sure Helios.lua file is regenerated

**Expected behavior**
In Helios.lua file a viewport variable name "My Profile = { .... }" will be created with the whitespace invalidating the file.

**please complete the following information:**
 - Helios all
 - DCS all
 - [ ] Profile Editor

**Solution**
Add a validation to the Viewport name textbox making sure it does not contain white spaces or any other invalid character for lua variable names

**Comment by BlueFinBima** [comment]
Thanks for reporting this.  I'll taker a look.

**Comment by BlueFinBima** [comment]
Awaiting Delivery

**Comment by BlueFinBima** [comment]
Delivered in 1.6.6000.0
