### ISSUE TITLE
wont install patches

### ISSUE THREAD

**Issue by vinceouida** [HeliosVirtualCockpit/Helios#722]
[Helios has written the report to the file 'Helios_status_report_133224034509255863.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

{
  "product": "Helios",
  "version": "1.6.5900.1",
  "items": [
    {
      "report": [
        {
          "timeStamp": "03/04/2023 01:37:45.297 PM",
          "status": "Helios viewport patches installation failed"
        },
        {
          "timeStamp": "03/04/2023 01:37:45.297 PM",
          "status": "Some patches failed to be written"
        },
        {
          "timeStamp": "03/04/2023 01:37:20.475 PM",
          "status": "mods\\Aircraft\\F14\\Cockpit\\Scripts\\UHF_Radio\\Indicator\\RemotePilot\\init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta'; ignoring patch"
        },
        {
          "timeStamp": "03/04/2023 01:37:20.477 PM",
          "status": "mods\\Aircraft\\F14\\Cockpit\\Scripts\\UHF_Radio\\Indicator\\RemoteRIO\\init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta'; ignoring patch"
        },
        {
          "timeStamp": "03/04/2023 01:37:20.477 PM",
          "status": "mods\\Aircraft\\F14\\Cockpit\\Scripts\\VHF_Radio\\Indicator\\Main\\init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta'; ignoring patch"
        },
        {
          "timeStamp": "03/04/2023 01:37:20.477 PM",
          "status": "mods\\Aircraft\\F14\\Cockpit\\Scripts\\VHF_Radio\\Indicator\\RemotePilot\\init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta'; ignoring patch"
        },
        {
          "timeStamp": "03/04/2023 01:37:20.480 PM",
          "status": "mods\\Aircraft\\Mirage-F1\\Mirage-F1_Common\\Radar_Cyrano_IV_legacy\\Indicator\\Main\\CyranoLegacy_init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta'; ignoring patch"
        },
        {
          "timeStamp": "03/04/2023 01:37:20.480 PM",
          "status": "mods\\Aircraft\\SA342\\Cockpit\\Radio\\Indicator\\UHF\\init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta'; ignoring patch"
        },
        {
          "timeStamp": "03/04/2023 01:37:20.480 PM",
          "status": "mods\\Aircraft\\SA342\\Cockpit\\RWR\\indicator\\init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta'; ignoring patch"
        },
        {
          "timeStamp": "03/04/2023 01:37:20.480 PM",
          "status": "mods\\Aircraft\\SA342\\Cockpit\\TV\\Indicator\\init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta'; ignoring patch"
        },
        {
          "timeStamp": "03/04/2023 01:37:20.480 PM",
          "status": "mods\\Aircraft\\SA342\\Cockpit\\WP1\\init.lua does not exist in DCS installation in 'C:\\Program Files\\Eagle Dynamics\\DCS World OpenBeta'; ignoring patch"
        },
        {
          "timeStamp": "03/04/2023 01:37:23.000 PM",
          "severity": 2,
          "status": "The elevated process C:\\Program Files\\Helios Virtual Cockpit\\Helios\\HeliosPatching.exe failed in an unexpected way",
          "recommendation": "Please file a bug"
        }
      ],
      "name": "Configuration Results"
    }
  ]
} #

**Comment by BlueFinBima** [comment]
@vinceouida please read the instructions above which say " and replace this message with a description of the problem you are reporting"
Please also review the wiki, especially section 3. https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help#3-if-apply-patches-fails-with-an-error-saying-the-patches-dont-fit-this-version-of-dcs-and-to-get-new-ones

**Comment by BlueFinBima** [comment]
Closing as More Info Needed (and nothing forthcoming)
