### ISSUE TITLE
some patches failed to be written.

### ISSUE THREAD

**Issue by vinceouida** [HeliosVirtualCockpit/Helios#724]
[Helios has written the report to the file 'Helios_status_report_133224986293999501.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

[Helios_status_report_133224986293999501.txt](https://github.com/HeliosVirtualCockpit/Helios/files/10891971/Helios_status_report_133224986293999501.txt)

**Comment by BlueFinBima** [comment]
@vinceouida I'm closing this as a duplicate of #722 and the fact that there was no response from the raiser to my reply.  Please read the instructions above which say " and replace this message with a description of the problem you are reporting"
Please also review the wiki, especially section 3. https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help#3-if-apply-patches-fails-with-an-error-saying-the-patches-dont-fit-this-version-of-dcs-and-to-get-new-ones
