### ISSUE TITLE
P-51D variant “P-51D-30-NA” does not work with CaptnZeen p-51D profile 

### ISSUE THREAD

**Issue by MadKreator37** [HeliosVirtualCockpit/Helios#734]
# HELP US TO HELP YOU

If you are having problems installing / configuring / using a profile then you should use the support process for the provider of that profile.

- [ ] I have read [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)
---
### Describe the Helios Issue
The p-51D profile does not work with the p-51D-30-NA variant without manually adding the name to the helios/mods/p-51d.lua. When doing that, however the profile will not load without disabling “preflight check”. Although disabling preflight check does allow the profile to run and work with all-51 variants. 

### Steps to Reproduce the problem
Steps to reproduce the behaviour:
-start default p-51 profile
-create fast mission with p-51d-30-na as selected aircraft- error given and profile will not function
- manually edit savedgames/dcs.openbeta/scripts/helios/mods/p-51d.lua- add ;P-51D-30-NA to line 6
- Start control center- preflight check warning
- Disable preflight check and create new fast mission with any p-51 variant and the profile works
- * by doing so, the editor wants you to “setup DCS” again, but it will over-write and delete the name you added, causing the -30-NA variant to not function again.
- 
### Expected behavior
Profile updated to work natively with p-51D, TF-51D, and P-51D-30-NA variants

### Please complete the following information:
 - Helios Version 1.6.6.002
 - DCS Version: Most recent version openbeta
 -

### The problem happened while using 
(place an 'x' between the square brackets for all that apply)
 - [ x] Profile Editor
 - [x ] Control Center
 - [ ] Keypress Receiver
 - [ ] Something else (*remember to tell us what it is*)

**Comment by BlueFinBima** [comment]
@MadKreator37 what you're describing is not a Helios issue.  The Lua file you're describing is created from content within the actual profile itself.  Using `P51_v3.0b.hpf` as the example, at line 8264, there is the following instruction:
```
Helios_P51.Name = "P-51D;TF-51D"
```
I suspect that changing that line to 
```
Helios_P51.Name = "P-51D;TF-51D;P-51D-30-NA"
```
might improve the situation.  You might have to delete the current lua file from the mods directory (or you might not).

Ultimately, this is a change which needs to be made by the profile developer.
