### ISSUE TITLE
"RESET MONITOR" OPTION Returns an Error Message After Monitor Reconfig.  

### ISSUE THREAD

**Issue by JollyGreenFE** [HeliosVirtualCockpit/Helios#735]
After swapping monitors around I opened an A-10C II Helios profile in order to reset the monitors.  Received a message stating "Error encountered while resetting monitors: Object reference not set to an instance of an object."  After acknowledging the message, DCS Monitor Setup under the Interface Status states under Recommendations "This version of Helios does not support using different display scaling on different monitors.  Make sure you use the same values for all displays."  

One monitor is a 4k, while the other 2 are 1920 x 1080, and *all* monitors are scaled to 100%!  

A status report is attached.  
[Helios_status_report_133285193014697070.txt](https://github.com/HeliosVirtualCockpit/Helios/files/11471292/Helios_status_report_133285193014697070.txt)

**Comment by BlueFinBima** [comment]
@JollyGreenFE Apologies in the delay to respond to this.  The status report does not contain sufficient information to identify this type of problem.  Can you upload `%userprofile%\Documents\Helios\Profile Editor Problems.log` which might provide a little more information.  If you can reproduce, I'll take `%userprofile%\Documents\Helios\Profile Editor.log` as well (from the Profile Editor run which showed the problem).

**Comment by BlueFinBima** [comment]
Closing as more info is needed and none is forthcoming
