### ISSUE TITLE
Viewports are not tracked automatically issue

### ISSUE THREAD

**Issue by szved** [HeliosVirtualCockpit/Helios#736]
### Describe the Helios Issue
* Facing the warnings and incorrect panels displays in the most recent versions of Helios/DCS. Have been running the same configuration (hardware/monitors/Helios/profile) successfully before the software upgrades.
Also have another identical setup where the issue appeared in the vanilla setup of the most recent Helios/DCS/profile versions.*

### Steps to Reproduce the problem
1. *Open 'Helios Control Center'*
1. *Select 'F16C_v1.1b' profile, default unchanged captzeen profile installed via Helios*
2. *Ensure Console switch is ON*
3. *Click on 'START' button*
4. *Notice WARN 'Master caution'*
5. *See (5) errors of type '`The [viewportname] is not tracked automatically because it is contained within a gauge, control or panel. ...`'*
6. *Note same warning displayed in 'Helios Profile Editor > DCS Monitor Setup' with profile opened*

### Expected behavior
*Cockpit panels are loaded correctly and no caution warning displayed*

### Screenshots
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/2970693/96855d62-4238-4d64-91b2-80ad84b4706d)

---
[Helios_status_report_133287441812517594.txt](https://github.com/HeliosVirtualCockpit/Helios/files/11492162/Helios_status_report_133287441812517594.txt)

---

### Helios and DCS versions
 - Helios Version *1.6.6002.0000
 - DCS Version *DCS World 2.8.4.39731*

### The problem happened while using 
 - [x] Profile Editor
 - [x] Control Center
 - [ ] Keypress Receiver
 - [ ] Something else

**NOTE**
Thank you guys for your excellent work with Helios! 👏
Will be trying to roll back every component version (besides DCS as not sure if it allows for downgrades) to narrow down the issue root cause meanwhile. Any more precise troubleshooting steps much appreciated.

**Comment by szved** [comment]
UPD:
1. Workaround for the original issue is moving all viewports from Main_panel of the profile directly to the Monitor 2 in my case. Looked up in the 'f-16-viper' channel of CaptZeen Helios profiles, huge thanks MadKreator37. The root cause seems not a Helios defect, but rather a profile support/display issue.
2. Still the DED frame top looks trimmed, differs from display in Helios Profile Editor visualization - needs further research; and I'm a complete newbie to Helios - would appreciate any cues to troubleshooting.
3. Another thing noticed while investigating this one - when OSB is pressed on any MFD as small white rectangle briefly flashes next to it on the display which seems a new issue. Also will research and potentially extract to a separate thread.

**Comment by BlueFinBima** [comment]
@szved 

1. this is mostly a Helios defect which has been addressed, although viewports which are not directly on the monitor are still not tracked for changes afd562373f91e20b8249bf06e66542a7573023b1 and 498c146b54f2f5484c66fee7c16f3226a77caaed

Github issues should only describe a single issue but I'll comment this one time....

2. This seems to be a Windows task bar issue.. maybe hide it?
3. Seems unlikely to be related to Helios.  Either this is a profile issue, or possibly something related to a touch screen visualisation?

**Comment by BlueFinBima** [comment]
Closing as more info needed and none was forthcoming
