### ISSUE TITLE
when starting helios and runing profile i get this error. I am also using comunity version of vaicom pro

### ISSUE THREAD

**Issue by hreich11** [HeliosVirtualCockpit/Helios#738]
{
  "product": "Helios",
  "version": "1.6.6002.0",
  "items": [
    {
      "report": [
        {
          "timeStamp": "06/04/2023 11:18:31.830 AM",
          "severity": 2,
          "status": "Error received from Export.lua: \"thirdparty LuaExportBeforeNextFrame[string \"%USERPROFILE%\\Saved Games\\DCS.openbeta\\Scr",
          "flags": 4,
          "recommendation": "Log message was shortened.  See application log for details.",
          "fullText": "Error received from Export.lua: \"thirdparty LuaExportBeforeNextFrame[string \"%USERPROFILE%\\Saved Games\\DCS.openbeta\\Scripts\\VAICOMPRO\\VAICOMPRO.export.lua\"]:61: attempt to call method 'Alt' (a nil value)\""
        }
      ],
      "name": "Control Center Console"
    }
  ]
}
++++++++++++++++++++++++++++++++++++++++++++++
when starting helios and runing profile i get this error. I am also using comunity version of vaicom pro

**Comment by BlueFinBima** [comment]
@hreich11 Has Viacom pro's exports been defined in the DCS aircraft tab in a similar manner to the screen shot below?
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/18526232/28b47898-a47b-4c04-8c5b-42a1fe1642ba)
 If so, some programs' exports files play nicer with other exports than other ones.
 Does making `VAICOMPRO\VAICOMPRO.export.lua` the last of the third party files make any difference to the problem.
 Ultimately, the error (line 61 of VAICOMPRO\VAICOMPRO.export.lua) seems to relate to what is happening internally within  VAICOMPRO.export.lua so maybe asking VAICOMPRO's support forum about the issue would be a good place to go.

**Comment by BlueFinBima** [comment]
Closing as more info is needed, and since none was forthcoming this issue cannot be progressed.
