### ISSUE TITLE
CHANGE THIS TITLE TO SOMETHING MEANINGFUL

### ISSUE THREAD

**Issue by DOFInteract** [HeliosVirtualCockpit/Helios#740]
# HELP US TO HELP YOU
## Change the title text to something relevant and follow the instructions below.

If you are having problems installing / configuring / using a profile then you should use the support process for the provider of that profile.

- [ ] I have read [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)
---
## *[Helios has written the report to the file* `Helios_status_report_133341468799745010.txt` *and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]*

---
### Describe the Helios Issue
*A clear and concise description of what the bug is, when it started to happen and any recent changes.*

### Steps to Reproduce the problem
Steps to reproduce the behaviour:
1. *Go to '...'*
2. *Click on '....'*
3. *Scroll down to '....'*
4. *See error*

### Expected behavior
*A clear and concise description of what you expected to happen.*

### Screenshots
*If applicable, add screenshots to help explain your problem.*

### Please complete the following information:
 - Helios Version [eg *1.6.6002.0*]
 - DCS Version [e.g. *Open Beta 2.7.16.28111*]
 - BMS Version

### The problem happened while using 
(place an 'x' between the square brackets for all that apply)
 - [x] Profile Editor
 - [ ] Control Center
 - [ ] Keypress Receiver
 - [ ] Something else (*remember to tell us what it is*)

### Additional context
*Add any other context about the problem here.  (eg this problem started happening when I ....)*

**Comment by DOFInteract** [comment]
Help me I can't install DCS viewport patches
[Helios_status_report_133341468799745010.txt](https://github.com/HeliosVirtualCockpit/Helios/files/12079179/Helios_status_report_133341468799745010.txt)

**Comment by DOFInteract** [comment]
Help me I can't install DCS viewport patches
[Helios_status_report_133341468799745010.txt](https://github.com/HeliosVirtualCockpit/Helios/files/12079190/Helios_status_report_133341468799745010.txt)
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/139863672/f011a746-aafd-42d2-a0bd-664358820bab)

**Comment by BlueFinBima** [comment]
** HELP US TO HELP YOU **
Please read the instructions for raising an Issue when opening an issue.

> [] I have read [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)

At the "getting help" link, you'll find a section about issues when installing patches [Installing Patches](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help#3-if-apply-patches-fails-with-an-error-saying-the-patches-dont-fit-this-version-of-dcs-and-to-get-new-ones) and how to resolve them.

If this does not resolve the problem, then refer to [Get Help with Helios Software](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help-with-Helios-Software) which is also linked in the original document.
