### ISSUE TITLE
DCS: F-15E Interface?

### ISSUE THREAD

**Issue by MedievalBunny** [HeliosVirtualCockpit/Helios#741]
Is anyone working on adding an Interface for the DCS F-15E? 

I'm tempted to start building one, but don't want to duplicate efforts.

**Comment by BlueFinBima** [comment]
Yes, almost complete.  It is in the Mudhen-Interface branch if you want to follow along

**Comment by BlueFinBima** [comment]
Anticipated delivery 1.6.6010.0

**Comment by BlueFinBima** [comment]
https://www.youtube.com/watch?v=rMRb6HU1k-I

**Comment by BlueFinBima** [comment]
Delivered in Delivered in 1.6.6010.4
