### ISSUE TITLE
MFD export for VR

### ISSUE THREAD

**Issue by klinkeye** [HeliosVirtualCockpit/Helios#742]
As MFD export using VR is possible using a monitor config .lua line: 
```
VR_allow_MFD_out_of_HMD = true
```
A feature request to add a Helios GUI option to both include in the monitor config the line VR_allow_MFD_out_of_HMD = true - as well as check if the line exists in the monitor configuration if the GUI option is selected.

**Comment by klinkeye** [comment]
Additional information is that in order for this to work, a narrative should be provided that the DCS VR System Options needs to have VR Mirror Options - "Use DCS System Resolution" enabled.

**Comment by BlueFinBima** [comment]
@klinkeye I have to confess to being confused by this request.  In general, Helios and VR are incompatible.  Can you explain the use case where Helios and VR work together to result in this request?

**Comment by klinkeye** [comment]
@BlueFinBima I know a lot of the community think that MFD export is completely not possible in DCS, and that MFD export is mostly pointless for VR use. However, it is 100% possible and in my use case: I currently export 3 MFDs in the FA18c using a Varjo XR3 mixed reality headset. I use Helios to setup the monitor configuration and place the MFDs on my winwing usb displays. In order to make MFD export work with VR you need "VR_allow_MFD_out_of_HMD = true" in the monitor config .lua alongside the configuration generated by Helios.

Other DCS Settings required for this to work is - DCS VR Options: VR Mirror Options - "Use DCS System Resolution".

The Resolution and Screens configuration is the same as you would for a flat-screen Helios scenario.

What I am asking for is, the ability to tick a box for "VR Use" which includes that line in the monitor configuration Helios generates, and in the checks that Helios does, validates that the line exists in the Helios configuration if it is ticked. Currently Helios warns me that the configuration is different from the Helios profile because I manually add that line in.

**Comment by BlueFinBima** [comment]
Thanks for the explanation and use case.  MR/AR isn't something I had
considered for Helios.  Can you please attach a working example of a
monitor setup Lua file which is configured as you need it to be?

**Comment by klinkeye** [comment]
Certainly, renamed with .txt because Github dont like .lua extensions.
This example is for a single MFD (currently what I'm testing).

Did you also want the Helios profile?

[H_FA18-1Display.lua.txt](https://github.com/HeliosVirtualCockpit/Helios/files/12191299/H_FA18-1Display.lua.txt)

**Comment by BlueFinBima** [comment]
Thanks, I just wanted to know if the variable was part of another function.  I realise that what you ask sounds trivial, however the issue isn't the insertion of the text, but how Helios validates that the lua has not been altered.  I'll investigate once I get the next release of Helios out of the door. 
```
_  = function(p) return p end
name = _('H_FA18-1Display')
description = 'Generated from Helios Profile FA18-1Display'
FA_18C_RIGHT_MFCD = { x = 0, y = 254, width = 768, height = 770 }
Viewports = {
  Center = {
    x = 768,
    y = 0,
    width = 3440,
    height = 1440,
    aspect = 2.38888888888889,
    dx = 0,
    dy = 0
  }
}
UI = { x = 769, y = 0, width = 3440, height = 1440 }
UIMainView = UI
GU_MAIN_VIEWPORT = Viewports.Center
VR_allow_MFD_out_of_HMD = true
```

**Comment by BlueFinBima** [comment]
Design Notes:  
* Can't really be implemented as a single global option.  Needs to be individually enabled for the separate profiles, as well as a single enabler for the Combined monitor setup.  
* This also requires persisting the enablement in the Helios preferences.  
* Also ideally this needs to be done in a fashion which allows similar enablement in the monitor setup lua should that be necessary in the future (possibly not necessary for now).
* Preflight needs to ensure that it can restore state in PerformReadyCheck for the DCS Monitor Setup interface.

**Comment by BlueFinBima** [comment]
So much investigation and design work for a single line of script being added!  The DCS Monitor Setup Interface is a very nuanced design focused on viewports.  Simply adding an option to the interface panel was not consistent with the design, and would  not have been able to function properly with both combined and isolated Monitor Setup scripts - and preflight checking would have been a major problem. 
The final design uses a new control (see Special Controls in the Toolbox) and a profile with this control in it (plus the viewport needing to be exported), will have the requested variable set in the monitor setup Lua script.
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/18526232/45e4a4ba-88e6-483c-ae34-923192b4bcc2)

**Comment by BlueFinBima** [comment]
@klinkeye This has been delivered in 1.6.6020.0 which has just been released.  The way it works is that you drag the new control into the profile you're using for VR, and configure as normal with the DCS Monitor Setup Interface.  The resulting monitor setup script should have the variable set in it, and shouldn't cause problems with pre-flight.

**Comment by klinkeye** [comment]
Brilliant work - much appreciated!
