### ISSUE TITLE
Trouble with exporting any screens in the f-22A

### ISSUE THREAD

**Issue by Lkirchner1234** [HeliosVirtualCockpit/Helios#749]
Helios is a great software but I am having trouble exporting any of the screens in the f-22A. With a bunch of the other planes Helios already has profiles for them with all of the screens and gauges there able to just be dragged out onto whatever monitor you are using. But for the f22 there is none of that.

I have already configured some of it.
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/100038209/b94f5936-618e-43d6-80d0-cb7009278e72)

The f-22A mod I am using is: https://grinnellidesigns.com/f22/

Any help exporting the screens or configuring helios would be extremely helpful.

**Comment by BlueFinBima** [comment]
Hello @Lkirchner1234, I suggest that you head to the [Capt Zeen Discord](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help-with-Profiles#capt-zeen) where most of the users hang out. Maybe another user can help you along if you have tried everything you can do on your own.
