### ISSUE TITLE
F-15E Loose Ends (Interface / Controls / Gauges)

### ISSUE THREAD

**Issue by BlueFinBima** [HeliosVirtualCockpit/Helios#753]
# F-15E Strike Eagle Loose Ends
This issue is based on 1.6.6020.0

1. UFC HUD REJ1/2 toggle is reversed [ ]   (Reported by Seiko on Discord)
2. the low fuel warning fires the nuclear warninglight in the backseat! (steff on Discord)
3. UFC incorrect B3 Pressed button image (@MadKreator37 )

**Comment by BlueFinBima** [comment]
Noticed button B/3 on both pilot and wso has incorrect "pressed" image. My fault 100%. I did not resize it appropriately. All other "pressed" ufc buttons are 7 pixels smaller than their normal counterparts. Corrected image attached.

[UFC B3 Button Corrected.zip](https://github.com/HeliosVirtualCockpit/Helios/files/12493942/UFC.B3.Button.Corrected.zip)

**Comment by MadKreator37** [comment]
Wrong image still for B3

**Comment by MadKreator37** [comment]
UFC Correct B3 Pressed button
[UFC B3 pressed.zip](https://github.com/HeliosVirtualCockpit/Helios/files/12506982/UFC.B3.pressed.zip)

**Comment by BlueFinBima** [comment]
Interface change to UFC toggle switches.
Image change to one key on the UFC
Autobinding fix for WSO Caution light panel to address issues with the lower row of indicators lighting up the wrong light.
JSON interface commit for the Interface change

@MadKreator37 because the autobinding was wrong for the WSO caution lights, the bindings in your profile are wrong and need to be corrected.

**Comment by BlueFinBima** [comment]
Shipped in 1.6.6030.1
