### ISSUE TITLE
F-15E UFC Incorrect Button Image

### ISSUE THREAD

**Issue by MadKreator37** [HeliosVirtualCockpit/Helios#754]
Noticed button B/3 on both pilot and wso has incorrect "pressed" image. My fault 100%. I did not resize it appropriately. All other "pressed" ufc buttons are 7 pixels smaller than their normal counterparts. Corrected image attached. 

[UFC B3 Button Corrected.zip](https://github.com/HeliosVirtualCockpit/Helios/files/12493942/UFC.B3.Button.Corrected.zip)

**Comment by BlueFinBima** [comment]
Copied to Loose Ends #753
