### ISSUE TITLE
Control Center Command Line option not working

### ISSUE THREAD

**Issue by BlueFinBima** [HeliosVirtualCockpit/Helios#755]
- [X] I have read [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)
---
### Describe the Helios Issue
Specifying a profile as an argument for Control Center from the command line is a little opaque (from the help) because it requires a full path to the `.hpf` file.  The help also contains the term "Pos 0" without making reference to it - however this is outside the scope of this issue.

### Steps to Reproduce the problem
Steps to reproduce the behaviour:
1. Go to command line
2. Type "Control Center.exe" "profile1.hpf"
3. Even though profile1.hpf exists in `Documents\Helios\Profiles` it does not start
4. Type `"Control Center.exe" "%userprofile%\Documents\Helios\Profiles\profile1.hpf"`
5. Profile starts

### Expected behavior
The help is unhelpful about the requirements of the argument to start a profile.  Control Center should look for the profile in the Helios Profile Directory and the Secondary Profile Directory if it cannot find the profile which has been passed as an argument.

### Please complete the following information:
 - Helios Version [*1.6.602*] (and probably for a very long time before this 
 - DCS Version   n/a
 - BMS Version  n/a

### The problem happened while using 
(place an 'x' between the square brackets for all that apply)
 - [X] Profile Editor
 - [X] Control Center
 - [ ] Keypress Receiver
 - [ ] Something else (*remember to tell us what it is*)

### Additional context
Raised by Ratzifutzi on CZ Discord

**Comment by Todd1215** [comment]
I use the command line feature as well and agree that the help is not helpful. Probably the Control Center should just look in whatever directory is defined as default or overridden by -d option.

**Comment by BlueFinBima** [comment]
Thanks for the input @Todd1215.  I've added some usage examples to the help and tweaked the help text a little. Rather than use the -d, I'm doing a file.exists on supplied profile, if that is false I do a file.exists on the _profile directory from the HeliosSettings_ and if that is false I try a file.exists on the _secondary profile directory_ from the HeliosSettings.  If that fails, I assume that the input is rubbish.
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/18526232/964e9788-ba42-44a8-a4a2-b8cbdf5c7859)
It would be nice to suppress the default settings in the examples. but I'm struggling to find the right CommandLineParser incantation.

**Comment by BlueFinBima** [comment]
Shipped in 1.6.6030.1
