### ISSUE TITLE
Some viewports and instruments are transparent in VR

### ISSUE THREAD

**Issue by rocketeer998** [HeliosVirtualCockpit/Helios#756]
Hi, it's great to see that now Helios allows one to export MFD and gauges to second monitor while in VR. Been waiting for years for this. It works great for the MFDs in F-18. But its IFEI is transparent, while the UFC doesn't appear at all.

I added a second line to handle F-15E as they are called MPD and added these to my monitor setup lua.
VR_allow_MFD_out_of_HMD = true
VR_allow_MPD_out_of_HMD = true

Only then the MPDs appear in the F-15E. But they are transparent like the IFEI in the F-18.

Is there a reason why the MFDs in F-18 are fine with black background, but the IFEI in F-18 and MPDs in F-15E are transparent?
I played with the background colors and opacity of the viewports, checking and unchecking use of background. None of these helped.

[https://imgur.com/a/431pefc](url)
[https://imgur.com/3HSiLhM](url)

**Comment by BlueFinBima** [comment]
Hi @rocketeer998,  generally most viewports are exported from DCS with transparent backgrounds.  I have no idea why, but it isn't a big issue in non-VR.  I think you'd have to take this up with ED  if you wanted it changed.  This said, I don't think viewports for the hornet IFEI are part of their module, so I wouldn't expect that ED will be too interested.  
Helios does have an IFEI for the hornet which does not use a viewport,  not sure if that helps any.
All I can offer you is sympathy.
@klinkeye  can you add anything to this discussion?

**Comment by rocketeer998** [comment]
Are you saying the ED chose to make F18 viewports with black background, while leave F15 viewports transparent by default?

the hornet IFEI is not pulled from viewport, but from the F-18 interface where all gauges and panels are. Only MFDs are in the viewport category.

**Comment by BlueFinBima** [comment]
@rocketeer998 I am _speculating_ that ED made the viewports have a background.  I have no way to know it was a deliberate decision.  I don't work for ED or Razbam.
The exporting of MFDs from DCS, to a significant extent, is nothing to do with Helios.  If someone tells me how to change a module's lua script to force a background, I might add it to a Helios patch, but that would only happen if it would not negatively impact other Helios users.

**Comment by rocketeer998** [comment]
So if ED is the one who made the F-18 MFD black background, and F-15E MPD transparent, as users of Helios ourselves we can't do anyone to change transparency of viewports? It will need to come from adminstrators of helios like yourself in the form of a patch? but I suppose unless others vote for this to be done else it'd remain transparent, until ED decides to do it themselves.

**Comment by BlueFinBima** [comment]
@rocketeer998 I think you're misunderstanding the situation.  At this moment in time, if is not possible for me to do anything.  I do not know if it is even achievable to get the effect of a background on the viewport by changing one or more Lua files.  It might need a change by the module developers.
**If** you or somebody else works out how to get the background by changing a Lua file, **then** it would probably be a simple task for Helios to deliver that change as a patch.  The Helios patch only makes it easier for Helios users to get the Lua changes that they could apply themselves by other means.
This is not about other Helios users "voting" for this.  I did a huge amount of work to implement the change which gave you the insertion of `VR_allow_MFD_out_of_HMD = true` without triggering altered script warning and I did that for one user (or two if we include you).
I will not accept this issue as a future enhancement to Helios because there isn't any evidence that what you're requesting can ever be delivered by Helios without a change by Razbam / ED.

**Comment by BlueFinBima** [comment]
@rocketeer998 Did you investigate this on the ED Forum before opening this issue?  You might like to take a look at [MFD Background Turn Black After 2.8.3.37854.1 Open Beta Update](https://forum.dcs.world/topic/322001-mfd-background-turn-black-after-283378541-open-beta-update/#comment-5178806).   Obviously this article refers to the Hornet, but my main take-away from this is that not everyone thinks a black background is desirable.

**Comment by BlueFinBima** [comment]
Ref:
Below is the code block which gives the Hornet a solid background.  The file is `... \Mods\aircraft\FA-18C\Cockpit\Scripts\Multipurpose_Display_Group\Common\indicator\BAKE\MPD_common_bake_page.lua`.  My hunch is that 
this would not work with the F-15E, but I have not tried it.
``` lua
...
-- Background on HUD-only view
do
	-- we need the border be rescaled to sizes -1 to 1
	local borderSzNorm = getMaxCoord(displayBorderVerts)

	local verts = {}
	copyTable(verts, displayBorderVerts)
	local inds = prepareBorderVerts(verts, 1 / borderSzNorm)

	local HUD_only_back        			= CreateElement "ceMeshPoly"
	HUD_only_back.name				= bake_material_name .. "_HUD_only_back"
	HUD_only_back.material 	 		= MakeMaterial("",{0,0,0,255})
                                                                         ---  This value is the Alpha channel of the background
	HUD_only_back.vertices      		= verts
	HUD_only_back.indices	     		= inds
	HUD_only_back.additive_alpha   		= false
	
	if bakeToCockpitTexture ~= true then
		HUD_only_back.controllers 	 	= {{"render_purpose",1,2,3}}
	end
	
	--HUD_only_back.isdraw				= false
	HUD_only_back.parent_element 		= pic_placeholder.name
	Add(HUD_only_back)
end
...
end
```
