### ISSUE TITLE
Add Change Control Center Profile - Output Binding

### ISSUE THREAD

**Issue by finbarlay** [HeliosVirtualCockpit/Helios#760]
# Add Change Control Center Profile - Output Binding 

- [Y ] I have read [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)
---
### Description
*I have recently started using Helios with DCS and have been amazed at the functionality contained in it.  I have added some functionality so that a Helios Profile can start another Helios Profile on an event (eg.button press).  The reason I am using this is so that profiles can be setup without toggling/hiding objects (which befuddles me a bit) and I thought I would share my code as it might be of interest.

In Profile Editor, under  [Bindings |  Interfaces | Profile], this adds a new option of [change control center profile] which has a Static Value/Action Value of the Profile to change to.*

[HeliosChangeProfileUpdate.PDF](https://github.com/HeliosVirtualCockpit/Helios/files/12783300/HeliosChangeProfileUpdate.PDF)

**Comment by BlueFinBima** [comment]
@finbarlay Thanks for submitting this request, as well as providing your code (maybe a PR would have been easier ;-) )
Typically, you would create your sub-profiles in separate panels in a single profile, and simply hide/unhide the panels.  While I'm not sure about the pros/cons about switching to a new profile with this code (my main concern is the time it might take to load the new images),  I do think that it is worth including your functionality in a future release of Helios.
Thanks again for offering your idea and code to the Helios Virtual Cockpit project.

**Comment by finbarlay** [comment]
> @finbarlay Thanks for submitting this request, as well as providing your code (maybe a PR would have been easier ;-) ) Typically, you would create your sub-profiles in separate panels in a single profile, and simply hide/unhide the panels. While I'm not sure about the pros/cons about switching to a new profile with this code (my main concern is the time it might take to load the new images), I do think that it is worth including your functionality in a future release of Helios. Thanks again for offering your idea and code to the Helios Virtual Cockpit project.

@BlueFinBima  Thanks for looking at this, let alone including it.  I'm not familiar with C# or Git (my source code management skills started and ended with SourceSafe), but I'll look into Pull Requests for next time (I had to look up what PR meant) . :laughing:

**Comment by BlueFinBima** [comment]
Shipped in 1.6.6030.1
