### ISSUE TITLE
Binding value Lua error "[string "chunk"]:1: syntax error near 'Falcon'"

### ISSUE THREAD

**Issue by Todd1215** [HeliosVirtualCockpit/Helios#770]
While running the Ice Profile for BMS with latest Helios 1.6.603 we get an error message thrown in the ControlCenter log file "attached". seems to reference the below code.
https://github.com/HeliosVirtualCockpit/Helios/blob/a215b04bb7d7412e3be79de1c2f7468c53765a00/Helios/HeliosBinding.cs#L278C42-L278C42

Below is the Control Center log that shows the error.

[Control Center Problems.log](https://github.com/HeliosVirtualCockpit/Helios/files/13169925/Control.Center.Problems.log)

**Comment by Todd1215** [comment]
The ProfileName string could contain special characters that are allowed in the filesystem. we should escape any character that might be valid for a filesystem name.

**Comment by BlueFinBima** [comment]
The only character I could find which is valid in a Windows filename but needs to be escaped in Lua is the apostrophe.

**Comment by BlueFinBima** [comment]
Delivered in 1.6.6040.3
