### ISSUE TITLE
Interface not working

### ISSUE THREAD

**Issue by tulbord** [HeliosVirtualCockpit/Helios#772]
I'm having problems with the interfaces.
When trying to add an interface, the error message appears and then the blank window.

![image](https://github.com/HeliosVirtualCockpit/Helios/assets/78508590/d82c4734-abf1-4572-a8ef-ee32c03e5d55)

![image](https://github.com/HeliosVirtualCockpit/Helios/assets/78508590/cfe3edf9-2dcc-4606-b41d-8582cf7354d0)

**Comment by Todd1215** [comment]
More than likely you have multiple USB controllers with the same USB ID. Maybe you have some DIY boards connected or something. Disconnect all your USB controllers and see if you get the same error.

**Comment by tulbord** [comment]
Thank you for your help.
I was using the ccp server and that was the problem.

**Comment by BlueFinBima** [comment]
@Todd1215 Would you mind taking a look at https://github.com/HeliosVirtualCockpit/Helios/commit/ab37b3f5f8158c7bd06e86725fb550d53b8215e9 please?

**Comment by Todd1215** [comment]
That should give a better error message at least. So looks ok to me. Sent from my iPadOn Nov 1, 2023, at 9:40 AM, BlueFinBima ***@***.***> wrote:﻿
@Todd1215 Would you mind taking a look at ab37b3f please?

**Comment by BlueFinBima** [comment]
@Todd1215 Thanks.  I was a little surprised that the previous code did not provide the protection I was expecting, but not surprised enough to investigate further ;-)

**Comment by BlueFinBima** [comment]
Tagging with #485, #491, #659, #723

**Comment by BlueFinBima** [comment]
Delivered in 1.6.6040.3
