### ISSUE TITLE
MK37 /F-15E Interface Output Bindings not working- TF Couple Switch, Flyup Cover and Switch...Interface issue?

### ISSUE THREAD

**Issue by MadKreator37** [HeliosVirtualCockpit/Helios#773]
- [ x] I have read [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)
---
### Describe the Helios Issue
TF Couple switch on CAS panel and Flyup Cover and Switch on Left Bulkhead, outputs not functioning. Possible something changed in module when Terrain Following radar was added. Verified bindings are correct in the profile.

### Steps to Reproduce the problem
Steps to reproduce the behaviour:
open profile
start game
move TF Couple switch in Helios- No Movement in DCS ( bindings are correct and input functions)
move Flyup switch cover and switch in Helios- No movement in DCS (bindings are correct and inputs function)

### Expected behavior
Switches in cockpit move when they are switched on/off in helios

### Please complete the following information:
 - Helios Version1.6.603
 - DCS Version 2.9.0.47168
 - Profile MK37 F-15E v 1.0.2

### The problem happened while using 
(place an 'x' between the square brackets for all that apply)
 - [ ] Profile Editor
 - [ ] Control Center
 - [ ] Keypress Receiver
 - [ x] Something else-- In Game

### Additional context
Seems to be an interface issue. Tried re-binding in the profile with no luck,

**Comment by BlueFinBima** [comment]
@MadKreator37 looks like you are correct about Terrain following.  456, 522 and 523 are all now on device TFR and previously they were on device FLCTRL.
The only other switch defined to TFR was already defined in the interface with the current device.

**Comment by BlueFinBima** [comment]
https://github.com/HeliosVirtualCockpit/HeliosInterfaces/commit/8aafd58e8950e2b61a03c21b159b4ed9742b825b is the mirror commit for the JSON Interface.

**Comment by MadKreator37** [comment]
Great! Will the profile need updated/ new bindings due to the new Device ID's?

**Comment by BlueFinBima** [comment]
@MadKreator37 No, the profile will just start working again when the changes to the interface are picked up.  You can try this by using the JSON version of the interface mentioned above.

**Comment by MadKreator37** [comment]
Perfect, thank you very much!

**Comment by MadKreator37** [comment]
New interface works as expected with no profile modification necessary. A+
