### ISSUE TITLE
Request: Split F-15E UFC into two parts

### ISSUE THREAD

**Issue by MedievalBunny** [HeliosVirtualCockpit/Helios#775]
I'm loving the pre-built F-15E panels. But, the UFC is quite ... large. I'm having trouble fitting it into a setup I like.

Would it be possible to split it into two separately placeable halves? One with just the Option Select buttons and LCD lines and another with the numerical keypad and HUD controls?

Or is there someplace I can find the graphics used for the panels and build my own?

**Comment by MadKreator37** [comment]
@MedievalBunny Here are the images used in the UFC. You could take the main image into PS or gimp, or whatever and split it. The items in the Helios "Toolbox" are hard coded in. They are made from straight programming of the separate parts combined into one unit. The ODU Displays though, I'm not sure about. Bluefin created the displays and I think they are just programmed into Helios too.  I wouldn't even know how to make new ones for a new UFC. I provided graphics and assembled the profile. Bluefin did all the programming and interface. I used all the items from the toolbox that Bluefin created so I don't have any other working versions. Only what is already in Helios.

[UFC.zip](https://github.com/HeliosVirtualCockpit/Helios/files/13668053/UFC.zip)

**Comment by MadKreator37** [comment]
Actually, here. Here is every thing used in the profile and a lot of images that weren't. I don't have the photoshop files for any of them. Only the PNG's
https://drive.google.com/drive/folders/1lTOQwsHy4PknkjkqfLOB7iaCsEfud50i?usp=sharing

**Comment by MedievalBunny** [comment]
@MadKreator37 That is hugely useful, thank you!! I can do exactly what I want with that.

The ODU Displays are not a thing I really understand how to do the way they are implemented in the stock UFC, but I can just do it the easy way with a display export from DCS if I can't figure out the text fields. Probably going to want a UFC display export for the later model F-15E with the digital UFC anyway once that comes out.

**Comment by MedievalBunny** [comment]
UFC export is a little dark, but overall I'm quite happy with this. 

Thanks again!

![Screenshot 2023-12-14 020722](https://github.com/HeliosVirtualCockpit/Helios/assets/19675397/5c2032ed-b9a7-4827-a829-6fee31bdb8c7)

**Comment by MadKreator37** [comment]
@MedievalBunny Dude! Great job! Happy that worked out! Bluefin added screen exporter functions into helios ( like IRIS) a while back, that has brightness/ contrast/ gamma filters. You could create the viewport behind something, or on a virtual monitor then use the screen exporter to place it in the right spot and use the video filters to brighten it up. I've never tried it personally but that may be an idea if you want to mess with that.

**Comment by BlueFinBima** [comment]
@MedievalBunny Makes sense in the context of your screenshot.  The ODU text handling is a little involved so not easy for you to replicate, but that isn't an obstacle to splitting.

**Comment by MadKreator37** [comment]
Thank you for this Bluefin!

**Comment by BlueFinBima** [comment]
Delivered in 1.6.6050.1

**Comment by BlueFinBima** [comment]
@MadKreator37 The only thing changed from your profile's perspective, is that the WSO UFC should no longer have the "dead space" at the bottom (ie it is the correct size).
