### ISSUE TITLE
UH-1H Huey - Mission where I select a Huey defined as Client - All buttons works on their own when entering mission

### ISSUE THREAD

**Issue by TBarina** [HeliosVirtualCockpit/Helios#776]
If I start any missions where I select one Huey that was defined as "Client" and not "Player" in the mission editor, as soon as I start the mission all cockpit buttons are clicked on their own and I cannot start her up.
Probably it doesn't recognize that I've select the unit a Player controlled one.

The only work-around is to stop Helios, start the missions and the start Helios.

Is this to be considered as a bug?

Many thanks.

**Comment by TBarina** [comment]
Anyone has the same issue?

**Comment by BlueFinBima** [comment]
@TBarina I think I remember someone reporting something similar on Discord, but I don't think this is a Helios issue per se.  I suggest you head to the [Capt Zeen Discord](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help-with-Profiles#capt-zeen) where most of the users hang out. Maybe another user can help you along if you have tried everything you can do on your own.
