### ISSUE TITLE
Incorrect deviceId in F-14 interface

### ISSUE THREAD

**Issue by MedievalBunny** [HeliosVirtualCockpit/Helios#784]
A number of systems in the F-14 interface have incorrect deviceIds in the json, breaking a bunch of functionality. The autopilot and fuel system switches for sure I've found so far, I suspect there are more.

I've fixed the ones I've found so far on my end, I'll go through the rest of the profile and submit a pull request.

**Comment by MedievalBunny** [comment]
Fixed with this: https://github.com/HeliosVirtualCockpit/HeliosInterfaces/pull/8#issue-2060947667

**Comment by BlueFinBima** [comment]
Awaiting response about testing of the PR.

**Comment by BlueFinBima** [comment]
@MedievalBunny 's F-14 Changes from https://github.com/HeliosVirtualCockpit/HeliosInterfaces/pull/8 and https://github.com/MedievalBunny/HeliosInterfaces/commit/623b0c588d6ef69c9910e93fcebb00352c19e577

**Comment by BlueFinBima** [comment]
Shipped in 1.6.606.  Thanks for the contribution to Helios
