### ISSUE TITLE
AMPCD not displaying

### ISSUE THREAD

**Issue by aerodenamic** [HeliosVirtualCockpit/Helios#785]
I am currently using/ setting up the f18, and can not get buttons or template ampcds and such to show up in the game. I have 2 regular monitors and my third is an old lenovo tab4 that i am using spacedesk over wifi to display my mfd feeds. I got that part to work fine, it displays both my left and right mfds live on the tablet, but I can not get any buttons to show up. I tried editing the lua file as well and only saw the viewports in the file, none of the buttons I added. Not sure if this is an issue with helios, dcs, my setup, or just lack of understanding how this all works, Id appreciate any help!

**Comment by BlueFinBima** [comment]
Hi @aerodenamic, typically requests for help are not dealt with on GitHub.  The [Get Help section of the Wiki](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help) will give you pointers about where people can assist you.
