### ISSUE TITLE
Telemetry Driver and Interface: Additional Data Request - Magnetic Yaw needs to be available in Simulator Telemetry

### ISSUE THREAD

**Issue by Shaftoe62** [HeliosVirtualCockpit/Helios#786]
Currently the common Simulator Telemetry only contains "Yaw" as a directional parameter. 

But this represent True North in the DCS World. While the Magnetic North is much more commonly used in aircraft. Notably for all analog compasses.

There seems to have been done some preliminary work on this because the function call "LoGetMagneticYaw()" is already mentioned in Export.lua right beneath "LoGetADIPitchBankYaw()".

So hereby an urgent request to add the magnetic yaw to the common section of Simulator Telemetry for ALL aircraft.

Thank in advance.

![image](https://github.com/HeliosVirtualCockpit/Helios/assets/53898212/07289693-d46d-4431-818c-f62890fdea47)
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/53898212/9b2bd2d7-b6ec-46fe-92e9-595e8a229b76)
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/53898212/5210175b-3e20-425a-acc0-1b982f9a8ac5)
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/53898212/d543c20c-9642-499b-87de-75354ccc6a90)

**Comment by BlueFinBima** [comment]
Shipped in 1.6.606
