### ISSUE TITLE
Minor issues AH-64D CMWS Threat Quadrant Indicators

### ISSUE THREAD

**Issue by Shaftoe62** [HeliosVirtualCockpit/Helios#797]
@BlueFinBima

Hi, I've been working on an adapted version of the pilot CMWS panel for the CPG. There is a lot of telemetry available for that and that is great.

![image](https://github.com/HeliosVirtualCockpit/Helios/assets/53898212/39948f93-5d7b-4f51-9f6a-827687809015)

But I ran into some strange issues that put me on the wrong foot in the beginning. Nothing major, just confusing.

### 1. Confusing variable names in Helios.AH64D.hif.json vs.AH-64D_BLK_II.lua (driver)

Some of the variables are called "Zones" (front, right, aft and left) in the JSON while they are actually just the tiny arrows in that direction. 

In the driver they are named like that and that is how I eventually figured out what they are doing and when they are activated.

I was thinking that these zones were active in **_stead of_** (for example) direction front-left and direction front-right, when these were both active at the same time.

I think those "zone" arrows don't really need to be identified seperately. There are only four directions and these contain a range of id's (I think to identify seperate graphics).

These zone arrows are active when the adjacent group (range) of id's is active.

A direction highlights all the arrows that belong to that direction (in the simulator). For example.

A threat in the front-right quadrant highlights the front, front-right and right arrows and the big one in the front-right.

A threat in the front-left quadrant highlights the front, front-left and left arrows and the big one in the front-left.

So when both sensors are activated both these quadrants are highlighted.

The front arrow is thus hightlighted twice.

That is probably why they have separate ID's.

But these ID's are activated by each adjacent quadrant so they are rather confusing to use. The front zone arrow for example is activated by BOTH front directions. 

And since I simply use images like these (that include all the three tiny arrows) for each quadrant highlight, I have no need for those "zone" arrow ID's.
 
![cmws-threat-display-direction-front-right](https://github.com/HeliosVirtualCockpit/Helios/assets/53898212/b2a407a4-44e6-4a7e-a676-f602e1bd3adc)

The only use I can think of for these separate "zone" arrows is if you want to work with transparency in those highlights or different colors perhaps. But that would be really over complicating things. Even for me!!!

### 2. Numbers as strings? Why not Boolean?

The variables for all these Threat Quadrant Indicators contain string values (0.0 or 1.0) and not Booleans as is indicated/suggested in the Helios.AH64D.hif.json. They even have a precision of one decimal that has no purpose whatsoever. 

It would be much nicer it they would contain true or false and then as the current 0.0 = true and 1.0 = false. Then they can be used directly to set the visibility of a quadrant.

Now that can only be done with a lua script for each image in Helios:

```
a = TriggerValue
a = string.format("%.0f", a)
b = true
if a == '1' then b = false end
return b
```

**Comment by BlueFinBima** [comment]
Thanks for the comments / suggestions.  
1.  This would be a breaking change for anyone who has already implemented their own CMWS.  Additionally the internal AH-64D CMWS would need to be reworked to achieve the request, and it is currently working so I don't see any material benefit in prioritising this work.  If you wish to clarify the current implementation of the CMWS, then I would suggest making additions to the wiki.

2.  I understand that this is a general point, however as it relates to 1. you could simplify the process by using this template which exposes the internal CMWS Display and which will allow binding to the current values in the interface.
[AH-64D CMWS Display.zip](https://github.com/HeliosVirtualCockpit/Helios/files/14035222/AH-64D.CMWS.Display.zip).
If you continue to use Luascript, then `return TriggerValue > 0`  is neater, more performant and quicker to type.
The current implementation of the Helios communication protocol is essentially type-less.  The requested functionality would be a significant change to the helios communication.  #251 is in vaguely the same area.

**Comment by Shaftoe62** [comment]
@BlueFinBima

Hi, thanks for the reply.

I fully understand the problem of backward incompatibility with existing implementations. It wasn't really a request for changing anything. I just thought it was worth mentioning it for clarity. I will have a look at the Wiki to see if I can add it there in a concise way for the benefit of others.

Where can I find the Wiki, so I can post my findings there?

You can tell I'm not a very good (lua) coder and this is just what I came up with to get it working. And I just left it at that. Verbose as it is. But I'm learning on the job so thanks for the tip on how to do it better. I will change that right away.

**Comment by Shaftoe62** [comment]
@BlueFinBima

The zip archive AH-64D.CMWS.Display.zip you posted only cantains a file AH-64D CMWS Display.htpl. 

I don't know how I can use that?

Thanks

**Comment by Shaftoe62** [comment]
The lua code needs to be `return tonumber(TriggerValue) < 1` as it needs to return false to show the highlight and it needs be a number but that is in line with the other issue you linked.

**Comment by BlueFinBima** [comment]
Place the template `AH-64D CMWS Display.htpl` into %userprofile%\documents\helios\templates\user\` and the display should show in the "AH-64D Apache" section of the toolbox.

Your original Lua converted TriggerValue to a string so I assumed that TriggerValue was already a number so I'm not sure why you need a "tonumber()".   To negate the expression it would simply be `return not(TriggerValue > 0)`.

Finally, you seem very familiar with raising issues so cast your eye to the right and you'll see "Wiki".  
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/18526232/df77afe4-71e8-4387-91be-cfe2a643f3ad)

**Comment by BlueFinBima** [comment]
In that case use `return TriggerValue =="0.0"` for the Set Hidden binding.

**Comment by Shaftoe62** [comment]
Ok, that would be the most "performant" way to do it? Because there is no conversion involved?

Now that we are on the subject of "Syntax", I have been struggeling with some questions.

1. Is there a way to use "new lines" in - for example - Labels or Text Displays like so:
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/53898212/12c07197-8cbb-4052-aa4c-991f2156d985)

2. How can I use special characters in Lua script. Specifically the degree symbol (°). 

I managed to figure out a way to work with a colon (:) by using '\u{3a}' but that only seems to work with one hex pair. 
Degree should be hex {c2 b0} but that doesn't work.

Is there a way to get the degree symbol as a string in lua? And what would work for special charachters in general?

**Comment by BlueFinBima** [comment]
@Shaftoe62 We've strayed way off the original issue so  I'm going to shut this down.  GitHub Issues, at least in this repository, are for  reporting project "issues" and are not general discussions.  Please refer to https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help (which essentially will point you back to Capt Zeen's discord).
