### ISSUE TITLE
Suggestion: Make a Android or Apple App to receive the MFDs and Data via WLAN

### ISSUE THREAD

**Issue by ToastyBanK3nobi** [HeliosVirtualCockpit/Helios#798]
Hey folks,

i'ld love to have an android app, which can receive the Data and the MFDs via WLAN, currently i'm using a programm which uses my tablett as a monitor (spacedesk), but i would prefer a nativ tablet use for DCS. Currently i'm sending the mfds to the mentioned tablet.

I hope you think the same about this idea as i do.

with Kind Regards
TaostyBanK3nobi

**Comment by Todd1215** [comment]
You want Helios to be a tablet App? or you want Helios to be able to interact with a tablet via an app? I'm not sure what the gain would be as the results would be the same. There are already several mobile apps that work with DCS already.

**Comment by BlueFinBima** [comment]
I agree with Mr Wheelchock.  The request is effectively for an Android version of Helios Control Center which is outside the scope of this project.  @ToastyBanK3nobi you might want to review https://forum.dcs.world/topic/228734-dcs-ufc-android-app/ which is just one of several such offerings.  I can understand why the request is being made, however this project is specifically a Windows application and for this reason alone the issue/request is being closed.

**Comment by ToastyBanK3nobi** [comment]
@BlueFinBima that´s a bummer... I don´t know if it´s worth to explain in more Detail, but i´ll do it anyways :) I hope you don´t mind.

What i meant:
The possibility to directly send the MFDs that you create with Helios to an Android Tablet, currently there is no such APP which can display the MFDs via WLAN directly onto your Tablet. The only Way currently to achieve the Goal of having your MFDs in Front of you an a Tablet is if you use an external APP like SpaceDesk which emulates that your Tablet is a Monitor and then Sends the Data (MFDs) to your Tablet, which puts more strain on your graphics Card then needed. If i recall correctly there is already a way build into helios to send Data from the DCS PC to a 2nd PC and show the MFDs there, correct me please if i´m wrong. I know that the DCS PC always has to calculate the Viewports/MFDs, but in my Usecase it also has to calculate a "real" monitor and send this Data through SpaceDesk.

I hope this helps to understand what my idea was, unfortunately English isn´t my native language, so if it isn´t understandable tell me.

With Kind Regards
ToastyBanK3nobi

**Comment by BlueFinBima** [comment]
@ToastyBanK3nobi It is not clear to me how you have investigated the Android options which are currently available. https://play.google.com/store/apps/details?id=com.deviceworks.warthogdevice&pli=1 is yet another offering which does some portion of what you are requesting and there are others.
Iris Screen Exporter is the project closely related to Helios and moves images from one PC to another, but it is not the only way to transport images.  An Android application which renders information from the Iris Server is certainly possible for someone with the right skill set, **however** it would be one direction only (so no interaction with the tablet touch screen).
If you wish to investigate options for yourself, maybe take a look at the FFMPEG options on Android.  There seems to be a few projects in this area, and FFMPEG can be used to transport images from one device to another.
Ultimately, I fully understand your request (and so do the authors of various existing Android applications), however this is not on the  Helios or Iris roadmaps.

Regards BFB
