### ISSUE TITLE
AH-64D CMWS Display does not have enough room for Display Lines 1 & 2

### ISSUE THREAD

**Issue by Shaftoe62** [HeliosVirtualCockpit/Helios#799]
Texts should be showing "F   60" and "C   30"

![image](https://github.com/HeliosVirtualCockpit/Helios/assets/53898212/24c5278f-af1d-4ec6-bda9-3ddecd12e3a5)

In my own version of this display I have one space removed for each of these lines when they show the Flares and Chaff quantities.

`"F " = "F"`

Maybe the simulator now exports different texts (with more spaces) than it did in earlier versions?

Also, when I remove one space in the same way in the CMWS display, and the quantity only has one digit, the numbers don't line up vertically anymore.

![image](https://github.com/HeliosVirtualCockpit/Helios/assets/53898212/ebf1af20-6786-4781-9729-373eae6868c4)

Is it perhaps a font issue?

**Comment by Shaftoe62** [comment]
I took it upon myself to make a new font, specific for the CMS display.

![image](https://github.com/HeliosVirtualCockpit/Helios/assets/53898212/13478214-f5da-41de-abfb-15e52640cbd8)


It's based on the DCS 'DCSWorld\Mods\aircraft\AH-64D\Cockpit\IndicationResources\CMWS\CMWS_font.tga' file, but I completed the Latin alphabet (All Caps).

I left a full 7x5 matrix in the font in an unused glyph that can be used to copy/paste to create additional glyphs if needed.

I also included the original Adobe Illustrator document and an SVG of the same matrix/grid that can be imported in FontForge directly and should position itself precisely.

All characters are exactly 896 units(points) wide (56 x 16). The Adobe Illustrator should be self explanatory on this.



Also, in the display, the texts inputs CMWS Line 1 & 2, have "F  " (F + 2 spaces) replaced by a single "F" and "C  " (C + 2 spaces) is replaced by a single "C", respectively.

If a countermeasure is out, the display shows "FOUT" or "COUT", without any spaces.

A line can contain max 4 characters.

![image](https://github.com/HeliosVirtualCockpit/Helios/assets/53898212/f266e686-1cd1-4b4e-ace4-6efa5d81c686)


[AH-64D-CMWS.zip](https://github.com/HeliosVirtualCockpit/Helios/files/14111837/AH-64D-CMWS.zip)

**Comment by Shaftoe62** [comment]
You are right. It was a resizing issue. I have "Scale and Layout" of my monitors on 150% in Windows (Helios Editor) but I run DCS in full resolution (4K). 

So, the panel got enlarged 150% because I just slapped it on my main monitor just to check on it's composition. I'm not actually using it.

I also took a closer look at the font you are using now: A-10C_ALQ_213.ttf

I found the following issues:

1. Space has a different width than the other glyphs. 600 vs 800. (that causes the alignment issue)
2. The smaller than glyph (<) has a "damaged" circle (the bottom one) and some loose vertices.

It also has round dots as opposed to square ones of the "real" CMWS font. But that can be a matter of taste :-)
And some characters are notably different (J, D, zero) but that is to be expected since it was originally made for the A-10.

If I can do you a favor by fixing those 2 issues in the A-10C_ALQ_213.ttf font, just let me know.

P.S. I will also make my own Keyboard Unit (KU) font so I can have the KU scratchpad centered on the bottom of my main monitor, right above my dual Stream Decks XL which has the KU keys configured on them. If you catch my drift...

**Comment by Shaftoe62** [comment]
Oh, about your question on the "tail" in the three.

It doesn't show here on my system. Nor can I find anything really wrong in the glyph in FontForge. 

![image](https://github.com/HeliosVirtualCockpit/Helios/assets/53898212/dabe8c29-5fa2-4ecc-bb21-37940957b776)


But I have the font installed now so I could use it to print very big.

I will now de-intall it and run only the panel real big. I'll be right back

**Comment by Shaftoe62** [comment]
Phew, that a bit more complicated than I expected.

But I managed to isolate the right font (without loading any others) by Helios only (so not installed in Windows).

And the results are the same. No tail.

![image](https://github.com/HeliosVirtualCockpit/Helios/assets/53898212/24df8261-3832-4103-8c76-818fa1d60411)

**Comment by BlueFinBima** [comment]
This is from Windows
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/18526232/b4890659-6889-4b00-82da-2d005c2a69fb)
(I think I fixed the 3 BTW so it does not show with a tail here)

**Comment by Shaftoe62** [comment]
How did you fix it? It's very strange because those tails don't show up on my system...

But your screen also shows another issue with the fonts in general.

They all have the same family name! And that doesn't work. Especially not when they all have the same weight!

Windows, and therefore also the Helios Profile Editor cannot distinguish between the different fonts.

The editor will show only one font as available.

I'm not going to try what will happen if I would install them all in Windows because it's a pain to get them uninstalled again.

But completely different fonts (which they all are) should have a distinct own font family name.

Members of a family only have different weights like regular, bold etc or 200, 400 600 etc . 

Or specific styles, but these have to be styles that are common font-styles like bold, italic, oblique, condensed, extended, smallcaps, stuff like that. 

Otherwise they won't be recognized by windows and you will end up having access to only one font.

It's a bit strange that FontForge allows to enter any style name or weight you fancy.

**Comment by BlueFinBima** [comment]
Tails only seem to appear when point size is <=24.  I fixed it by deleting the circle where the tail was attached to and creating a new one.
Personalization->Fonts makes it easy to uninstall fonts.  Just delete all of the faces in the font you don't need, and play with the problematic one.
Never had a problem with the fonts, but obviously with Helios, the fonts are private.

**Comment by Shaftoe62** [comment]
So then it is intentional that the fonts don't show up in the editor?

![image](https://github.com/HeliosVirtualCockpit/Helios/assets/53898212/f6d22058-8a91-4074-be94-bc216268c524)

**Comment by BlueFinBima** [comment]
Not intentional, just that nobody has viewed it as a high enough priority to fix it.

Anyway to your original point, A-10C_ALQ_213.ttf has now been changed to include a new zero, six and nine.  The problems you highlighted with the `space`, and `Less Than` have been correct, and the inbuilt CMWS has been updated so that line 1 and line 2 are constrained to 4 characters.

Once I have made sure that the A-10C CMSP and CMSC along with the M2000C VHF radio still display correctly, this will be rolled into a future release of Helios. (probably the next one).

**Comment by Shaftoe62** [comment]
Ok. I'm working on the KU font at the moment. Turns out it's a completely different font after all. Much narrower gaps in between the dots and a many differences in glyphs.

I also have corrected some remaining issues in the CMWS font. The paths went the wrong way around according to FontForge.

When both are done I will send you a package with all the files.

That shows it's never a good idea to implement something without thorough testing.

For now I have removed the link to the zip file.

Do you think you now have solved the issue you were talking about earlier?

**Comment by BlueFinBima** [comment]
> Do you think you now have solved the issue you were talking about earlier?
If you mean the tails, no.  I've managed to get rid of a few more by stumbling around in the dark trying to change the anchor points, but I'm now not convinced that is the problem.  So I've decided to live with the issue since nobody else has spotted it.

**Comment by BlueFinBima** [comment]
I've already put a commit in for this issue, so as far as I'm concerned, this issue is complete except for delivering it in a Helios release.

**Comment by Shaftoe62** [comment]
It's interesting that you mentioned that it only occurs with small font sizes. That would indicate that there is something amis with the Bezier curves. It can happen that the scaling goes haywire but then they are usually set up in a wrong way.

Did you notice that FontForge changes the Illustrator vector "arms"? It seems that FontForge averages and merges the two from adjacent vertices into one. That may also cause issues. Especially when they are then scaled afterwards.

I will have another look later.

I'm still getting to grips with the finer details of FontForge so this is also part of my learning process.

**Comment by Shaftoe62** [comment]
To wrap up the CMS and KU fonts:

![image](https://github.com/HeliosVirtualCockpit/Helios/assets/53898212/e1747791-0e84-4e19-aea0-a5cb533de9dd)

Both are in the zip file completely free of verification errors.

For both also the grid is included in Adobe Illustrator and as ready-to-import SVGs.

Both are designed on the exact same (illustrator) 16 x 16 pixel grid of 896 x 1024 px total. 

With some obvious differences.

Where the CMWS font has dots of 96 px square and 32 px between each dot,

the KU font has 112 px square dots and 16 px in between the dots. So, bigger dots, closer together.

In between each glyph is a space of exactly two dots (purple) with their appropriate space in between those as well (red), for both fonts.

For that reason the KU glyphs are not entirely centered in the glyph width of 896 px but shifted 8 px to the left. 

That way the 16 x 16 px grid remains uncompromized.

![image](https://github.com/HeliosVirtualCockpit/Helios/assets/53898212/e392e4f3-68f8-49bb-b149-ba138d4cbbba)

![image](https://github.com/HeliosVirtualCockpit/Helios/assets/53898212/14fc2833-af83-4f59-b6f2-aa89d8d459c2)

Final remarks:

I have changed the parentheses to be better distinguishable from the brackets.

In the AH-64D-KU font the hashtag is a full matrix of dots because that is what DCS returns as the blinking cursor.

Zip file with both fonts:

[AH-64D-CMWS-KU.zip](https://github.com/HeliosVirtualCockpit/Helios/files/14118283/AH-64D-CMWS-KU.zip)

**Comment by BlueFinBima** [comment]
@Shaftoe62 The TTF fonts you included are copyright Shaftoe62.  Can you please provide me with the License terms for the distribution of these fonts and their usage by others.

**Comment by Shaftoe62** [comment]
Euh... I just copied what you have in your fonts. 

There is no licence. 

Except a "Feel free to use them any which way you want" license.

**Comment by BlueFinBima** [comment]
@Shaftoe62 thanks for the contribution.  I obviously needed to get a formal statement from the copyright holder.  The work is done so the modified CMWS and KU's will appear in the next release of Helios.

**Comment by Shaftoe62** [comment]
Ok, I have one question about the KU scratchpad. 

I thought DCS had replaced the colon (:) by an exclamation point (!) for some unknown reason.

But I just found out that the replacement is done by the driver (AH64D_BLK_II.lua)

I suppose there is a reason for that?

So I was wondering if it would be practical to change the exclamation point in the KU font into a colon?

Cause the now exclamation point needs to be replaced in the parser.

**Comment by BlueFinBima** [comment]
@Shaftoe62 the colon has a special meaning in the communications flow, and there is currently no mechanism to escape characters, so we substitute them.  Yes you could do a substitution in the font, but I think leaving the font as it is, and letting the parser handle it is fine.

**Comment by Shaftoe62** [comment]
Ok, that also explains why I was struggeling with the character substitution in Lua. Much better with the parser.

You asked me to use the Issues Template for new Issues. Where can I find this Issue Template?

**Comment by BlueFinBima** [comment]
When you Click "New" to create a new issue, it takes you to the following screen.
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/18526232/b5a0d3b6-b8b3-4ecb-85ee-16e63083e40f)
If you click "Get Started" it presents you with an issue containing the template.

**Comment by BlueFinBima** [comment]
Delivered in 1.6.6070.2
@Shaftoe62 Many thanks for contributing the improved fonts!  Your contribution is much appreciated.
