### ISSUE TITLE
Release 1.6.6060.3 "Setup DCS" bugged for DCS-F16C and other planes -

### ISSUE THREAD

**Issue by specialistward** [HeliosVirtualCockpit/Helios#804]
Release 1.6.6060.3 "Setup DCS" bugged for DCS-F16C and other planes - pressing "Setup DCS" will still give the error of "An updated export script and assoicated files must be installed to support this profile in DCS."

 Apache "Setup DCS"  in DCS interfaces works but many of the other planes is broken

**Comment by BlueFinBima** [comment]
closing as duplicate of #803
