### ISSUE TITLE
AH-64D KU Scratchpad variables sometimes alternate in sync with blinking of sim displays and sometimes they don't.

### ISSUE THREAD

**Issue by Shaftoe62** [HeliosVirtualCockpit/Helios#805]
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/53898212/cb36f189-b889-4d39-b3c9-764f40240e19)

### The Issue:

The Helios DCS AH-64D Apache Keyboard Unit (KU) Schratchpad variables sometimes alternate in concert with the blinking of the simulator displays, and sometimes they don't.

_Interface components in this issue (Helios variables)_

- DCS AH-64D Apache - Keyboard Unit (CP/G) Scratchpad changed
- DCS AH-64D Apache - Keyboard Unit (Pilot) Scratchpad changed

Normally, in "typing mode", and when the cursor blinks, the content of the Scratchpad interface components alternates between an empty string and the current message. In concert with the simulator display.

When you don't give any new input the display goes blank after 60 seconds, and the Helios variable stops alternating and will be empty.

That is perfect for Helios applications. I'm very happy with that. Especially because it is changing/updating all the time. Just how I want it.

But! When you enter invalid input, like an invalid altitude or gun range, the simulator display will blink, but the Helios variable does not alternate it's content. It just has the error message as a static string.

That is unexpected.

### How to reproduce:

To reproduce this you need to run the simulator.

To quickly get an example you can do the following:

![image](https://github.com/HeliosVirtualCockpit/Helios/assets/53898212/8f9ba5d2-04ba-47fb-98a6-3ba6b4d3baae)

1. Go to the weapons page (WPN) on any MFD
2. Push the bottom far right (light grey) action button: MANRNG>XXXX (manual range setting)
3. The KU display will light up and show: MAN RANGE: (and a blinking cursor)
4. Push 1 on the KU

Up to this point the blinking and alternating values works as expected.

But then...

5. If you then push ENTER on the KU

After a second a blinking text appears: MAN RANGE:1
This means you have entered an invalid value. 1 meter is invalid.

But also: The value (content) of the interface component (Helios variable) is now no longer alternating. It's now a static string with the error message.

**Another difference:**

In the normal typing mode the alternating of the Helios variable content stops after 60 seconds without new input, in concert with the blinking of the display.

The error messages keep on blinking on the display indefinately. And the Helios variables remains static (not alternating).

**Also noteworthy:**

In the normal typing mode there is a cursor present.

In the error cases there is no cursor but there is always a colon in the string.

If you enter a correct value for the gun range (1000), then the simulator display goes dark right away and the Helios variable will be empty and static. That is fine as it is.

### Expected behaviour:

I would expect the error messages from the KU Scratchpads to alternate(blink) just like the normal typing does.

### Info:

Helios 1.6.6002.0000
Latest DCS Open Beta
BMS version ?

### Issue happens:

It's just there in the Interface.

### Context:

I'm working on a panel that consists only of the Schratchpad display(s) and which is positioned at the center bottom of my main monitor. Where it sits right above my two Stream Decks XL, which have the full KU as physical buttons in a shared profile.

I want the panels(s) to be hidden from the main monitor when the KU scratchpad dislay(s) are blank. And blink in concert with the simulator display(s).

I use plural here because it involves the panels/displays for both the Pilot and the CPG.

I use the normal alternating of the Helios variables to determine if the panel needs to be shown. By combining it with a timer so that if it stops changing for 1 (or 2) seconds, the panel will be hidden.

I don't have that for the error mesages. These stop changing right away and that made the panels disappear.

Eventually I figured out a way to make an exeption for the error messages, based on the content (colon present in string).

So in those cases I use two more timers. One to make it blink and another one to have a countdown from 60 seconds to eventually hide the panel because otherwise it's too distracting too long.

But now I solved it for myself, I wonder if this Helios behaviour is fully intentional. 

I think it would be better if the error messages would be alternating just like they blink on the actual simulator displays.

**Comment by BlueFinBima** [comment]
@Shaftoe62 Thanks for the recreation details.  I was with you up to point 5, but after that I don't understand your "Another difference:" nor "Also noteworthy:".

I reacquainted myself with the contents of the scratchpad and the mechanism is much simpler than I remember it being with the result that  **I think** I can improve the scratchpad pretty easily.  Whether this cures all of the issues you're seeing I cannot tell, but to be frank, if this isn't the complete fix, then I'll have to declare the remainder as "Won't Fix".

If you want to have a play, then putr the attached Apache  driver in `%userprofiles$\Saved Games\DCS.openbeta\scripts\Helios\drivers\` (after unzipping it).

[AH-64D_BLK_II.zip](https://github.com/HeliosVirtualCockpit/Helios/files/14232922/AH-64D_BLK_II.zip)

**Comment by Shaftoe62** [comment]
Hi, if I try to use your file I get this configuration error.

And I can't run the profile.

![image](https://github.com/HeliosVirtualCockpit/Helios/assets/53898212/edd92319-fa1e-4760-a513-45187edc99f2)

![image](https://github.com/HeliosVirtualCockpit/Helios/assets/53898212/39ae85a0-fa45-4d21-8fee-a40291eb35b0)

**Comment by BlueFinBima** [comment]
@Shaftoe62 Ignore Profile Editor.  In Control Center, turn off the Preflight and the driver should load up ok.

**Comment by Shaftoe62** [comment]
@BlueFinBima

That completely fixes all the issues in one stroke. Now the signal is exactly the same as the simulator display(s). Excellent!

I didn't know for sure what caused the secondary issues (another difference, also noteworthy). Obviously they were but 
appearances of the same issue.

### One Question:

Is the AH-64D_BLK_II.lua driver the only thing the **preflight** checks? I do need my profile error log for debugging.

Or should I best return to the previous (original) driver and wait for the next release before altering my profile?

**Comment by BlueFinBima** [comment]
###"One Question"
PreFlight checks many things, but it is independent of the logging which still takes place.  Preflight is there to stop the unwarey from trying to start a profile when there are things which are likely to cause problems.  
Your call whether you reverse the changes.

**Comment by Shaftoe62** [comment]
@BlueFinBima

Is there maybe a list or overview of what the preflight checks?

I know that some things can be "configured" in the profile itself (like the management of the Export.lua) so I can use a customized HeliosExport16.lua.

But I did not find a setting to use (test) a  customized driver. Except switching off the preflight check, like you suggested.

And I'm not really comfortable with switching off the preflight check if I'm not quite sure of what I'm actually switching off.

**Comment by BlueFinBima** [comment]
> Is there maybe a list or overview of what the preflight checks?
No
> But I did not find a setting to use (test) a customized driver. Except switching off the preflight check, like you suggested.
There isn't one.  Just keep an eye on the "Control Center.log" (pre run messages) and "Control Center Problem.log" (cumulative).

**Comment by BlueFinBima** [comment]
Delivered in 1.6.6070.2
