### ISSUE TITLE
Mirage F1 EE no Viewports

### ISSUE THREAD

**Issue by ToastyBanK3nobi** [HeliosVirtualCockpit/Helios#810]
Hey @BlueFinBima,

i´´m using Helios for quiet some time now. And i´ve used it since then every day in every Plane. I´ve made an all-in-one Profile, which runs great with every plane so far. Since 2 or 3 Days i´ve got the F1 as a testperiod-plane, and naturally also put their Viewports into my profile, reverted all patches and reinstalled them as well as reconfigured, so every check is green including save the profile in helios profile editor. Unfortunately i don´t have the viewports when i´m sitting in the F1, and what i don´t understand is that it´s the only plane where this happens. I´ve also quickly tested the CE Variant, it´s the same.

Any Ideas what i could be doing wrong or is it broken maybe?

Using the newest Version of the Game and Helios

With Kind Regards
ToastyBanK3nobi

p.s. english isn´t my native, but i hope it´s readable and understandable... thx mate

**Comment by BlueFinBima** [comment]
@ToastyBanK3nobi There are no viewports for this/these aircraft because I don't own these module, and nobody has offered to provide the changes necessary for the creation of the patches, or offered to test the patches.
If you wish to be that person who provides the patched files needed for the viewports then please attach the complete file(s) to this issue.

**Comment by ToastyBanK3nobi** [comment]
@BlueFinBima unfortunately i´m lacking the knowledge for this, but i would offer to test them. But if it is explanable how to do the changes, maybe you could advise me...

**Comment by BlueFinBima** [comment]
Maybe you should ask about the Mirage F1 viewports in this [Discord Channel](https://discord.gg/6rKT76Qg).  Maybe others with the module have already manually patched the needed files.

**Comment by BlueFinBima** [comment]
I was possibly reading too much into this request... If someone tells me the sizes of the two items which already have patches, then I'll create Viewports Extents for these patches.

**Comment by BlueFinBima** [comment]
Delivered in 1.6.609
