### ISSUE TITLE
F16 Fuel gauge and fuel flow gauge wont work, no telemetry bind for them like other guages

### ISSUE THREAD

**Issue by gdpalumbo** [HeliosVirtualCockpit/Helios#812]
All other F16 gauges i have input work and have a telemetry item to bind to them to get them to work.  The remaining fuel gauge and fuel flow gauge i cannot get to work as they have no telemetry item to bind to their functions.  I have had no problem getting any of the other gauges i use to work.  Captain Zeen did get a working fuel flow gauge but he did this by very unconventional means, if the fuel flow meter could work in helios, he would have just input it as a gauge instead of literally building his own gauge, numbers and grabbing dcs outputs for the 1k,10k,100k and binding them to his number locations.  There are multiple forums on the internet with others asking for this and there still is no solution.

### Steps to Reproduce the problem
Steps to reproduce the behaviour:
1. Insert gauges
2. go down to the binding menu
3. CLick on f16 and go down to telemetry
4. *You will find no option for these two gauges in telemetry. You will find totalizer options under fuel gauge outside of the telemetry section but these give an error when trying to bind as i don't think thats what they are for.

### Expected behavior
Expect the fuel gauge to showe remaining fuel in pounds at the bottom and for the needles to move and show individual tanks. Using latest helios version as it was just updated.  Using latest dcs version that was just updated as of this past week, and new viewport pacthes have been installed, no errors on helios software.

**Comment by BlueFinBima** [comment]
@gdpalumbo 
> I guess I could also dissect captain zeens profile and remove everything except those two gauges and see if I can do that.

You're likely to hit a problem with Captain Zeen's profile using a different form of interface from your own Profile so I don't rate your chances of doing this very highly.

**Comment by Todd1215** [comment]
You request has been added to issue #811. I am going to close this issue and track all updates / changes in #811.
