### ISSUE TITLE
BF AV8B Profile Right MPD - Gain Rocker non-functional

### ISSUE THREAD

**Issue by MadKreator37** [HeliosVirtualCockpit/Helios#820]
* There is no "Issue" section in the AV8B profile's Github, so I published it here*

If you are having problems installing / configuring / using a profile then you should use the support process for the provider of that profile.

- [ x] I have read [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)
---
### Describe the Helios Issue

Right MPD Gain rocker has no Input, Output, or graphical changes when pressed.

 - Helios Version 1.6.6070.0002
 - DCS Version 2.9.3.57104

### The problem happened while using 
(place an 'x' between the square brackets for all that apply)
 - [ ] Profile Editor
 - [ x] Control Center
 - [ ] Keypress Receiver
 - [ ] Something else (*remember to tell us what it is*)

**Comment by BlueFinBima** [comment]
@MadKreator37 [There is now](https://github.com/HeliosProfiles/DCS-AV-8B-NA-Profile-BlueFinBima/issues) - you just needed to ask ;-)
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/18526232/b1e06675-981f-4938-ba1e-9839025fc0fe)
