### ISSUE TITLE
Unplugging a controller causes Helios to crash

### ISSUE THREAD

**Issue by rocketeer998** [HeliosVirtualCockpit/Helios#821]
If I add a joystick or throttle as an interface, unplugging it will crash Helios.

![image](https://github.com/HeliosVirtualCockpit/Helios/assets/145094080/f5d2549f-b350-4cb7-a372-0183bd3b1b20)

**Comment by BlueFinBima** [comment]
Thanks for reporting this.  If raising future bug reports, please use the Bug Report template
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/18526232/e2798d29-ed4e-4e4f-9092-013601374141)

**Comment by rocketeer998** [comment]
ok thanks. I didn't know you have separate bugs from issues.

**Comment by BlueFinBima** [comment]
Delivered in 1.6.608
