### ISSUE TITLE
Add MSFS2020 interface

### ISSUE THREAD

**Issue by macieksoft** [HeliosVirtualCockpit/Helios#823]
Would be good to have MSFS2020 support for lvars, simvars etc...
Currently there are multiple apps that can do that, but they are all payware.

Shouldn't be too much of a problem to implement interface for MSFS2020.

**Comment by Todd1215** [comment]
Typically how NEW Helios interfaces are developed is by someone who has the knowledge of the target app/api and Helios development. I'm not too sure there is any current dev working on such an interface.

Do you have any links to documentation for MSFS2020 and how it works? Helios is open source and free to anyone to fork the code and work on it themselves.

**Comment by BlueFinBima** [comment]
This issue can be re-opened if a Pull Request is received with the requested function.
Closing because not in plan.
