### ISSUE TITLE
Jerk on STBY instruments for F18C

### ISSUE THREAD

**Issue by Coolands** [HeliosVirtualCockpit/Helios#830]
Hello I am using the latest version 1.6.6090.0002 of helios with the latest profile of Capt zeen F18 but the instruments do not have a fluid but jerky movement unlike the DDI display. 
I can't understand why. 
My PC is recently equipped with Windows 11 I fly with an average of 70 fps. 
I am attaching a video to illustrate. 
I have 4 screens in total.

https://github.com/user-attachments/assets/1a599038-3c55-4bcc-b946-6010e0785569

**Comment by Todd1215** [comment]
This issue typically occurs because you have monitors with different refresh rates. Make sure all your monitors are set to the same refresh rate.

**Comment by Coolands** [comment]
THANKS YOU so much you are my hero. One of my four screen dont has the same value
