### ISSUE TITLE
F16 EHSI has no option for telemetry data to display flags, course, bearing

### ISSUE THREAD

**Issue by gdpalumbo** [HeliosVirtualCockpit/Helios#831]
# HELP US TO HELP YOU

If you are having problems installing / configuring / using a profile then you should use the support process for the provider of that profile.

- [ ] I have read [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)
---
### Describe the Helios Issue
This isn't so much a bug as something that isn't included in the current version.  The EHSI needs telemetry data to display the course flag, bearing flag, desired heading flag, miles to destination when using tacan etc.. when these things change on the hsi in the sim, we need them to change on the ehsi in helios, as far as i can see, the only items that allow these things to be changed is when button presses in by buttons in the cockpit that are using helios to process them are pressed, and you can create a trigger from that....am i reading that right?

### Steps to Reproduce the problem
Steps to reproduce the behaviour:
1. *Go to '...'*
2. *Click on '....'*
3. *Scroll down to '....'*
4. *See error*

### Expected behavior
*A clear and concise description of what you expected to happen.*

### Screenshots
*If applicable, add screenshots to help explain your problem.*

### Please complete the following information:
 - Helios Version latest updated 7-23-24
 - DCS Version latest version as of 7-23-24
 - BMS Version

### The problem happened while using 
(place an 'x' between the square brackets for all that apply)
 - [ ] Profile Editor
 - [ ] Control Center
 - [ ] Keypress Receiver
 - [ ] Something else--just not an available feature.

### Additional context
*Add any other context about the problem here.  (eg this problem started happening when I ....)*

**Comment by Todd1215** [comment]
Are you sure you are not looking at the Falcon BMS EHSI ? That is the only stock one that comes with Helios. it only works with Falcon BMS and takes all data from Falcon BMS's sharedmemory  so there is no need to have any data bindings for this particular guage. If you are referring to a different guage then please do some additional explaining on which control it is. Pictures are worth a thousand words.

**Comment by BlueFinBima** [comment]
@gdpalumbo Since you have a date against DCS, I'm assuming that your request is against the interface for the DCS F-16C_50 from ED.  The current JSON interface was generated from external sources and is far from perfect and is not used by the Helios Profile from Capt Zeen which most people use.  The JSON interface needs a significant amount of work to bring it close to being complete (the EHSI is only one example of this), and while some work has been done on improving the interface, it is not a high priority task for the Helios project given the limited resources on this project.

Flagging as an enhancement request.

**Comment by gdpalumbo** [comment]
I ended up using the viewport which was a much better option, I don’t blame you for not doing it if the viewport is available.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
