### ISSUE TITLE
AH64D TEDAC Simulator Viewport Still Has Old Naming

### ISSUE THREAD

**Issue by MadKreator37** [HeliosVirtualCockpit/Helios#834]
In the toolbox, the TEDAC /combined control has the correct new viewport name 'TEDAC' however the standalone "Simulator Viewport" still has the name AH64D_TEDAC and is not functional.

*Tested and confirmed not functional with old naming but works correctly when changed to TEDAC.

### Please complete the following information:
 - Helios Version Current
 - DCS Version Current

### The problem happened while using 
(place an 'x' between the square brackets for all that apply)
 - [x ] Profile Editor
 - [ x] Control Center
 - [ ] Keypress Receiver
 - [ ] Something else (*remember to tell us what it is*)

**Comment by BlueFinBima** [comment]
I've altered the JSON for the TEDAC to suppress the prefix in order to create a viewport with the name TEDAC.  This will go out at the same time as the Chinook ships.
