### ISSUE TITLE
Triple monitor issue, Everything squished to the left leaving the right monitor mostly black

### ISSUE THREAD

**Issue by Blindlookout** [HeliosVirtualCockpit/Helios#836]
I have an issue where when I use helios things on my main monitors get squished to the left just like in the picture I have included. I have fussed with Lua files, settings, read forums and so on. I have a total of 5 monitors 3 main monitors and two touchscreens. The scaling on all screens is the same, the resolution on the three main screens is 3840x2160 and the two touchscreen monitors are run at 1920x1080 each. The main menu screen appears correctly on one single central screen, but when I start a mission everything becomes squished to the right. Everything is also not centered and the aspect ratio is weird (I have double checked the Lua files to see if the ratio is off.) I have been fighting with this issue endlessly. I can get DCS to run just fine, but when I set my display settings to "helios" things get wonky. The helios profiles seem to display correctly on the two touchscreen monitors, just the 3 main game monitors are affected. I am at a loss as I feel like I have checked everything I can think of to fix the issue, at least as far as my current knowledge allows me. I discovered other people having the same issue but I did not find anyone who had a solution. Can someone please help provide some insight, I am happy to provide any info you might need?
![IMG_2119](https://github.com/user-attachments/assets/2338efba-aaa8-413a-a28b-aa796e69bb8c)

**Comment by Blindlookout** [comment]
I have this exact problem as this user, I mean exact.

**Comment by BlueFinBima** [comment]
Hi @Blindlookout, this project uses issues for addressing Helios bugs.  General support is provided by the community on Discord.  Please refer to [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help) in the Wiki.  Item 7. describes Discord.
Regards
