### ISSUE TITLE
Unhandled exception in WindowsBase when dragging bindings

### ISSUE THREAD

**Issue by tomaspaseka** [HeliosVirtualCockpit/Helios#838]
### Describe the Helios Issue
* I'm getting unhandled error in WindowsBase, when I'm dropping any Action to control output.

### Steps to Reproduce the problem
1. Open Binding panel
2. Select some control
3. Switch to Output
4. Select some action and drag it to e.g. pushed "Bindings"
5. Drop it -> error appears

### Expected behavior
*I can set binding properly

### Screenshots
*![image](https://github.com/user-attachments/assets/162c00dd-60bc-4864-887a-c14b3972177b)

### Please complete the following information:
 - Helios Version 1.6.6101.0002
 - DCS Version 2.9.7.59263
- Plane F-15E

### The problem happened while using 
(place an 'x' between the square brackets for all that apply)
 - [X] Profile Editor
 - [ ] Control Center
 - [ ] Keypress Receiver
 - [ ] Something else (*remember to tell us what it is*)

### Additional context
*Add any other context about the problem here.  (eg this problem started happening when I ....)*

**Comment by BlueFinBima** [comment]
Hi Tomas,
Firstly, thanks for filling out the template.

Your screenshot suggests that you've successfully dragged at least two (presumably) interface output bindings onto controls, so I'm guessing that this does not happen every time you're dragging a binding.  Can you narrow down when this problem happens, __and when it does not happen__?

If you're able to recreate this problem, then please attach `%userprofile%\documents\Helios\Profile Editor Problems.log` and `%userprofile%\documents\Helios\Profile Editor.log` of the run where the problem happened. 

Is this the first time you're using Profile Editor?

Have you seen this problem when using other releases of Helios?

I'm not able to reproduce this problem BTW.

**Comment by tomaspaseka** [comment]
I've created my cockpit few months ago (not sure witch version). I've experiences this issue from time to time, but now it's 100% reproducible and I'm unable to change any mapping. 

I've tried that on two different computers, one with DCS and another without, but it's reproducible on both.

I've created new profile and it works fine, so it seems that problem is my cockpit. That is strange because cockpit is working just fine.

[Profile Editor Problems.log](https://github.com/user-attachments/files/17017684/Profile.Editor.Problems.log)
[Profile Editor.log](https://github.com/user-attachments/files/17017685/Profile.Editor.log)

[F-15E-remote-DCS-ext-6-local.zip](https://github.com/user-attachments/files/17017726/F-15E-remote-DCS-ext-6-local.zip)

**Comment by BlueFinBima** [comment]
Hi Tomas, thanks for the additional information and attaching the files.
If you copied your profile's `.hpf` file **and** the `.hply` file to the second computer, then I think there is a good chance that the problem is a corrupt `.hply` file.  If this is the case, I suggest renaming the `.hply` file to something with a different file suffix, and re-run the tests.  Profile Editor will not care that the `.hply` file is missing.

If this fixes or changes the problem, then please attach the `.hply` file that corresponds to the profile you sent me.  

I see no problems binding new elements to the profile you included above.
 
Regards

**Comment by tomaspaseka** [comment]
Thanks that was it. I've deleted .hply and it works fine.

Thanks a lot.

**Comment by BlueFinBima** [comment]
Closing as stale.
