### ISSUE TITLE
Many DCS CH-47F bindings no longer working after 2.9.9.2280 

### ISSUE THREAD

**Issue by BlueFinBima** [HeliosVirtualCockpit/Helios#846]
# HELP US TO HELP YOU

If you are having problems installing / configuring / using a profile then you should use the support process for the provider of that profile.

- [X] I have read [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)
---
### Describe the Helios Issue
Many DCS CH-47F bindings no longer working after 2.9.9.2280 

### Expected behavior
The CH-47F interface should work correctly after 2.9.9.2280

### Please complete the following information:
 - Helios Version 1.6.611
 - DCS Version 2.9.9.2280
 - BMS Version

### The problem happened while using 
(place an 'x' between the square brackets for all that apply)
 - [X] Profile Editor
 - [X] Control Center
 - [ ] Keypress Receiver
 - [ ] Something else (*remember to tell us what it is*)

### Additional context

Reported by @MadKreator37

**Comment by BlueFinBima** [comment]
2.9.9.2280 changed the devices.lua in a non-backward compatible manner.

**Comment by BlueFinBima** [comment]
There were further module changes made by ED in early December which broke the CDU.   This has been fixed in https://github.com/HeliosVirtualCockpit/Helios/commit/f3aeb9e6e4678d76ad1a82bf8ebeaebb2c67d057

**Comment by MadKreator37** [comment]
All working in 1.6.6120
