### ISSUE TITLE
Clickable Potentiometer Image Issue

### ISSUE THREAD

**Issue by MadKreator37** [HeliosVirtualCockpit/Helios#848]
### Describe the Helios Issue
- When rotation is confined to "allow only when un-clicked", the "clicked' image does not follow the rotation of the pot. and after clicking, resets the pot to original position.
- When rotation is confined to "allow only when clicked", the 'UN-clicked" image now does not follow the rotation and when the click is released the pot resets back to original position,

### Expected behavior
- Both cicked and un-clicked images follow rotation regardless of setting or "clicked state"

### Please complete the following information:
 - Helios Version 1.6.611.5
 

### The problem happened while using 
(place an 'x' between the square brackets for all that apply)
 - [ ] Profile Editor
 - [ x] Control Center
 - [ ] Keypress Receiver
 - [ ] Something else (*remember to tell us what it is*)

### Additional context

- The clickable rotary encoder does not exhibit this behavior. It functions as expected with all 3 "rotation state" settings.
- When the clickable pot rotation is not confined to a clicked or un-clicked state, it also functions exactly as expected.

**Comment by BlueFinBima** [comment]
@MadKreator37 The code deliberately sets the image back to the initial value for the control.  I'm certain that there was a use case I had in mind when I did this, but for the life of me, I can't think what that use case would have been.  Clearly, the logical approach is for the encoder and potentiometer to work in a similar manner which probably overrides that unremembered use case and this is what I'll go forward with.

**Comment by MadKreator37** [comment]
Works like a charm in 1.6.6120

**Comment by BlueFinBima** [comment]
Fixed in shipped release  1.6.6120,2
