### ISSUE TITLE
Error when load a profile

### ISSUE THREAD

**Issue by Bigopus** [HeliosVirtualCockpit/Helios#851]
after update the latest version, I can´t open an existing profile for editing. the follow message pops up and by close, the helios will close.
version 1.6.6110.5. 
I can´t open any previous created profile with the helios control center too.
![grafik](https://github.com/user-attachments/assets/e1d8f68a-99f4-445d-a950-c31ea375d73d)

regards

**Comment by BlueFinBima** [comment]
@Bigopus Please attach the profile's `.hpf` file to this issue an I'll take a look.

**Comment by Bigopus** [comment]
one of my profiles I can´t open.
[A10CII_V6vr.zip](https://github.com/user-attachments/files/18053642/A10CII_V6vr.zip)

**Comment by Bigopus** [comment]
After reinstall some times the Helios works fine now. First I could not deinstall because a .dll file was missing. I wrote an emty and this was okay. 
Thank you
