### ISSUE TITLE
In Falcon Interface the Pilot Callsign not populated

### ISSUE THREAD

**Issue by Todd1215** [HeliosVirtualCockpit/Helios#852]
# Scenario
A user has multiple installs of Falcon BMS and one of those installs the user has not run Falcon BMS for the first time and set the pilots callsign. This results in the Helios reporting that the pilot callsign has not been set, even if that is not the BMS instance that the profile is set to.

This can easily be reproduced:
1. have multiple installs of BMS and by removing the PilotCallsign registry entry from the Benchmark Sims Windows registry entry for any register BMS instance
2. run Helios Profile Editor
3. note the error in Interface Status TAB that the Pilot Callsign is not detected

**Comment by BlueFinBima** [comment]
Adding Awaiting Delivery label

**Comment by BlueFinBima** [comment]
Fixed in shipped release  1.6.6120,2
