### ISSUE TITLE
Ellipsis in the F/A-18C UFC Scratchpad Control from the Toolbox When Precise Coordinates are used

### ISSUE THREAD

**Issue by BlueFinBima** [HeliosVirtualCockpit/Helios#854]
Reported by @MadKreator37 on Discord.

- [X] I have read [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)
---
### Describe the Helios Issue
*A clear and concise description of what the bug is, when it started to happen and any recent changes.*

### Steps to Reproduce the problem
Steps to reproduce the behaviour:
1. Go to F/A-18C JDAM Training in ED
2. Follow training and when coordinates are entered in the UFC, the Helios version will be incomplete with an ellipsis at the end of the display.

### Expected behavior
Toolbox version of the F/A-18C UFC should match the contents of the in-cockpit scratchpad.
### Screenshots
![screenshot_20241212121232](https://github.com/user-attachments/assets/4663fc06-cfcb-48e0-9ec3-6bb6813e92b3)

### Please complete the following information:
 - Helios Version [*1.6.6100.5*]
 - DCS Version [*2.9*]
 - BMS Version n/a

### The problem happened while using 
(place an 'x' between the square brackets for all that apply)
 - [ ] Profile Editor
 - [X] Control Center
 - [ ] Keypress Receiver
 - [ ] Something else (*remember to tell us what it is*)

**Comment by BlueFinBima** [comment]
Temporary fix is to reduce the height of the UFC by a few pixels while keeping the width constant.

**Comment by BlueFinBima** [comment]
Observed during recreation, the cuing bar on the options display is sometimes solid. This probably means that the translation in the F/A-18C driver or the conversion string in the scratchpad needs adjustment.

**Comment by BlueFinBima** [comment]
related to #605

**Comment by BlueFinBima** [comment]
> Observed during recreation, the cuing bar on the options display is sometimes solid. This probably means that the translation in the F/A-18C driver or the conversion string in the scratchpad needs adjustment.

Looks like ED changed the character they used for the cueing indicator to a `|` so this has now been added to the mapping that relates to the `:` in the display.

**Comment by MadKreator37** [comment]
looks good in 1.6.6120
