### ISSUE TITLE
Code signing - Decide if/how to do this

### ISSUE THREAD

**Issue by derammo** [HeliosVirtualCockpit/Helios#93]
* created by @BlueFinBima on 2018-09-15 09:17:19 +0000 UTC

### please make sure to close upstream issue when this item is closed

**Comment by derammo** [comment]
@BlueFinBima I would like to close this issue since I am at least part of the legal entity that would have to sign the releases and I have no intention of doing so.

**Comment by derammo** [comment]
specifically, we don't have any systems in place to ensure the integrity of a build so any signature would just be taking responsibility for something that isn't actually being managed

**Comment by BlueFinBima** [comment]
Fair point.  Keen to keep making MD5 and SHA2 checksums available for the deliverables though.

**Comment by derammo** [comment]
@BlueFinBima I think I am missing something.  Our only delivery point now is GitHub (no more ED files.)   So why would we need checksums?  We don't have mirrors that could corrupt our files in transit and GitHub is https.   I commented elsewhere when I got rid of the checksums but did not get a reply.

**Comment by BlueFinBima** [comment]
Fundamentally you are correct, but not everyone trusts GitHub, and having a checksum basically allows people who have downloaded to verify that what they downloaded is what we intended.  It also provides some protection if some of our colleagues distribute from their own websites.

**Comment by derammo** [comment]
what tool are windows users using to check the checksums?   just so I can make sure we present them in the appropriate format.  I noticed you had MD5 in there, which are basically useless security wise.  so I am wondering what else do the tools people use now support besides sha-1?   one of the sha-2 functions (which are actually secure, as far as I know.)

**Comment by derammo** [comment]
also: if you don't trust github, where do we store the hashes?

**Comment by BlueFinBima** [comment]
All valid points, but having a checksum listed for the msi would allow someone who has an msi sitting on their machine to be able to know that his has not been tampered with since being downloaded, although I would accept that anyone who cares that much should just download the file again from Github. 
Clearly you think it is pointless, so I'm happy to bow to your greater experience in this area.
