### ISSUE TITLE
Gadroc Todo: Switch from Old Managed DirectX so SharpDX

### ISSUE THREAD

**Issue by derammo** [HeliosVirtualCockpit/Helios#94]
* created by @BlueFinBima on 2018-09-16 15:49:48 +0000 UTC

### please make sure to close upstream issue when this item is closed

**Comment by derammo** [comment]
@BlueFinBima I thought this was done?

**Comment by BlueFinBima** [comment]
Could this be referring to our continued use of HIDSharp?  SharpDX is being used.  Unless someone tells us that there is a limitation with the current DirectX interfaces, or a deprecation, then I agree that this should be closed. 

*** Unclear what this refers to ***
