### ISSUE TITLE
Gadroc Todo: Move images out of assembly into filesystem

### ISSUE THREAD

**Issue by derammo** [HeliosVirtualCockpit/Helios#95]
* created by @BlueFinBima on 2018-09-16 15:49:53 +0000 UTC

### please make sure to close upstream issue when this item is closed

**Comment by derammo** [comment]
I don't think this is a good idea.  It invites a new sort of problem where people modify the built in images and the basic controls break as a result and we end up with support issues.

Instead, I would prefer we add a  button in "Tools" to export all the images that are in our resource DLLs to a specified location.  So people can export the images and edit/use them as they wish, but the Helios built in controls will still use the unmodified resources.

**Comment by BlueFinBima** [comment]
Interesting notion.  Who is asking for this?  If nobody, then I'd suggest freezer.

**Comment by BlueFinBima** [comment]
If freezer, we need a new issue to deliver the tooling, or put in the freezer.  This should be closed because it is suggesting we reverse course.  Thoughts?

**Comment by derammo** [comment]
users have several times asked how to edit the images for their own use.   I thought about getting rid of resources entirely and just having all images (PNG) and drawings (XAML drawings) be unpacked in the installation folder.  But then I realized this could cause breakage.  So my suggestion is we implement the spirit of this request, which is "we don't charge for image packs any more, so share the images with our users" by having a button in the Tools menu that just iterates all image and drawing resources and writes them to equivalent paths in Documents\Helios\Images\[Helios|FA-18C|...] using the paths that we have from the magic resource paths.   Don't write any images that are already present (in case already hacked up.)    So people can hit this button once if they want to get all our images and then they can do as they wish with them afterwards.

I think that implements the spirit of this request without the fragility downside.

**Comment by BlueFinBima** [comment]
TBH, I'd rather just point interested users to GitHub to get the images.  I'm not aware of this request coming up in recent times.
Setting to flags to enhancement and fridge.
