### ISSUE TITLE
Gadroc Todo: Split Helios Assembly into Helios and HeliosUI (Move all dependencies on WPF to HeliosUI)

### ISSUE THREAD

**Issue by derammo** [HeliosVirtualCockpit/Helios#96]
* created by @BlueFinBima on 2018-09-16 15:49:59 +0000 UTC

### comment by @derammo on 2020-05-25 00:01:06 +0000 UTC

ha! this is funny because I had the same thought recently.  But it doesn't work any more because all the dialogs for DCS interfaces and such are in Helios now.   Really Helios core should just be the runtime for a collection of interfaces and visuals and the bindings between them.  Then you could have only view models in that library and repeatedly touch yourself (or not) and chant "MVVM" while separating all the actual UI code out to another library that also depends on HeliosUI.  

### please make sure to close upstream issue when this item is closed

**Comment by derammo** [comment]
I would like to close this.   It creates no value other than gratification for MVVM fans.

**Comment by BlueFinBima** [comment]
Won't fix?
