### ISSUE TITLE
Gadroc Todo: Fix save/load crash bug on EOS servos

### ISSUE THREAD

**Issue by derammo** [HeliosVirtualCockpit/Helios#97]
* created by @BlueFinBima on 2018-09-16 15:50:27 +0000 UTC

### please make sure to close upstream issue when this item is closed

**Comment by derammo** [comment]
do we support EOS servos at this point?

**Comment by BlueFinBima** [comment]
As far as I know, yes.  I certainly don't see a good reason to remove it.

Status:  Closing until diagnostics can be provided by an EOS user with the problem.
