### ISSUE TITLE
Gadroc Todo: Add exe scanning for CMSC, CMSP, Radio and PUI-800 (from forums)

### ISSUE THREAD

**Issue by derammo** [HeliosVirtualCockpit/Helios#98]
* created by @BlueFinBima on 2018-09-16 15:51:50 +0000 UTC

### please make sure to close upstream issue when this item is closed

**Comment by derammo** [comment]
any idea what this is?  I guess there was a forum post about some clever way to get these without exported viewports?  do we care?

**Comment by BlueFinBima** [comment]
No idea what this is about.  A quick search on ED Forum enlightened 0%.  
Closing until more information as to why this is needed appears.

**Comment by derammo** [comment]
I bet someone has a hack where they directly get the values of these very small exports from DCS without using viewports.  But I super don't care :)
